function hdfwarn(status)
%Use the last error generated by the HDF library as a warning.

%   Copyright 1984-2006 The MathWorks, Inc.
%   $Revision: 1.1.6.4 $  $Date: 2006/03/13 19:46:43 $

if status==-1
  error_code = hdfhe('value',1);
  if strncmpi(hdfhe('string',error_code),'no error',8)
    msg = sprintf('The NCSA HDF library reported an unknown error.');
  else
    msg = sprintf('The NCSA HDF library reported the following error: \n%s', ...
                  hdfhe('string',error_code));
  end
  warning('MATLAB:hdfwarn:generic', '%s', msg)
end
