function buildPanelMenuOptions(dp, hParentMenu)
%BUILDPANELMENUOPTIONS Builds menu items to auto-hide and lock the dialog
%panel. This method is used by both HistogramVisual.createNTXMenus() and
%createBaseContext() methods to add these menu items to the main menu and
%context menu. hParentMenu can either be a context menu handle or a
% handle to a main menu.

%   Copyright 2010 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2010/03/31 18:39:31 $

% Lock dialog panel widths and order
uimenu('parent',hParentMenu, ...
    'label','Lock Panel', ...
    'separator','on', ...
    'callback',@(h,e)togglePanelLock(dp), ...
    'checked',uiservices.logicalToOnOff(dp.PanelLock),...
    'tag','LockPanelMenu');

% Add Auto-hide menu, configure checkmark
uimenu('parent',hParentMenu, ...
    'label','Auto-hide Panel', ...
    'callback',@(h,e)toggleAutoHide(dp), ...
    'checked',uiservices.logicalToOnOff(dp.AutoHide),...
    'tag','AutoHideMenu');


% [EOF]
