function init(dp,hUser)
% First-time initialization DialogPanel object with a new
% graphical application context.

%   Copyright 2010 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $   $Date: 2010/04/21 21:48:58 $
    
initPresenter(dp,hUser); % base class method
hParent = dp.hParent;

% Create body panel for application UI
bg = get(dp.hFigPanel,'backgr');
dp.hBodyPanel = uipanel( ...
    'parent',hParent, ...
    'bordertype','none', ...
    'units','norm', ...
    'background',bg, ...
    'units','pix');
setContextMenuHandler(dp,dp.hBodyPanel,[]); % set app-specific context menu

% Create message that is displayed when body panel is too small
% Message and visibility controlled by hideBodyContentIfTooSmall()
dp.hBodyTooSmallTxt = uicontrol( ...
    'parent',hParent, ...
    'backgr',bg, ...
    'foregr',[.5 .5 .5],... % gray
    'fontsize',10, ...
    'units','pixels', ...
    'tag','dialogmgr_small_display_msg',...
    'horiz','center', ...
    'vis','off', ...
    'style','text');

% Create auto-hide vertical bar
%
% Set to inactive so mouse click registers as mousedown, not as buttondown
% fcn on the uicontrol.  Also, no position needs to be set here.
splitter = dialogmgr.SplitterControl(hParent);
splitter.ArrowCount = dp.SplitterArrowCount;
splitter.BarSize = dp.SplitterBarSize;
splitter.ForegroundColor = [.5 .5 .75];
splitter.Type = 'Bar';
dp.hBodySplitter = splitter;

% Create panel to hold all graphical dialogs within the DialogPanel
dp.hDialogPanel = uipanel( ...
    'parent',hParent, ...
    'bordertype','none', ...
    'units','pix', ...
    'background',bg, ...
    'tag','dialog_panel_top_parent',...
    'deletefcn',@(h,e)deleteDialogPanel(dp));
setContextMenuHandler(dp,dp.hDialogPanel,dp); % set context menu

% Create message that is displayed when dialog panel has no docked dialogs
% This could be confusing to a user without a message indicating why the
% panel is otherwise blank.
dp.hNoDockedDialogs = uicontrol( ...
    'parent',dp.hDialogPanel, ...
    'backgr',bg, ...
    'foregr',[.5 .5 .5],... % gray
    'fontsize',10, ...
    'units','pixels', ...
    'tag','docked_dialog_text',...
    'horiz','center', ...
    'vis','off', ...
    'style','text');

% Use dummy values for sliderstep, min, max for now.
% These get reset in resizeScrollBar()
dp.hScrollBar = uicontrol( ...
    'parent',hParent, ...
    'style','slider', ...
    'units','pix', ...
    'tag','dialogmgr_scroll_bar',...
    'backgr',bg, ...
    'Value',0.0, ...
    'min', 0.0, ...
    'max', 1.0);

% Setup auto-scroll timer for continuous scrolling while mouse remains
% stationary at top or bottom of dialog panel
dp.hAutoScrollTimer = timer( ...
    'ExecutionMode','FixedDelay', ...
    'BusyMode','drop', ...
    'tag','autoscrolltimer', ...
    'TimerFcn',@(h,e)mouseDragDialog(dp,true), ...
    'Period',.04);

% Timer for DialogPanel auto-hide
%
% StartDelay controls the watchdog time-out period
% Period is irrelevant
% Note that we do NOT reset the timer on every mouse motion; we allow the
% running timer to expire first.  That means we get an inconsistent time to
% auto-close, no greater than StartDelay, but possibly much shorter.
dp.hAutoHideTimer = timer( ...
    'ExecutionMode','singleShot', ...
    'StartDelay',1, ...
    'BusyMode','drop', ...
    'tag','autohidetimer', ...
    'TimerFcn',@(h,e)autoHideTimerTimeOut(dp), ...
    'Period',0.1);

% Create and cache drag-able outline of info panel
createDialogPanelOutline(dp);

% React to slider changes continuously
dp.hScrollBarAction = addlistener(dp.hScrollBar,'Action', ...
    @(h,e)scrollBarSliderAction(dp));

% Setup resize
% Set listener to track position changes in hFigPanel
resizeParentPanel(dp);
addlistener(dp.hFigPanel,'SizeChange',@(h,e)resizeParentPanel(dp));

end
