function obj = torquescheduler( proxyScheduler )
; %#ok Undocumented
%TORQUESCHEDULER constructor for Torque scheduler

% Copyright 2007 The MathWorks, Inc.
% $Revision: 1.1.6.1 $   $Date: 2007/11/09 19:51:19 $

if ispc
    error( 'distcomp:torquescheduler:unixOnly', ...
           'The Torque scheduler is only supported on UNIX platforms' );
else
    workerType = 'unix';
end

obj = distcomp.torquescheduler;

infoStruc = pParseOutputFromQstat( obj );

if ~isempty( findstr( infoStruc.pbs_version, 'PBSPro' ) )
    warning( 'distcomp:torquescheduler:CouldUsePBSPro', ...
             ['You are using the Torque scheduler with PBS version "%s".\n', ...
              'You may be able to use the ''PBSPro'' scheduler type'], ...
             infoStruc.pbs_version );
end

useJA     = false;
resource  = '-l nodes=^N^';
rshCmd    = 'rsh';
rcpCmd    = 'rcp';
useAttach = false;
stateinds = {'RE', ...
             'HQW'};

set( obj, ...
     'Type', 'Torque', ...
     'Storage', handle(proxyScheduler.getStorageLocation), ...
     'ServerName', infoStruc.server, ...
     'ClusterOsType', workerType, ...
     'ResourceTemplate', resource, ...
     'UseJobArrays', useJA, ...
     'RcpCommand', rcpCmd, ...
     'RshCommand', rshCmd, ...
     'UsePbsAttach', useAttach, ...
     'StateIndicators', stateinds, ...
     'HasSharedFilesystem', true );

obj.setupForParallelExecution( workerType );

% This class accepts configurations and uses the scheduler section.
sectionName = 'scheduler';
obj.pInitializeForConfigurations(sectionName);
