function createControls(this)

    % Copyright 2009-2010 The MathWorks, Inc.

    % Cache string dictionary class
    SD = Simulink.sdi.StringDict;
    
    % Cache GUI utilities class
    UG = Simulink.sdi.GUIUtil;
    
    % Dialog
    DialogTitle  = [SD.ToolName SD.Colon ' ' SD.IGDataImport];
    this.HDialog = UG.CreateDialog(DialogTitle);
    
    % set simulink icon instead of MATLAB icon
    prevState = warning('off','MATLAB:HandleGraphics:ObsoletedProperty:JavaFrame');
    warningCleaner = onCleanup(@() warning(prevState));
    jframe=get(this.HDialog, 'javaframe');
    iconPath = fullfile(matlabroot, ...
                        'toolbox',  ...
                        'simulink', ...
                        'simulink', ...
                        '+Simulink',...
                        '+sdi',     ...
                        'Icons',    ...
                        'simulink.gif');
    jIcon=javax.swing.ImageIcon(iconPath);
    jframe.setFigureIcon(jIcon);
    
    % OK, Cancel, and Help dialog Buttons
    this.OKButton = uicontrol(this.HDialog,           ...                            
                            'FontSize', 10,           ...
                            'Units',    'pixels',     ...
                            'Style',    'pushButton', ...
                            'String',    SD.OK        ...
                            );
    this.CancelButton = uicontrol(this.HDialog,             ...                                  
                                  'FontSize', 10,           ...
                                  'Units',    'pixels',     ...
                                  'Style',    'pushButton', ...
                                  'String',   SD.Cancel     ...
                                  );
    
    this.HelpButton = uicontrol(this.HDialog,             ...                                
                                'FontSize', 10,           ...
                                'Units',    'pixels',     ...
                                'Style',    'pushButton', ...
                                'String',   SD.Help       ...
                                );

    % "Import From" section
    this.ImportFromLabel = uicontrol(this.HDialog,                          ...
                                     'HorizontalAlignment', 'left',         ...                                     
                                     'FontSize',            10,             ...
                                     'FontWeight',          'bold',         ...
                                     'Units',               'pixels',       ...
                                     'Style',               'text',         ...
                                     'String',              SD.IGImportFrom ...
                                     );
    this.ImportFromBaseRadio = uicontrol(this.HDialog,                        ...
                                         'HorizontalAlignment', 'left',        ...                                         
                                         'FontSize',            10,            ...
                                         'Units',               'pixels',      ...
                                         'Style',               'radioButton', ...
                                         'String',              SD.IGBaseWS    ...
                                         );
    this.ImportFromMATRadio = uicontrol(this.HDialog,                         ...
                                        'HorizontalAlignment', 'left',        ...                                        
                                        'FontSize',            10,             ...
                                        'Units',               'pixels',      ...
                                        'Style',               'radioButton', ...
                                        'String',              SD.IGMATFile   ...
                                        );
    this.ImportFromMATLabel = uicontrol(this.HDialog,                           ...
                                        'HorizontalAlignment', 'left',          ...                                        
                                        'FontSize',            10,              ...
                                        'Units',               'pixels',        ...
                                        'Style',               'text',          ...
                                        'String',              SD.IGMATFilename ...
                                        );
    this.ImportFromMATEdit = uicontrol(this.HDialog,                    ...
                                       'BackgroundColor',     [1 1 1],  ...
                                       'HorizontalAlignment', 'left',   ...                                       
                                       'FontSize',            10,       ...
                                       'Units',               'pixels', ...
                                       'Style',               'edit'    ...
                                       );
    LoadButtonIcon = Simulink.sdi.GUIUtil.CreateMATLABIconPath('file_open.png');
    [this.ImportFromMATButton,            ...
        this.ImportFromMATButtonContainer] = ...
        Simulink.sdi.GUIUtil.CreateButton(this.HDialog, '', LoadButtonIcon);
    
    % "Import To" section
    this.ImportToLabel = uicontrol(this.HDialog,                        ...
                                   'HorizontalAlignment', 'left',       ...                                   
                                   'FontSize',            10,           ...
                                   'FontWeight',          'bold',       ...
                                   'Units',               'pixels',     ...
                                   'Style',               'text',       ...
                                   'String',              SD.IGImportTo ...
                                   );
    this.ImportToNewRadio = uicontrol(this.HDialog,                         ...
                                      'HorizontalAlignment', 'left',        ...                                      
                                      'FontSize',            10,            ...
                                      'Units',               'pixels',      ...
                                      'Style',               'radioButton', ...
                                      'String',              SD.IGNewRun    ...
                                     );
    this.ImportToExistRadio = uicontrol(this.HDialog,                         ...
                                        'HorizontalAlignment', 'left',        ...                                        
                                        'FontSize',            10,            ...
                                        'Units',               'pixels',      ...
                                        'Style',               'radioButton', ...
                                        'String',              SD.IGExistRun  ...
                                       );
    this.ImportToExistLabel = uicontrol(this.HDialog,                       ...
                                        'HorizontalAlignment', 'left',      ...                                        
                                        'FontSize',            10,          ...
                                        'Units',               'pixels',    ...
                                        'Style',               'text',      ...
                                        'String',              SD.IGRunName ...
                                        );
    this.ImportToExistCombo = uicontrol(this.HDialog,                       ...
                                        'BackgroundColor',     [1 1 1],     ...
                                        'HorizontalAlignment', 'left',      ...                                        
                                        'FontSize',            10,          ...
                                        'Units',               'pixels',    ...
                                        'Style',               'popupmenu', ...
                                        'String',              {'default'}  ...
                                        );
    
    % "Import variables" section - Table
    this.ImportVarsTT = javaObjectEDT('com.mathworks.toolbox.sdi.sdi.CustomTreeTable',...
                                       int32(1));
    this.ImportVarsTTScrollPane = javaObjectEDT('javax.swing.JScrollPane');
    this.ImportVarsTTScrollPane.getViewport.setView(this.ImportVarsTT);
    [this.ImportVarsTTComponent, this.ImportVarsTTContainer] = ...
        javacomponent(this.ImportVarsTTScrollPane, [0 0 1 1], this.HDialog);
    rowList = javaObjectEDT('java.util.ArrayList');
    rowList.add(int32(8));
    this.ImportVarsTTModel =                                                ...
        javaObjectEDT('com.mathworks.toolbox.sdi.sdi.CustomTreeTableModel', ...
                      rowList, 9, this.colNameArrayList);
    this.ImportVarsTT.setModel(this.ImportVarsTTModel);
    this.ImportVarsTT.setClickCountToStart(1);
    this.ImportVarsTT.setRowHeight(25);
    this.ImportVarsTT.setShowSortOrderNumber(false);
    this.ImportVarsTT.setShowTreeLines(false);
    set(this.ImportVarsTTContainer, 'Units', 'pixels');
    this.ImportVarsTTScrollPane.getViewport.setBackground(java.awt.Color.white);
    this.ImportVarsCheckboxCellRenderer = javaObjectEDT('com.jidesoft.grid.BooleanCheckBoxCellRenderer');
    this.ImportVarsCheckboxCellEditor   = javaObjectEDT('com.jidesoft.grid.BooleanCheckBoxCellEditor');
    hCheckBoxCellEditor = handle(this.ImportVarsCheckboxCellEditor ,...
                                 'callbackproperties');
    hCheckBoxCellEditor.EditingStoppedCallback = {@this.callback_multiselectCheckBox};
    this.ImportVarsCheckboxCellEditor.setClickCountToStart(0);
    
    % Set cell editor for import column
    ColumnModel       = this.ImportVarsTT.getColumnModel();
    ImportColumnIndex = ColumnModel.getColumnIndex(SD.IGImportColName);
    ImportColumn      = ColumnModel.getColumn(ImportColumnIndex);
    ImportColumn.setCellRenderer(this.ImportVarsCheckboxCellRenderer);
    ImportColumn.setCellEditor(this.ImportVarsCheckboxCellEditor);
    
    % "Import variables" section - Buttons - Icons
    RefreshButtonIcon = Simulink.sdi.GUIUtil.CreateSDIIconPath('browser_refresh.png');
    
    % "Import variables" section - Buttons - Refresh
    [this.RefreshButton,                                             ...
     this.RefreshButtonContainer] =                                  ...
                                    Simulink.sdi.GUIUtil.CreateButton...
                                    (this.HDialog, SD.Refresh,       ...
                                     RefreshButtonIcon);
    
    % "Import variables" section - Buttons - Select All
    [this.SelectAllButton,            ...
     this.SelectAllButtonContainer] = ...
        Simulink.sdi.GUIUtil.CreateButton(this.HDialog, SD.SelectAll, []);
    
    % "Import variables" section - Buttons - Clear All
    [this.ClearAllButton,            ...
     this.ClearAllButtonContainer] = ...
        Simulink.sdi.GUIUtil.CreateButton(this.HDialog, SD.ClearAll, []);
    
    % "Import variables" section - Context menu
    this.ContextMenu            = uicontextmenu('parent', this.HDialog);
    this.ContextMenuRootSource  = uimenu(this.ContextMenu, 'label', SD.IGRootSourceColName);
    this.ContextMenuTimeSource  = uimenu(this.ContextMenu, 'label', SD.IGTimeSourceColName);
    this.ContextMenuDataSource  = uimenu(this.ContextMenu, 'label', SD.IGDataSourceColName);
    this.ContextMenuBlockSource = uimenu(this.ContextMenu, 'label', SD.IGBlockSourceColName);
    this.ContextMenuModelSource = uimenu(this.ContextMenu, 'label', SD.IGModelSourceColName);
    this.ContextMenuSignalLabel = uimenu(this.ContextMenu, 'label', SD.mgSigLabel);
    this.ContextMenuSignalDims  = uimenu(this.ContextMenu, 'label', SD.IGSignalDimsColName);
    this.ContextMenuPortIndex   = uimenu(this.ContextMenu, 'label', SD.IGPortIndexColName);
end