function [c,t] = uitoolfactory(p,id)
% This function is undocumented and will change in a future release

%UITOOLFACTORY Creates built-in toolbar components
%   uitoolfactory 
%       With no arguments, displays registered toolbar 
%       components to the command window.
%
%   [C] = uitoolfactory(H,'GroupName.ComponentName') 
%       H is the parent toolbar handle. 
%       'GroupName' is the name of the toolbar group
%       'ComponentName' is the name of the toolbar component
%       C is the toolbar component
%
%   [C] = uitoolfactory(H,'GroupName')
%       Specifying a 'GroupName' without a 'ComponentName' will create
%       all the components, C, registered in that group.
%
%   NOTE:
%       C will return empty if the component is no longer supported as a
%       built-in component.
%
%   [INFO] = uitoolfactory(H,'getinfo')
%       Returns a struct containing information on all registered tools.
%
%   Example: 
%       % Create a figure with a simple toolbar
%       FIG = figure('toolbar','none');
%       H = uitoolbar('parent',FIG);
%       C = uitoolfactory(H,'Standard.EditPlot'); 
%       C = uitoolfactory(H,'Exploration.ZoomIn'); 
%       set(C,'Separator','on');
%       C = uitoolfactory(H,'Exploration.ZoomOut');
%       C = uitoolfactory(H,'Exploration.Pan');
%
%   See also UIGETTOOL.

%   Copyright 1984-2010 The MathWorks, Inc.
%   $Revision: 1.1.6.24 $ $Date: 2010/05/20 02:30:10 $


if nargin==0
    % Pretty print output
    info = localGetToolbarComponentInfo;
    localPrettyPrint(info); 
    
% info = uitoolfactory('getinfo')    
elseif nargin==1 && nargout==1
    info = localGetToolbarComponentInfo;    
    % Convert cell of structs to structure
    for n = 1:length(info)
       c(n) = info{n};
    end    

elseif nargin==2 
    c = localMainCreate(p,id);
end

%---------------------------------------------------%
function [hComponent] = localMainCreate(p,fullid)
% Creates one or more uitoolbar components

hComponent = [];

% Get group and name from full ID
[idgroup,idname] = strtok(fullid,'.');
if ~isempty(idname)
    idname = idname(2:end);
end
    
% p must be a toolbar
if strcmpi(get(p,'Type'),'uitoolbar')
    hToolbar = p;
else
    error('uitools:uitoolfactory:InvalidHandle', 'Handle must be a toolbar');
end

% Get full listing of registered components
dat = localGetToolbarComponentInfo;

% No name specified, so load group of toolbar components
if isempty(idname)
    
    % Cycle through each item and add appropriately
    for n = 1:length(dat);
        info = dat{n};
        if strcmp(info.group,idgroup)
             hComponent(end+1) = localCreateToolbarComponent(hToolbar,info);    
        end
    end
    
% Load individual toolbar components
else
    % Cycle through each item 
    for n = 1:length(dat);
        info = dat{n};
        if strcmp(info.group,idgroup) && strcmp(info.name,idname);
             hComponent = localCreateToolbarComponent(hToolbar,info);
             break;
        end
    end    
end

%---------------------------------------------------%
function [h] = localCreateToolbarComponent(p,info)
% Creates individual components (i.e. uitoggletool)

%mlroot = 'S:/A/matlab'; % for sandbox testing
mlroot = matlabroot;

ICONROOT = [mlroot, '/toolbox/matlab/icons/'];
props = info.properties;

% Create tag based on group & name. It is better to keep this tag unique as
% we do know. It is used to improve the performance of creating the icon
% from CData in Java Figures. It is used as the key to search for a match
% in a table with Java icons created for component generated by this
% uitoolfactory. 
props.tag = [info.group,'.',info.name];

% Load cdata from *.gif file
filename = info.icon;
if length(filename)>3 && strncmp(filename(end-3:end),'.gif',4)
    [cdata,map] = imread([ICONROOT,info.icon]);
    % Set all white (1,1,1) colors to be transparent (nan)
    ind = find(map(:,1)+map(:,2)+map(:,3)==3);
    map(ind) = NaN;
    props.cdata = ind2rgb(cdata,map);

% Load cdata from *.png file
elseif length(filename)>3 && strncmp(filename(end-3:end),'.png',4)
    [cdata map alpha] = imread([ICONROOT,info.icon],'Background','none');
    % Converting 16-bit integer colors to MATLAB colorspec
    cdata = double(cdata) / 65535.0;
    % Set all transparent pixels to be transparent (nan)
    cdata(alpha==0) = NaN;
    props.cdata = cdata;

% Load cdata from *.mat file
else
    dat = load([ICONROOT,info.icon],'cdata');
    props.cdata = dat.cdata;
end

% Specify PARENT property
props.parent = p;

% Create toolbar component
h = feval(info.constructor,props);

% Properties common to all uitool components
set(h,'HandleVisibility','off','Serializable','off');

%---------------------------------------------------%
function localPrettyPrint(uidata)
% Pretty prints toolbar data to command window
% in a similar manner as the PATH command.

% Header
disp(sprintf('\n\t\tTOOLBAR ITEMS\n'))     

info = {};
for n = 1:length(uidata)
    info{n} = [uidata{n}.group,'.',uidata{n}.name];
end

% Display items
ch= strvcat(info);
tabspace = ones(size(ch,1),1);
tabspace(:) = sprintf('\t');
s = [tabspace, ch];
disp(s)

% Footer
disp(sprintf('\n'))

%---------------------------------------------------%
function [uidata] = localGetToolbarComponentInfo
% Loads all toolbar data

uidata = {};

% STANDARD TOOLS ------------------------------------------%
% New Figure
info = [];
info.name = 'NewFigure';
info.group = 'Standard';
info.constructor = 'uipushtool';
info.properties.ClickedCallback = 'filemenufcn(gcbf,''FileNew'')'; 
info.properties.ToolTipString = 'New Figure';
info.icon = 'file_new.png';
info.label = 'New';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Open File
info = [];
info.name = 'FileOpen';
info.group = 'Standard';
info.constructor = 'uipushtool';
info.properties.ClickedCallback = 'filemenufcn(gcbf,''FileOpen'')'; 
info.properties.ToolTip = 'Open File';
info.properties.BusyAction = 'cancel';
info.properties.Interruptible = 'off';
info.icon = 'file_open.png';
info.label = 'Open';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Save Figure
info = [];
info.name = 'SaveFigure';
info.group = 'Standard';
info.constructor = 'uipushtool';
info.properties.ClickedCallback = 'filemenufcn(gcbf,''FileSave'')'; 
info.properties.ToolTip = 'Save Figure';
info.properties.BusyAction = 'cancel';
info.properties.Interruptible = 'off';
info.icon = 'file_save.png';
info.label = 'Save';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Print
info = [];
info.name = 'PrintFigure';
info.group = 'Standard';
info.constructor = 'uipushtool';
info.properties.ClickedCallback = 'printdlg(gcbf)'; 
info.properties.ToolTip = 'Print Figure';
info.properties.BusyAction = 'cancel';
info.properties.Interruptible = 'off';
info.icon = 'file_print.png';
info.label = 'Print';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Plot Edit
info = [];
info.name = 'EditPlot';
info.group = 'Standard';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'plotedit(gcbf,''toggle'')';
info.properties.ToolTip =  'Edit Plot';
info.icon = 'pointer';
info.label = 'Edit Plot';
info.readyForGUIDE = false;
uidata{end+1} = info;

% EXPLORE TOOLS ------------------------------------------%

% Zoom In
info = [];
info.name = 'ZoomIn';
info.group = 'Exploration';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'putdowntext(''zoomin'',gcbo)';
%info.properties.ClickedCallback = 'zoom inmode';
info.properties.ToolTip = 'Zoom In';
info.icon = 'tool_zoom_in.png';
info.label = 'Zoom In';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Zoom Out
info = [];
info.name = 'ZoomOut';
info.group = 'Exploration';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'putdowntext(''zoomout'',gcbo)';
%info.properties.ClickedCallback = 'zoom outmode';
info.properties.ToolTip = 'Zoom Out';
info.icon = 'tool_zoom_out.png';
info.label = 'Zoom Out';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Zoom X
info = [];
info.name = 'ZoomX';
info.group = 'Exploration';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'putdowntext(''zoomx'',gcbo)';
info.properties.ToolTip = 'Zoom X-Axis';
info.icon = 'zoomx.mat';
info.label = 'Zoom X-Axis';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Zoom Y
info = [];
info.name = 'ZoomY';
info.group = 'Exploration';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'putdowntext(''zoomy'',gcbo)';
info.properties.ToolTip = 'Zoom Y-Axis';
info.icon = 'zoomy.mat';
info.label = 'Zoom X-Axis';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Pan
info = [];
info.name = 'Pan';
info.group = 'Exploration';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'putdowntext(''pan'',gcbo)';
%info.properties.ClickedCallback = 'pan on';
info.properties.ToolTip = 'Pan';
info.icon = 'tool_hand.png';
info.label = 'Pan';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Rotate
info = [];
info.name = 'Rotate';
info.group = 'Exploration';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'putdowntext(''rotate3d'',gcbo)';
%info.properties.ClickedCallback = 'rotate3d on';
info.properties.ToolTip = 'Rotate 3D';
info.icon = 'tool_rotate_3d.png';
info.label = 'Rotate';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Data Cursor
info = [];
info.name = 'DataCursor';    
info.group = 'Exploration';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'putdowntext(''datatip'',gcbo)';
info.properties.ToolTip = 'Data Cursor';
info.icon = 'tool_data_cursor.png';
info.label = 'Data Cursor';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Brush
info = [];
info.name = 'Brushing';    
info.group = 'Exploration';
info.constructor = 'uitogglesplittool';
info.properties.ToolTip = 'Brush/Select Data';
info.properties.Callback = @datamanager.brushHGCallback;
info.properties.ClickedCallback = 'putdowntext(''brush'',gcbo)';
info.properties.createFcn = @datamanager.createBrushToolBtn;
info.icon = 'tool_data_brush.png';
info.label = 'Brush Data';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Linked plots
info = [];
info.name = 'Linking';    
info.group = 'DataManager';
info.constructor = 'uitoggletool';
info.properties.oncallback = 'datamanager.linkbtnoncallback(''on'')';
info.properties.offcallback = 'linkdata(gcbf,''off'')';
info.properties.interruptible = 'off';
info.properties.busyAction = 'queue';
info.properties.ToolTip = 'Link Plot';
info.icon = 'tool_plot_linked.png';
info.label = 'Link Plot';
info.readyForGUIDE = false;
uidata{end+1} = info;

% ANNOTATION TOOLS ------------------------------------------%

% Colorbar
info = [];
info.name = 'InsertColorbar';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'insertmenufcn(gcbf,''Colorbar'')';
info.properties.ToolTip = 'Insert Colorbar';
info.icon = 'tool_colorbar.png';
info.label = 'Colorbar';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Legend
info = [];
info.name = 'InsertLegend';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.ClickedCallback = 'insertmenufcn(gcbf,''Legend'')';
info.properties.ToolTip = 'Insert Legend';
info.icon = 'tool_legend.png';
info.label = 'Legend';
info.readyForGUIDE = true;
uidata{end+1} = info;

% Rectangle
info = [];
info.name = 'InsertRectangle';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.OnCallback = 'startscribeobject(''Rectangle'', gcbf)';
info.properties.OffCallback = 'startscribeobject(''None'', gcbf)';
info.properties.ToolTip = 'Insert Rectangle';
info.icon = 'tool_shape_rectangle.png';
info.label = 'Rectangle';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Ellipse
info = [];
info.name = 'InsertEllipse';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.OnCallback = 'startscribeobject(''Ellipse'', gcbf)';
info.properties.OffCallback = 'startscribeobject(''None'', gcbf)';
info.properties.ToolTip = 'Insert Ellipse';
info.icon = 'tool_shape_ellipse.png';
info.label = 'Ellipse';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Textbox
info = [];
info.name = 'InsertTextbox';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.OnCallback = 'startscribeobject(''Textbox'', gcbf)';
info.properties.OffCallback = 'startscribeobject(''None'', gcbf)';
info.properties.ToolTip = 'Insert Textbox';
info.icon = 'tool_text_textbox.png';
info.label = 'Textbox';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Text Arrow
info = [];
info.name = 'InsertTextArrow';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.OnCallback = 'startscribeobject(''TextArrow'', gcbf)';
info.properties.OffCallback = 'startscribeobject(''None'', gcbf)';
info.properties.ToolTip = 'Insert Text Arrow';
info.icon = 'tool_text_arrow.png';
info.label = 'Text Arrow';
info.readyForGUIDE = false;
uidata{end+1} = info;

% 2 Headed Arrow
info = [];
info.name = 'InsertDoubleArrow';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.OnCallback = 'startscribeobject(''DoubleArrow'', gcbf)';
info.properties.OffCallback = 'startscribeobject(''None'', gcbf)';
info.properties.ToolTip = 'Insert Double Arrow';
info.icon = 'tool_arrow_dbl.png';
info.label = 'Double Arrow';
info.readyForGUIDE = false;
uidata{end+1} = info;

% 1 Headed Arrow
info = [];
info.name = 'InsertArrow';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.OnCallback = 'startscribeobject(''Arrow'', gcbf)';
info.properties.OffCallback = 'startscribeobject(''None'', gcbf)';
info.properties.ToolTip = 'Insert Arrow';
info.icon = 'tool_arrow.png';
info.label = 'Arrow';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Line
info = [];
info.name = 'InsertLine';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.OnCallback = 'startscribeobject(''Line'', gcbf)';
info.properties.OffCallback = 'startscribeobject(''None'', gcbf)';
info.properties.ToolTip = 'Insert Line';
info.icon = 'tool_line.png';
info.label = 'Line';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Pin
info = [];
info.name = 'Pin';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.OnCallback = 'startscribepinning(gcbf)';
info.properties.OffCallback = 'startscribepinning(gcbf,''off'')';
info.properties.ToolTip = 'Pin to axes';
info.icon = 'tool_pushpin.png';
info.label = 'Pin';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Align Distribute
info = [];
info.name = 'AlignDistribute';
info.group = 'Annotation';
info.constructor = 'uitoggletool';
info.properties.OnCallback = 'scribealign(gcbf)';
info.properties.ToolTip =  'Align/Distribute';
info.icon = 'tool_align_center.png';
info.label = 'Alignment';
info.readyForGUIDE = false;
uidata{end+1} = info;


% PLOTTOOL-RELATED TOOLS ------------------------------------------%

% Plottools Off
info = [];
info.name = 'PlottoolsOff';
info.group = 'Plottools';
info.constructor = 'uipushtool';
info.properties.ClickedCallback = 'plottools (gcbf, ''hide'');';
info.properties.ToolTip = 'Hide Plot Tools';
info.properties.Enable = 'off';
info.properties.RequireJavaFigures = 'on';
info.icon = 'tool_plottools_hide.png';
info.label = 'Hide Plot Tools';
info.readyForGUIDE = false;
uidata{end+1} = info;

% Plottools On
info = [];
info.name = 'PlottoolsOn';
info.group = 'Plottools';
info.constructor = 'uipushtool';
info.properties.ClickedCallback = 'plottools (gcbf, ''show'');'; 
info.properties.ToolTip = 'Show Plot Tools and Dock Figure';
info.properties.Enable = 'on';
info.properties.RequireJavaFigures = 'on';
info.icon = 'tool_plottools_show.png';
info.label = 'Show Plot Tools';
info.readyForGUIDE = false;
uidata{end+1} = info;
