function setup_figure(hSOS)
%SETUP_FIGURE

%   Author(s): J. Schickler
%   Copyright 1988-2002 The MathWorks, Inc.
%   $Revision: 1.7 $  $Date: 2002/04/14 23:33:43 $ 

cbs = dialog_cbs(hSOS);
sz  = gui_sizes(hSOS);

hFig = figure('Position', [400 400 205 115]*sz.pixf, ...
    'NumberTitle', 'Off', ...
    'IntegerHandle', 'Off', ...
    'Name', 'Convert to SOS', ...
    'Color', get(0,'defaultuicontrolbackgroundcolor'), ...
    'CloseRequestFcn', cbs.cancel, ...
    'Menubar', 'None', ...
    'Resize', 'Off', ...
    'HandleVisibility','Callback', ...
    'Visible', hSOS.Visible);

set(hSOS, 'FigureHandle', hFig);

% [EOF]
