function errorIds = errorIdsForStrictBusMsg
    errorIds = {'Simulink:blocks:BusSelectorUnconnected',...
                'Simulink:Bus:SigHierPropBusSelOutputDoesNotMatchInput',...
                'Simulink:blocks:DemuxSplittingInBusMode',...
                'Simulink:Engine:CannotPropFrameDataForward'};
end
%   Copyright 2010 The MathWorks, Inc.
