function [ssInBlkHs, ssOutBlkHs, ssTriggerBlkHs] = getSubSystemPortBlks(subsysH)
%   Return two vectors containing subsystem Inport and Outport blocks.

%   Copyright 2008-2009 The MathWorks, Inc.

    ssInBlkHs = find_system(subsysH, ...
                            'SearchDepth',1,...
                            'FollowLinks','on',...  
                            'LookUnderMasks','all', ...
                            'BlockType','Inport');

    ssOutBlkHs = find_system(subsysH, ...
                             'SearchDepth',1,...
                             'FollowLinks','on',...  
                             'LookUnderMasks','all', ...
                             'BlockType','Outport');
                         
    ssTriggerBlkHs = find_system(subsysH, ...
                             'SearchDepth',1,...
                             'FollowLinks','on',...  
                             'LookUnderMasks','all', ...
                             'BlockType','TriggerPort');                            
end