function b = setGUI(this, Hd)
%SETGUI   Set the GUI

%   Author(s): J. Schickler
%   Copyright 2006-2010 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2010/05/20 03:03:27 $

b = true;
hfdesign = getfdesign(Hd);
switch lower(get(hfdesign, 'Response'))
    case 'peaking filter'
        set(this, 'ResponseType', 'peak')
    case 'notching filter',
        set(this, 'ResponseType', 'notch')
    otherwise
        b = false;
        return;
end

switch hfdesign.Specification
    case 'N,F0,Q'
        set(this, ...
            'FrequencyConstraints', 'Center frequency and quality factor', ...
            'MagnitudeConstraints', 'Unconstrained', ...
            'F0', num2str(hfdesign.F0), ...
            'Q',  num2str(hfdesign.Q));
    case 'N,F0,Q,Ap'
        set(this, ...
            'FrequencyConstraints', 'Center frequency and quality factor', ...
            'MagnitudeConstraints', 'Passband ripple', ...
            'F0',    num2str(hfdesign.F0), ...
            'Q',     num2str(hfdesign.Q), ...
            'Apass', num2str(hfdesign.Apass));
    case 'N,F0,Q,Ast'
        set(this, ...
            'FrequencyConstraints', 'Center frequency and quality factor', ...
            'MagnitudeConstraints', 'Stopband attenuation', ...
            'F0',    num2str(hfdesign.F0), ...
            'Q',     num2str(hfdesign.Q), ...
            'Astop', num2str(hfdesign.Astop));
    case 'N,F0,Q,Ap,Ast'
        set(this, ...
            'FrequencyConstraints', 'Center frequency and quality factor', ...
            'MagnitudeConstraints', 'Passband ripple and stopband attenuation', ...
            'F0',    num2str(hfdesign.F0), ...
            'Q',     num2str(hfdesign.Q), ...
            'Apass', num2str(hfdesign.Apass), ...
            'Astop', num2str(hfdesign.Astop));
    case 'N,F0,BW'
        set(this, ...
            'FrequencyConstraints', 'Center frequency and bandwidth', ...
            'MagnitudeConstraints', 'Unconstrained', ...
            'F0', num2str(hfdesign.F0), ...
            'BW', num2str(hfdesign.BW));
    case 'N,F0,BW,Ap'
        set(this, ...
            'FrequencyConstraints', 'Center frequency and bandwidth', ...
            'MagnitudeConstraints', 'Passband ripple', ...
            'F0',    num2str(hfdesign.F0), ...
            'BW',    num2str(hfdesign.BW), ...
            'Apass', num2str(hfdesign.Apass));
    case 'N,F0,BW,Ast'
        set(this, ...
            'FrequencyConstraints', 'Center frequency and bandwidth', ...
            'MagnitudeConstraints', 'Stopband attenuation', ...
            'F0',    num2str(hfdesign.F0), ...
            'BW',    num2str(hfdesign.BW), ...
            'Astop', num2str(hfdesign.Astop));
    case 'N,F0,BW,Ap,Ast'
        set(this, ...
            'FrequencyConstraints', 'Center frequency and bandwidth', ...
            'MagnitudeConstraints', 'Passband ripple and stopband attenuation', ...
            'F0',    num2str(hfdesign.F0), ...
            'BW',    num2str(hfdesign.BW), ...
            'Apass', num2str(hfdesign.Apass), ...
            'Astop', num2str(hfdesign.Astop));
    otherwise
        error(generatemsgid('IncompleteConstraints'), ...
            'Internal Error: Lowpass ''%s'' incomplete', hfdesign.Specification);
end

abstract_setGUI(this, Hd);

% [EOF]
