function examples = getexamples(this)
%GETEXAMPLES   Get the examples.

%   Author(s): V. Pellissier
%   Copyright 2005 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2005/08/20 13:28:42 $

examples = {{ ...
    'Design a multi-band filter for noise shaping.', ...
    '% (Useful simulations of a Rayleigh fading wireless communications channel.)', ...
    'N = 90;', ...
    'NBands = 2;', ...
    'F1 = 0:0.01:0.4; F2 = [.45 1];', ...
    'A1 = 1.0 ./ (1 - (F1./0.42).^2).^0.25; A2 = [0 0];', ...
    'd = fdesign.arbmag(''N,B,F,A'',N,NBands,F1,A1,F2,A2);', ...
    'Hd = design(d,''firls'');', ...
    'fvtool(Hd)'}};

% [EOF]
