
function maskNames = getDVSupportedMaskTypes
    maskNames =    {'Design Verifier Test Objective'...
 %                   ,'Design Verifier Proof Objective',...
 %                   ,'Design Verifier Test Condition',...
 %                   ,'Design Verifier Assumption' ...
 };

