function blktypes = getSupportedBlockTypes


%   Copyright 1990-2006 The MathWorks, Inc.


    persistent CoverageBlockTypes;

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Load CoverageBlockTypes if needed
    if isempty(CoverageBlockTypes)
         CoverageBlockTypes = create_CoverageBlockTypes;
    end

    blktypes = CoverageBlockTypes;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CREATE_COVERAGEBLOCKTYPES
%
% Set the value of persistent string cell array CoverageBlockTypes

function CoverageBlockTypes = create_CoverageBlockTypes()

    % This list has a direct impact on the block order within the
    % model hierarchy.  Keep the list alphabetic to montain a degree
    % of consistency

    CoverageBlockTypes = { ...
                            'Abs', ...
                            'CombinatorialLogic', ...
                            'DiscreteIntegrator', ...
                            'DeadZone', ...
                            'Fcn',...
                            'ForIterator', ...
                            'If', ...
                            'Interpolation_n-D', ...
                            'Logic', ...
                            'Lookup', ...
                            'Lookup2D', ...
                            'Lookup_n-D',...
                            'MinMax', ...
                            'MultiPortSwitch', ...
                            'RateLimiter', ...
                            'Relay', ...
                            'Saturate', ...
                            'Switch', ...
                            'SwitchCase', ...
                            'WhileIterator'
                         };    

