function SavedData = save(Editor)
% Creates backup of Bode Editor settings.

%   Author(s): P. Gahinet
%   Copyright 1986-2006 The MathWorks, Inc.
%   $Revision: 1.6.4.4 $  $Date: 2006/06/20 20:02:37 $

Axes = Editor.Axes;
PlotAxes = getaxes(Axes);
if ~isempty(Editor.GainTargetBlock)
    GainTargetBlock = find(Editor.GainTargetBlock==Editor.LoopData.C);
else
    GainTargetBlock = [];
end

SavedData = struct(...
    'Class',class(Editor),...
    'EditedBlock',find(Editor.EditedBlock==Editor.LoopData.C),...
    'GainTargetBlock',  GainTargetBlock,...
    'EditedLoop', Editor.EditedLoop,...
    'Constraints',Editor.saveconstr,...
    'Grid',Axes.Grid,...
    'Title',Axes.Title,...
    'TitleStyle',struct(Axes.TitleStyle),...
    'Visible',Editor.Visible,...
    'XlabelStyle',struct(Axes.XlabelStyle),...
    'Xlabel',{Axes.Xlabel},...
    'Xlim',{get(PlotAxes(1),'Xlim')},...
    'XlimMode',{Axes.XlimMode},...
    'Ylabel',{Axes.Ylabel},...
    'YlabelStyle',struct(Axes.YlabelStyle),...
    'Ylim',{get(PlotAxes,'Ylim')},...
    'YlimMode',{Axes.YlimMode},...
    'MagVisible',Editor.MagVisible,...
    'MarginVisible',Editor.MarginVisible,...
    'PhaseVisible',Editor.PhaseVisible);
