function abstractnyquist_setGUI(this, Hd)
%ABSTRACTNYQUIST_SETGUI   

%   Author(s): J. Schickler
%   Copyright 2006-2010 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2010/05/20 03:03:10 $

hfdesign = getfdesign(Hd);
switch lower(hfdesign.Specification)
    case 'tw,ast'
        set(this, ...
            'TransitionWidth', num2str(hfdesign.TransitionWidth), ...
            'Astop', num2str(hfdesign.Astop));
    case 'n'
        set(this, ...
            'privFrequencyConstraints', 'unconstrained', ...
            'privMagnitudeConstraints', 'unconstrained');
    case 'n,tw'
        set(this, ...
            'privFrequencyConstraints', 'transition width', ...
            'privMagnitudeConstraints', 'unconstrained', ...
            'TransitionWidth', num2str(hfdesign.TransitionWidth));
    case 'n,ast'
        set(this, ...
            'privFrequencyConstraints', 'unconstrained', ...
            'privMagnitudeConstraints', 'Stopband attenuation', ...
            'Astop', num2str(hfdesign.Astop));
    otherwise
        error(generatemsgid('IncompleteConstraints'), ...
            'Internal Error: Nyquist ''%s'' incomplete', hfdesign.Specification);
end

abstract_setGUI(this, Hd);

% [EOF]
