function getPlotOpts(this,h)
% GETPLOTOPTS Gets plot options of @plot h

%  Author(s): C. Buhr
%  Copyright 1986-2005 The MathWorks, Inc.
%  $Revision: 1.1.8.1 $ $Date: 2009/10/16 06:17:51 $

% Get Title info
TitleStyle = h.AxesGrid.TitleStyle;
this.Title = struct('String',     h.AxesGrid.Title, ...
                 'FontSize',   TitleStyle.FontSize, ...
                 'FontWeight', TitleStyle.FontWeight, ...
                 'FontAngle',  TitleStyle.FontAngle, ...
                 'Color',      TitleStyle.Color);
     
% Get Xlabel info
XLabelStyle = h.AxesGrid.XLabelStyle;
this.XLabel = struct('String',     h.AxesGrid.XLabel, ...
                  'FontSize',   XLabelStyle.FontSize, ...
                  'FontWeight', XLabelStyle.FontWeight, ...
                  'FontAngle',  XLabelStyle.FontAngle, ...
                  'Color',      XLabelStyle.Color);

% Get Ylabel info
YLabelStyle = h.AxesGrid.YLabelStyle;
this.YLabel = struct('String',     {h.AxesGrid.YLabel}, ...
                  'FontSize',   YLabelStyle.FontSize, ...
                  'FontWeight', YLabelStyle.FontWeight, ...
                  'FontAngle',  YLabelStyle.FontAngle, ...
                  'Color',      YLabelStyle.Color);

% Get Tick Label info
TickLabelStyle = h.AxesGrid.AxesStyle;
this.TickLabel = struct('FontSize',   TickLabelStyle.FontSize, ...
                     'FontWeight', TickLabelStyle.FontWeight, ...
                     'FontAngle',  TickLabelStyle.FontAngle, ...
                     'Color',     TickLabelStyle.XColor);                  

% Get Grid info
this.Grid = h.AxesGrid.Grid;

% Get Lim and Limmode info
ax = h.AxesGrid.getaxes('2d');  
this.XLim = get(ax(1,:),{'Xlim'});     
this.XLimMode = h.AxesGrid.XLimMode;

this.YLim = get(ax(:,1),{'Ylim'});
this.YLimMode = h.AxesGrid.YLimMode;