function pInitialiseLocation(task, proxy, taskFcn, numArgsOut, argsIn)
; %#ok Undocumented
%pInitialiseLocation 
%
%  pInitialiseLocation(TASK)

% Copyright 2005-2008 The MathWorks, Inc.


% Fill in the relevant parts of the Job object
serializer = task.Serializer;

fieldsToInit = { ...
    'name' ...
    'taskfunction' ...
    'nargout' ...
    'argsin' ...
    'argsout' ...
    'capturecommandwindowoutput' ...
    'commandwindowoutput' ...
    'state' ...
    'errorstruct' ...
    'errormessage' ...
    'erroridentifier' ...
    'createtime' ...
    'starttime' ...
    'finishtime' ...
    };


valuesToInit = { ...
    char(proxy.getName) ...
    taskFcn ...
    numArgsOut ...
    argsIn ...
    cell(1, 0) ...
    false ...
    '' ...
    'pending' ....
    MException('', '') ...
    '' ...
    '' ...
    char(java.util.Date) ...
    '' ...
    '' ...
    };

% Request that the serializer create a the fields for a 'job' entity 
serializer.createFields(task, fieldsToInit, valuesToInit);
