function pPostTaskEvaluate(task, output, m_exception, cmd_window_output)        
; %#ok Undocumented
%pPostTaskEvaluate 
%
%  pPostTaskEvaluate(TASK, OUTPUT, ERR_MSG, ERR_ID, CMD_WINDOW_OUTPUT)

%  Copyright 2005-2008 The MathWorks, Inc.

%  $Revision: 1.1.10.6 $    $Date: 2008/06/24 17:00:55 $ 

try
    set(task, ...
        'OutputArguments', output, ...
        'Error', m_exception, ...
        'ErrorMessage', m_exception.message, ...
        'ErrorIdentifier', m_exception.identifier, ...
        'CommandWindowOutput', cmd_window_output, ...
        'State', 'finished', ...
        'FinishTime', char(java.util.Date));
catch err
    % Try and write an appropriate error message if possible
    if ishandle(task)
        try
            set(task, ...
                'Error', err,...
                'ErrorMessage', err.message, ...
                'ErrorIdentifier', err.identifier);
        catch e  %#ok<NASGU>
        end
    end
end
