function disp(this)
%DISP     Display this object

%   Copyright 2007-2008 The MathWorks, Inc.
%   $Revision: 1.1.6.3 $  $Date: 2008/06/13 15:11:50 $

% Define the fields to be displayed in order
fieldNames = {'Type', ...
    'Parent', ...
    'Position', ...
    'Items', ...
    'SelectedItemIndices', ...
    'AvailableListX', ...
    'SelectedListX', ...
    'RenderMoveUpDown', ...
    'RenderQuickHelp', ...
    'QuickHelp', ...
    'QuickHelpHeight'};

excludedFieldNames = {};
if this.RenderQuickHelp == 0
    % If RenderQuickHelp is 0
    excludedFieldNames = [excludedFieldNames 'QuickHelp'];
end

baseDisp(this, fieldNames, excludedFieldNames);

%-------------------------------------------------------------------------------
% [EOF]
