function nlsys = setext(nlsys, varargin)
%SETEXT  Set properties (including level 1 algorithm ones) of IDNLGREY
%   models. PRIVATE FUNCTION.
%
%   NLSYS = SETEXT(NLSYS, 'PROPERTY', VALUE) sets the property 'PROPERTY'
%   of the IDNLGREY object NLSYS to VALUE.
%
%   NLSYS = SETEXT(NLSYS, 'PROPERTY1', VALUE1, 'PROPERTY2', VALUE2, ...)
%   sets multiple property values of NLSYS in one single operation.
%
%   For more information on IDNLGREY properties, type IDPROPS IDNLGREY.
%
%   See also IDNLMODEL/SET, IDNLGREY/IDNLGREY and IDNLGREY/PEM.

%   Copyright 2005-2008 The MathWorks, Inc.
%   $Revision: 1.1.8.6 $ $Date: 2008/10/02 18:54:08 $

% Check that the function was called with at least three arguments.
nin = nargin;
error(nargchk(3, Inf, nin, 'struct'));

% Check that the function was called with an odd number of arguments.
if (rem(nin, 2) ~= 1)
    ctrlMsgUtils.error('Ident:general:InvalidSyntax','setext','setext')
end

% Get public properties and add all level 1 algorithm properties.
AllProps = pnames(nlsys);
AlgProps = fieldnames(idnlgreydef('Algorithm'));
AllProps = {AllProps{:} AlgProps{:}}';

% Get read-only properties.
ReadonlyProps = pnames(nlsys, 'readonly');

% Match specified property names against list of public properties.
% Include all properties to appropriately detect multiple matches.
try
    for i = 1:2:nin-1
        varargin{i} = nlpnmatchd(varargin{i}, AllProps, 18);
        % Note: if the i:th property name does not uniquely match an item
        % of AllProps, the error generated by nlpnmatchd is catched here.
        
        % Check if varargin{i} is settable.
        if ismember(varargin{i}, ReadonlyProps)
            ctrlMsgUtils.error('Ident:general:readOnlyProp',varargin{i},'IDNLGREY')
        end
    end
    nlsys = pvset(nlsys, varargin{:});
catch E
    throw(E)
end
