function setup(this, hVisParent)
%SETUP    Set up the visual.

%   Copyright 2008 The MathWorks, Inc.
%   $Revision: 1.1.6.3 $  $Date: 2009/04/27 19:54:35 $

setupAxes(this, hVisParent);

visState = 'off';
if ~isempty(this.Application.DataSource) && ~screenMsg(this)
    visState = 'on';
end

this.InfoText = text( ...
    'parent',this.Axes, ...
    'Tag', 'TextInformation', ...
    'units','norm', ...
    'horizontal','center', ...
    'interpreter','none', ...
    'vertical','middle', ...
    'position',[.5 .5],...
    'string','', ...
    'FontName','Courier', ...
    'FontSize',14, ...
    'vis', visState);

% [EOF]
