function initialize(this,Axes)
%INITIALIZE  Initialization for @eventCharView class

%  Author(s):  
%  Copyright 1986-2005 The MathWorks, Inc.
%   $Revision: 1.1.6.6 $  $Date: 2007/10/15 22:55:36 $

[s1,s2] = size(Axes(:,:,1)); 
VLines = zeros([s1 s2]);
Labels = zeros([s1 s2]);

%% Hittest must be on for characteristic data tip to work
for ct=1:s1*s2
   % RE: Set Z=-10 to make sure char lines don't obscure response lines
   VLines(ct) = line(NaN,NaN,-10,...
      'Parent',Axes(ct),...
      'Visible','off',...
      'LineStyle',':',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HandleVisibility','off',...
      'Color','k');
  pe = hggetbehavior(VLines(ct),'PlotEdit');
  pe.Enable = false;
  Points(ct) = line(NaN,NaN,10,...
      'Parent',Axes(ct),...
      'Visible','off',...
      'LineStyle','None',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HandleVisibility','off',...
      'Color','k',...
      'Marker','^',...
      'MarkerSize',10,...
      'MarkerFaceColor','r',...
      'Uicontextmenu', uicontextmenu('Parent',ancestor(Axes(ct),'Figure')));
  pe = hggetbehavior(Points(ct),'PlotEdit');
  pe.Enable = false;
end

    
this.VLines = handle(VLines(:));
this.Points = handle(Points(:));
this.PointTips = cell([s1 s2]);

% Create Event removal context menu. Callback will be populated by
% installtip
cmenu = get(this.Points,{'Uicontextmenu'});
for k=1:length(cmenu)
    uimenu('Parent',cmenu{k},'Label','Remove event','Tag','RemoveEvent');
end