function SavedData = save(Constr)
%SAVE   Saves constraint data

%   Author(s): A. Stothert
%   Revised: 
%   Copyright 2009 The MathWorks, Inc.
%   $Revision: 1.1.8.1 $  $Date: 2009/10/16 06:32:11 $

SavedData = struct(...
   'uID', Constr.uID, ...
   'Origin', Constr.Origin, ...
   'Type', Constr.Data.Type, ...
   'Gain', Constr.Data.xCoords, ...
   'Phase', Constr.Data.yCoords, ...
   'GainUnits', Constr.Data.xUnits, ...
   'PhaseUnits', Constr.Data.yUnits);
