function resetScopesDlg
%resetScopesDlg Reset all session-specific scope data caches.
%   Resets Preferences and Extensions cache.
%   This is called from Prefs dialog and brings up a confirmation dialog.
%   If ok, this simply invokes MPlay.resetScopes.

% Copyright 2004-2006 The MathWorks, Inc.
% $Revision: 1.1.6.1 $  $Date: 2008/04/11 16:22:39 $

proceedStr = 'Clear Cache';
opt = questdlg( ...
    {'Clearing the extension cache will allow new extensions', ...
     'to be discovered the next time a scope is opened.', ...
     '', ...
     'NOTE: This will close all open scopes.', ...
     '', ...
     '(You will need to re-open scope instances yourself.', ...
     ' Using "Save Instrument Sets" can help you do this.)', ...
     ''}, ...
    'Clear Extension Cache', ...
    proceedStr,'Cancel','Cancel');

if strcmp(opt,proceedStr)
    uiscopes.resetScopes; % dump cache
end

% [EOF]
