function Out = set(nlobj, varargin)
%SET  Set properties of custom regressor objects.
%
%   SET(R, 'PropertyName', VALUE) sets the property 'PropertyName'
%   of the custom regressor object R to the value VALUE. An equivalent
%   syntax is
%      R.PropertyName = VALUE
%
%   SET(R, 'Property1', Value1, 'Property2', Value2,...) sets multiple
%   property values with a single statement.
%
%   SET(R, 'Property') displays legitimate values for the specified
%   property.
%
%   SET(R) displays all properties of R and their admissible values.
%
%   If R is an array of custom regressor objects, properties must
%   be set for individual objects with the dot syntax, like
%   R(2).PropertyName=VALUE.

% Copyright 2005-2008 The MathWorks, Inc.
% $Revision: 1.1.8.4 $ $Date: 2008/10/02 18:52:44 $

% Author(s): Qinghua Zhang

% Check input arguments.
ni = nargin;
no = nargout;

if ~isa(nlobj, 'customreg')
    % Call built-in SET. Handles calls like set(gcf,'user',customreg).
    builtin('set', nlobj, varargin{:});
    return;
elseif (no && (ni > 2))
    ctrlMsgUtils.error('Ident:general:setOutputArg','customreg/set','customreg/set')
end

% Handle the case of object array
numobj = numel(nlobj);
if numobj>1
    allowedMOcase = false;
    if ni<3
        objclasses = cell(numobj,1);
        for ko=1:numobj
            objclasses{ko} = class(nlobj.ObjVector{ko});
        end
        if isequal(objclasses{:})
            allowedMOcase = true;
        end
    end
    
    if allowedMOcase
        if no==0
            if ni==1
                disp(sprintf('%dx1 array of objects with the property or properties:', numobj))
            else
                disp(sprintf('For each entry of the %dx1 array of objects:', numobj))
            end
        end
        nlobj = nlobj.ObjVector{1};
    else
        ctrlMsgUtils.error('Ident:idnlmodel:setObjArray')
    end
end

% Get public properties and their assignable values.
[AllProps, AsgnValues] = pnames(nlobj);


% Perform assignment.
if (ni == 1)
    % SET(nlobj) or S = SET(nlobj).
    if no
        Out = cell2struct(AsgnValues(:), AllProps(:), 1);
    else
        disp(idpvformat(AllProps, AsgnValues));
    end
elseif (ni == 2)
    % SET(nlobj, 'Property') or STR = SET(nlobj, 'Property').
    % Return admissible property value(s).
    try
        [Property, imatch] = nlpnmatchd(varargin{1}, AllProps, 18);
        if no
            Out = AsgnValues{imatch};
        else
            disp(AsgnValues{imatch});
        end
    catch E
        throw(E)
    end
else
    % SET(nlobj, 'Prop1', Value1, ...).
    sysname = inputname(1);
    if isempty(sysname)
        ctrlMsgUtils.error('Ident:general:setFirstInput','customreg/set')
    elseif (rem(ni-1, 2) ~= 0)
        ctrlMsgUtils.error('Ident:general:CompletePropertyValuePairs','CUSTOMREG','customreg/set')
    end
    
    % Get read-only properties.
    ReadonlyProps = pnames(nlobj, 'readonly');
    
    % Match specified property names against list of public properties.
    % Include all properties to appropriately detect multiple matches.
    try
        for i = 1:2:ni-1
            varargin{i} = nlpnmatchd(varargin{i}, AllProps, 18);
            % Note: if the i:th property name does not uniquely match an item
            % of AllProps, the error generated by nlpnmatchd is catched here.
            
            % Check if varargin{i} is settable.
            if ismember(varargin{i}, ReadonlyProps)
                ctrlMsgUtils.error('Ident:general:readOnlyProp',varargin{i},'CUSTOMREG')
            end
            
            nlobj.(varargin{i}) = varargin{i+1};
        end
    catch E
        throw(E)
    end
    
    % Assign nlobj in caller's workspace.
    assignin('caller', sysname, nlobj);
end

% FILE END