function build(this,Parent,X0,Y0)
%Function to construct container with Ok, Help and Cancel buttons.

% Author(s): Alec Stothert
% Revised:
% Copyright 1986-2007 The MathWorks, Inc. 
% $Revision: 1.1.8.1 $ $Date: 2009/10/16 06:14:19 $

UIColor = get(Parent,'Color');
%Set sizes
this.Width = 3*this.bWidth+2*this.bgap;
this.Height = this.bHeight;
%Make the container
this.hC = uicontainer('Parent',Parent,...
    'BackgroundColor',UIColor,...
    'units','characters');
%Add the three buttons
this.hOK = uicontrol('Parent',this.hC, ...
   'Style','pushbutton', ...
   'Units','characters', ...
   'Callback','', ...
   'String',sprintf('OK'), ...
   'Tag','btnOK');
this.hCancel = uicontrol('Parent',this.hC, ...
   'Style','pushbutton', ...
   'Units','characters', ...
   'Callback','', ...
   'String', sprintf('Cancel'), ...
   'Tag', 'btnCancel');
this.hHelp = uicontrol('Parent',this.hC, ...
   'Style','pushbutton', ...
   'Units','characters', ...
   'Callback','', ...
   'String', sprintf('Help'),...
   'Tag','btnHelp');
