function initialize(this,Axes)
%INITIALIZE  Initialization for @UncertainTimeView class

%  Author(s): Craig Buhr
%  Copyright 1986-2010 The MathWorks, Inc.
%   $Revision: 1.1.8.1 $  $Date: 2010/05/10 17:37:17 $

[s1,s2] = size(Axes(:,:,1)); 

UncertainMagPatch = zeros([s1 s2]);
UncertainPhasePatch = zeros([s1 s2]);


for ct=1:s1*s2       
   UncertainMagPatch(ct) = patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(1),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'FaceColor',[0.9804 .9*0.9804 0.8235],'EdgeColor',[0.9804 .9*0.9804 0.8235]);
     UncertainPhasePatch(ct) = patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(2),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'FaceColor',[0.9804 .9*0.9804 0.8235],'EdgeColor',[0.9804 .9*0.9804 0.8235]);
end

this.UncertainMagPatch = handle(UncertainMagPatch);
this.UncertainPhasePatch = handle(UncertainPhasePatch);


for ct=1:s1*s2       
    UncertainMagLines(ct) = line([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(1),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'Color',[0.9804 .9*0.9804 0.8235]);
  UncertainPhaseLines(ct) = line([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(2),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'Color',[0.9804 .9*0.9804 0.8235]);
end

this.UncertainMagLines = handle(UncertainMagLines);
this.UncertainPhaseLines = handle(UncertainPhaseLines);
