% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 25-Nov-2009 09:19:39
%  MATLAB version: 7.10.0.123646 (R2010a)
% -------------------------------------------------------------------
                                                                

% Definition of model arguments for: sldemo_mdlref_counter_datamngt.mdl

%   Copyright 1990-2009 The MathWorks, Inc.
%   $Revision: 1.1.10.1 $  $Date: 2009/12/28 04:38:59 $

% Default values for CounterParams structure:
% - Increment:    1
% - LowerLimit: -10
% - UpperLimit:  10
CounterParams = Simulink.Parameter;
saveVarsTmp{1} = struct;
saveVarsTmp{1}.Increment = 1;
saveVarsTmp{1}.LowerLimit = -10;
saveVarsTmp{1}.UpperLimit = 10;
CounterParams.Value = saveVarsTmp{1};
CounterParams.RTWInfo.StorageClass = 'Auto';
CounterParams.RTWInfo.Alias = '';
CounterParams.RTWInfo.CustomStorageClass = 'Default';
CounterParams.Description = '';
CounterParams.DataType = 'Bus: CounterParamType';
CounterParams.Min = -Inf;
CounterParams.Max = Inf;
CounterParams.DocUnits = '';
clear saveVarsTmp;

% Default values for ICs structure:
% - Count:         0
% - OverflowState: InRange
CounterICs = Simulink.Parameter;
saveVarsTmp{1} = struct;
saveVarsTmp{1}.Count = 0;
saveVarsTmp{1}.OverflowState = SlDemoRangeCheck.InRange;
CounterICs.Value = saveVarsTmp{1};
CounterICs.RTWInfo.StorageClass = 'Auto';
CounterICs.RTWInfo.Alias = '';
CounterICs.RTWInfo.CustomStorageClass = 'Default';
CounterICs.Description = '';
CounterICs.DataType = 'Bus: OutputType';
CounterICs.Min = -Inf;
CounterICs.Max = Inf;
CounterICs.DocUnits = '';
clear saveVarsTmp;

