function examples = getexamples(this)
%GETEXAMPLES   Get the examples.

%   Copyright 2008 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2008/10/31 07:04:44 $

examples = { ...
    {'Design a Gaussian windowed FIR filter of order 8 symbols, ', ...
    '% bandwidth-symbol time product of 0.50, and 10 samples per symbol.',...
    'h  = fdesign.pulseshaping(8,''Gaussian'',''Nsym,BT'',8,0.50);', ...
    'Hd = design(h);'};...
    };

% [EOF]
