function createFLSubdialog(dlg)
% Create Fraction Length content for Numeric Type dialog
%
% We don't actually register a dialog here; this is just a helper
% function that contributes UI controls to a parent dialog.

%   Copyright 2010 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $     $Date: 2010/04/21 21:21:25 $

hParent = dlg.ContentPanel;
bg = get(hParent,'BackgroundColor');
ppos = get(hParent,'pos');
pdx = ppos(3); % initial width of parent panel, in pixels

% LSB dialog
dy = 108;
hBAFLPanel = uipanel('parent',hParent, ...
    'units','pix', ...
    'pos', [2 1 pdx-4 dy], ...
    'bordertype','none',...
    'tag','fl_subpanel',...
    'background',bg);
dlg.hBAFLPanel = hBAFLPanel;

inBorder = 2;
outBorder = 2;
xL = inBorder; % inMargin - # pix separation from border to widget
xb = outBorder; % lineWidth # pix on each side of panel taken by border line
x0 = inBorder+1;
y0 = inBorder+76;
dx = pdx-2*inBorder-4;
dy = 20;
dyt = 16; % text prompt heights

% Create LSB widgets
%tip = 'Automatically set underflow threshold';

dlg.hBAFLPrompt =  uicontrol( ...
    'parent', hBAFLPanel, ...
    'backgroundcolor',bg, ...
    'units','pix', ...
    'horiz','left', ...
    'tooltip','', ...
    'pos',[x0 y0 dx dyt], ...
    'String','Fraction length (FL) constraint:',...
    'fontsize',8,...
    'tag','fl_constraint_prompt',...
    'Style','text');

y0 = y0-dy-4;    
tip = DAStudio.message('FixedPoint:fiEmbedded:FLConstraintMethodToolTip');
dlg.hBAFLMethod = uicontrol( ...
    'parent', hBAFLPanel, ...
    'backgroundcolor','w', ...
    'units','pix', ...
    'tooltip',tip, ...
    'pos',[x0 y0 dx dy], ...
    'callback',@(h,e)setBAFLMethod(dlg), ...
    'value',dlg.BAFLMethod, ...
    'style','popup', ...
    'fontsize',8,...
    'tag','fl_constraint_popup',...
    'string','Smallest magnitude|Fractional bits'); %Interactive Underflow|
% xxx NOTE:
% We purposefully removed 'Specify Underflow' from the popup control.
% It should be the 4th entry in the popup, if we wish to re-enable
% this method of fraction length specification in the future.
pdx2 = floor(pdx/2); % midpoint
dxL = pdx2-xb-xL-13;  % Left side is 10 pix shorter
xR = xL+dxL+4; % 1-pix gap to start of xR
dxR = pdx-xR-xb-2;

y0=y0-dy-8;
dlg.hBAFLValuePrompt = uicontrol( ...
    'parent', hBAFLPanel, ...
    'backgroundcolor',bg, ...
    'horiz','right', ...
    'enable','inactive', ...  % allow mouse drag on panel
    'units','pix', ...
    'pos',[x0 y0 dxL dyt], ...
    'string','Value:', ...
    'fontsize',8,...
    'tag','fl_value_prompt',...
    'style','text');

tip = DAStudio.message('FixedPoint:fiEmbedded:SmallestMagToolTip');
dlg.hBAFLSpecifyMagnitude = uicontrol( ...
    'parent',hBAFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'units','pix', ...
    'pos',[xR y0 dxR dy], ...
    'string',sprintf('%g',dlg.BAFLSpecifyMagnitude), ...
    'callback',@(h,e)setBAFLMagEdit(dlg,h), ...
    'tag','fl_lsb_magnitude_edit',...
    'fontsize',8,...
    'style','edit');

tip = DAStudio.message('FixedPoint:fiEmbedded:FLBitsToolTip');
dlg.hBAFLSpecifyBits = uicontrol( ...
    'parent',hBAFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'units','pix', ...
    'pos',[xR y0 dxR dy], ...
    'string',sprintf('%g',dlg.BAFLSpecifyBits), ...
    'callback',@(h,e)setBAFLSpecifyBits(dlg,h), ...
    'tag','fl_bits_edit',...
    'fontsize',8,...
    'style','edit');

y0=y0-dy-8;
tip = DAStudio.message('FixedPoint:fiEmbedded:ExtraFLBitsToolTip');
dlg.hBAFLExtraBitsPrompt = uicontrol( ...
    'parent',hBAFLPanel, ...
    'backgroundcolor',bg, ...
    'tooltip',tip, ...
    'horiz','right', ...
    'enable','inactive', ...
    'units','pix', ...
    'pos',[x0 y0 dxL dyt], ...
    'string','Extra FL bits:', ...
    'fontsize',8,...
    'tag','fl_extra_bits_prompt',...
    'style','text');

dlg.hBAFLExtraBits = uicontrol( ...
    'parent',hBAFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'units','pix', ...
    'pos',[xR y0 dxR dy], ...
    'string',sprintf('%d',dlg.BAFLExtraBits), ...
    'callback',@(h,e)setBAFLExtraBits(dlg,h), ...
    'fontsize',8,...
    'tag','fl_extra_bits_edit',...
    'style','edit');
