function createILFLSubdialog(dlg)
% Create content for the combined IL & FL options.

%   Copyright 2010 The MathWorks, Inc.
%   $Revision: 1.1.6.3 $     $Date: 2010/05/20 02:17:47 $

hParent = dlg.ContentPanel;
bg = get(hParent,'BackgroundColor');
ppos = get(hParent,'pos');
pdx = ppos(3); % initial width of parent panel, in pixels

% MSB dialog
dy = 108;

hBAILFLPanel = uipanel('parent',hParent, ...
    'units','pix', ...
    'pos', [2 1 pdx-4 dy], ...
    'bordertype','none',...
    'tag', 'ilfl_subpanel',...
    'background',bg); %#ok<*PROP>
dlg.hBAILFLPanel = hBAILFLPanel;

inBorder = 2;
outBorder = 2;
xL = inBorder; % inMargin - # pix separation from border to widget
xb = outBorder; % lineWidth # pix on each side of panel taken by border line
x0 = inBorder+1;
y0 = inBorder+76;
dx = pdx-2*inBorder-4;
dy = 20;
dyt = 16; % text prompt heights

pdx2 = floor(pdx/2); % midpoint
dxL = pdx2-xb-xL-13;  %% Left side is 11 pix shorter. We start from 1 pixel inside the border. 
xR = xL+dxL+4; % 1-pix gap to start of xR
dxR = pdx-xR-xb-2;

tip = DAStudio.message('FixedPoint:fiEmbedded:JointConstraintMethodToolTip');
dlg.hBASpecifyPrompt = uicontrol( ...
    'parent', hBAILFLPanel, ...
    'backgroundcolor',bg, ...
    'units','pix', ...
    'horiz','left', ...
    'enable','inactive', ...  % allow mouse drag on panel
    'pos',[x0 y0 pdx2-1 dyt], ... % estimates
    'string','Specify constraint:', ...
    'fontsize',8,...
    'tag','specify_constraint_prompt',...
    'style','text');
 
y0 = y0-dy-4; 
dlg.hBAILFLMethod =  uicontrol( ...
    'parent', hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','right', ...
    'units','pix', ...
    'pos',[x0 y0 dx dy], ...
    'value',dlg.BAILFLMethod, ...
    'callback',@(h,e)setBAILFLMethod(dlg), ...
    'string',['Max occurrences outside range|Largest magnitude|Integer bits|',...
              'Smallest magnitude|Fractional bits'], ...
    'fontsize',8,...
    'tag','ilfl_constraint_popup',...
    'style','popup'); 

% Create the widgets for each of the optimization options.
y0 = y0-dy-8;
tip = DAStudio.message('FixedPoint:fiEmbedded:OverflowPercentMethodToolTip');
dlg.hBAILFLPercent = uicontrol( ...
    'parent', hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'units','pix', ...
    'tooltip',tip, ...
    'horiz','right', ...
    'pos',[x0 y0 dxL dy], ...
    'string',sprintf('%d',dlg.BAILPercent), ...
    'callback',@(h,e)setBAILPercent(dlg,h), ...
    'fontsize',8,...
    'tag','ilfl_overflow_percent_edit',...
    'style','edit');

tip = DAStudio.message('FixedPoint:fiEmbedded:OverflowCountMethodToolTip');
dlg.hBAILFLCount = uicontrol( ...
    'parent', hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'units','pix', ...
    'tooltip',tip, ...
    'horiz','right', ...
    'pos',[x0 y0 dxL dy], ...
    'string',sprintf('%d',dlg.BAILCount), ...
    'callback',@(h,e)setBAILCount(dlg,h), ...
    'fontsize',8,...
    'tag','ilfl_overflow_count_edit',...
    'style','edit');

tip = DAStudio.message('FixedPoint:fiEmbedded:UnitsMethodToolTip');
dlg.hBAILFLUnits = uicontrol( ...
    'parent', hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'units','pix', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'pos',[xR y0 dxR dy], ...
    'string','Percent|Count', ...
    'callback',@(h,e)setBAILUnits(dlg,h), ...
    'value',dlg.BAILUnits, ...
    'fontsize',8,...
    'tag','ilfl_overflow_units_popup',...
    'style','popup');

tip = DAStudio.message('FixedPoint:fiEmbedded:LargestMagToolTip');
dlg.hBAILFLValuePrompt = uicontrol( ...
    'parent', hBAILFLPanel, ...
    'backgroundcolor',bg, ...
    'tooltip',tip, ...
    'horiz','right', ...
    'enable','inactive', ...  % allow mouse drag on panel
    'units','pix', ...
    'pos',[x0 y0-3 dxL dy], ...
    'string','Value:', ...
    'fontsize',8,...
    'tag','ilfl_value_prompt',...
    'style','text');

dlg.hBAILFLSpecifyMSBMagnitude = uicontrol( ...
    'parent',hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'units','pix', ...
    'pos',[xR y0 dxR dy], ...
    'string',sprintf('%g',dlg.BAILSpecifyMagnitude), ...
    'callback',@(h,e)setBAILMagEdit(dlg,h), ...
    'fontsize',8,...
    'tag','ilfl_msb_magnitude_edit',...
    'style','edit');

% Specify Bits goes on same row as Specify Magnitude
tip = DAStudio.message('FixedPoint:fiEmbedded:ILBitsToolTip');
dlg.hBAILFLSpecifyILBits = uicontrol( ...
    'parent',hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'units','pix', ...
    'pos',[xR y0 dxR dy], ...
    'string',sprintf('%g',dlg.BAILSpecifyBits), ...
    'callback',@(h,e)setBAILSpecifyBits(dlg,h), ...
    'fontsize',8,...
    'tag','ilfl_ilbits_edit',...
    'style','edit');

tip = DAStudio.message('FixedPoint:fiEmbedded:SmallestMagToolTip');
dlg.hBAILFLSpecifyLSBMagnitude = uicontrol( ...
    'parent',hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'units','pix', ...
    'pos',[xR y0 dxR dy], ...
    'string',sprintf('%g',dlg.BAFLSpecifyMagnitude), ...
    'callback',@(h,e)setBAFLMagEdit(dlg,h), ...
    'tag','ilfl_lsb_magnitude_edit',...
    'fontsize',8,...
    'style','edit');

tip = DAStudio.message('FixedPoint:fiEmbedded:FLBitsToolTip');
dlg.hBAILFLSpecifyFLBits = uicontrol( ...
    'parent',hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'units','pix', ...
    'pos',[xR y0 dxR dy], ...
    'string',sprintf('%g',dlg.BAFLSpecifyBits), ...
    'fontsize',8,...
    'callback',@(h,e)setBAFLSpecifyBits(dlg,h), ...
    'tag','ilfl_flbits_edit',...
    'style','edit');

y0=y0-dy-8;
% Alt: use safety factor, not guard bits
%      'Increase MSB weight beyond minimum required'
tip = DAStudio.message('FixedPoint:fiEmbedded:ExtraILBitsToolTip');
dlg.hBAILFLGuardBitsPrompt = uicontrol( ...
    'parent', hBAILFLPanel, ...
    'backgroundcolor',bg, ...
    'tooltip',tip, ...
    'enable','inactive', ...
    'horiz','right', ...
    'units','pix', ...
    'pos',[x0 y0 dxL dyt], ...
    'string','Extra IL bits:', ...  %Guard Bits
    'fontsize',8,...
    'tag','ilfl_guard_bits_prompt',...
    'style','text');

dlg.hBAILFLGuardBits = uicontrol( ...
    'parent', hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'units','pix', ...
    'pos',[xR y0 dxR dy], ...
    'string',sprintf('%d',dlg.BAILGuardBits), ...
    'fontsize',8,...
    'callback',@(h,e)setBAILGuardBits(dlg,h), ...
    'tag','ilfl_guard_bits_edit',...
    'style','edit');

tip = DAStudio.message('FixedPoint:fiEmbedded:ExtraFLBitsToolTip');
dlg.hBAILFLExtraBitsPrompt = uicontrol( ...
    'parent',hBAILFLPanel, ...
    'backgroundcolor',bg, ...
    'tooltip',tip, ...
    'horiz','right', ...
    'enable','inactive', ...
    'units','pix', ...
    'pos',[x0 y0 dxL dyt], ...
    'string','Extra FL Bits:', ...
    'fontsize',8,...
    'tag','ilfl_extra_bits_prompt',...
    'style','text');

dlg.hBAILFLExtraBits = uicontrol( ...
    'parent',hBAILFLPanel, ...
    'backgroundcolor','w', ...
    'tooltip',tip, ...
    'horiz','left', ...
    'units','pix', ...
    'pos',[xR y0 dxR dy], ...
    'string',sprintf('%d',dlg.BAFLExtraBits), ...
    'callback',@(h,e)setBAFLExtraBits(dlg,h), ...
    'fontsize',8,...
    'tag','ilfl_extra_bits_edit',...
    'style','edit');
