function maskline = getmaskline(this)
%GETMASKLINE   Get the maskline.

%   Author(s): J. Schickler
%   Copyright 2004 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2004/12/26 22:21:37 $

maskline = dspdata.maskline(...
    'EnableMask',          this.EnableMask, ...
    'NormalizedFrequency', this.NormalizedFrequency, ...
    'FrequencyVector',     evaluatevars(this.FrequencyVector), ...
    'MagnitudeUnits',      this.MagnitudeUnits, ...
    'MagnitudeVector',     evaluatevars(this.MagnitudeVector));

% [EOF]
