function setmaskline(this, maskline)
%SETMASKLINE   Set the maskline.

%   Author(s): J. Schickler
%   Copyright 2004 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2004/12/26 22:21:42 $

set(this, 'EnableMask',    maskline.EnableMask, ...
    'NormalizedFrequency', maskline.NormalizedFrequency, ...
    'FrequencyVector',     mat2str(maskline.FrequencyVector), ...
    'MagnitudeUnits',      maskline.MagnitudeUnits, ...
    'MagnitudeVector',     mat2str(maskline.MagnitudeVector), ...
    'isApplied',           true);

% [EOF]
