function setup_figure(this)
%SETUP_FIGURE   Set up the figure.

%   Author(s): J. Schickler
%   Copyright 2004 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2004/12/26 22:21:43 $

sz = gui_sizes(this);

hFig = figure('Visible', 'Off', ...
    'Menubar', 'none', ...
    'HandleVisibility', 'off', ...
    'IntegerHAndle', 'off', ...
    'NumberTitle', 'Off', ...
    'Color', get(0, 'defaultuicontrolbackgroundcolor'), ...
    'Name', 'User-defined Spectral Mask', ...
    'Position', [100 100 300 200]*sz.pixf);

set(this, 'FigureHandle', hFig);

% [EOF]
