function disp(this)
%DISP     Display this object
%   OUT = DISP(ARGS) <long description>

%   @commscope/@eyediagramgui
%
%   Copyright 2007-2008 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2008/05/12 21:22:45 $

% Define the fields to be displayed in order
fieldNames = {'Type', ...
    'Version', ...
    'FigureHandle', ...
    'Parent', ...
    'WindowRendered', ...
    'ScopeFaceRendered', ...
    'SessionName', ...
    'LastImportFileLocation', ...
    'LastSessionFileLocation', ...
    'FirstSave', ...
    'Dirty', ...
    'EyeDiagramObjMgr', ...
    'SingleEyeScopeFace', ...
    'CompareResultsScopeFace', ...
    'CurrentScopeFace', ...
    'SettingsPanel', ...
    'MeasurementsPanel', ...
    'PlotCtrlWin', ...
    'Listeners', ...
    'AutoListeners__', ...
    };

% Define the fields to be excluded
excludedFieldNames = {};

baseDisp(this, fieldNames, excludedFieldNames);

%-------------------------------------------------------------------------------
% [EOF]
