function renderHelpMenu(this)
%RENDERHELPMENU <short description>
%   OUT = RENDERHELPMENU(ARGS) <long description>

%   @commscope/@eyediagramgui
%
%   Copyright 2007-2008 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2008/05/12 21:22:54 $

% Get the figure handle
hFig = this.FigureHandle;

% Create the file menu
hHelpMenu = uimenu(...
    'Parent',hFig,...
    'Label','&Help',...
    'Tag','HelpMenu');

% Attach submenu items
uimenu(...
    'Paren',hHelpMenu, ...
    'Label', '&EyeScope Help', ...
    'Callback', @menucbHelp, ...
    'Position', 1, ...
    'Separator', 'off', ...
    'Tag', 'HelpEyeScope');

uimenu(...
    'Paren',hHelpMenu, ...
    'Label', 'Eye &Diagram Help', ...
    'Callback', @menucbHelp, ...
    'Position', 2, ...
    'Separator', 'off', ...
    'Tag', 'HelpEyeDiagram');

uimenu(...
    'Paren',hHelpMenu, ...
    'Label', 'About Communications Toolbox', ...
    'Callback', @menucbHelpAboutCommsTlbx, ...
    'Position', 3, ...
    'Separator', 'on', ...
    'Tag', 'HelpAboutCommsToolbox');


%-------------------------------------------------------------------------------
function menucbHelp(hsrc, eventdata)
% Callback function for Help menu items

% Get the source
sourceID = get(hsrc, 'Tag');

if strcmp(sourceID, 'HelpEyeScope')
    helpview([docroot '/toolbox/comm/comm.map'], 'eyescope_main');
else
    helpview([docroot '/toolbox/comm/comm.map'], 'commscope.eyediagram');
end

%-------------------------------------------------------------------------------
function menucbHelpAboutCommsTlbx(hsrc, eventdata)
% Callback function for About Communications Toolbox menu item

aboutcommtlbx;

%-------------------------------------------------------------------------------
% [EOF]
