function handles = renderViewMenu(this)
%RENDERVIEWMENU <short description>

%   Copyright 2007-2008 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2008/06/13 15:11:42 $

% Get the figure handle
hFig = this.FigureHandle;

% Create the file menu
hViewMenu = uimenu(...
    'Parent',hFig,...
    'Label','&View',...
    'Tag','ViewMenu');

% Attach submenu items
handles.ViewSingleEye = uimenu(...
    'Parent',hViewMenu,...
    'Callback',{@(hsrc,edata)menucbView(hsrc, this)},...
    'Label','Single Eye Diagram View',...
    'Position', 1,...
    'Checked', 'on', ...
    'Tag','ViewMenuSingleEye');

handles.ViewCompare = uimenu(...
    'Parent',hViewMenu,...
    'Callback',{@(hsrc,edata)menucbView(hsrc, this)},...
    'Label','&Compare Measurement Results View',...
    'Position', 2,...
    'Tag','ViewMenuCompare');

handles.ViewLegend = uimenu(...
    'Parent',hViewMenu,...
    'Callback',{@(hsrc,edata)menucbViewLegend(hsrc, this)},...
    'Label','&Legend',...
    'Position', 3,...
    'Separator', 'on',...
    'Enable', 'off', ...
    'Checked', 'off', ...
    'Tag','ViewMenuLegend');
end
%-------------------------------------------------------------------------------
function menucbView(hsrc, hGui)
% Callback function for view options

% Get the caller ID
callerID = get(hsrc, 'Tag');

% Set the new scope face
if strncmp(callerID, 'ViewMenuSingleEye',12)
    hGui.CurrentScopeFace = hGui.SingleEyeScopeFace;
else
    hGui.CurrentScopeFace = hGui.CompareResultsScopeFace;
end
end
%-------------------------------------------------------------------------------
function menucbViewLegend(hsrc, this)
if strcmp(get(hsrc, 'Checked'), 'on')
    setLegend(this.CurrentScopeFace, 'off')
    set(hsrc, 'Checked', 'off')
else
    setLegend(this.CurrentScopeFace, 'on')
    set(hsrc, 'Checked', 'on')
end
end
%-------------------------------------------------------------------------------
% [EOF]
