function [F,ERR] = eml_fimath_constructor_helper(useInputFimathForFimathConstructors,emlInputFimath,varargin)
% EML_FIMATH_CONSTRUCTOR_HELPER Helper function for eML to construct a
% fimath object.

%   Copyright 2003-2009 The MathWorks, Inc.
%   $Revision: 1.1.8.9 $  $Date: 2009/12/28 04:11:50 $


ERR = ''; F = [];
try
    % Set the global fimath
    if useInputFimathForFimathConstructors || fifeature('FimathLessFis')
        emlDefaultFimath = emlInputFimath;
    else
        emlDefaultFimath = fimath('RoundMode','nearest',...
                                  'OverflowMode','saturate',...
                                  'ProductMode','FullPrecision',...
                                  'ProductWordLength',32,...
                                  'MaxProductWordLength',128,...
                                  'ProductFractionLength',30,...
                                  'ProductSlopeAdjustmentFactor',1,...
                                  'ProductBias',0,...
                                  'SumMode','FullPrecision',...
                                  'SumWordLength',32,...
                                  'MaxSumWordLength',128,...
                                  'SumFractionLength',30,...
                                  'SumSlopeAdjustmentFactor',1,...
                                  'SumBias',0);
    end
    origDefaultFimath = fimath;
    globalfimath(emlDefaultFimath);
    F = fimath(varargin{:});
    % Reset the default fimath to its original value
    globalfimath(origDefaultFimath);
 
catch ME
    % Reset the global fimath to its original value
    globalfimath(origDefaultFimath);
    ERR = ME.message;
end


