function [sigbH, errStr] = sigbuild_handle(modelH)

%   Copyright 2009-2010 The MathWorks, Inc.

    errStr = '';
    sigbH = find_system(modelH, ...
                        'SearchDepth',        1, ...
                        'LoadFullyIfNeeded', 'off', ...
                        'FollowLinks',       'off', ...
                        'LookUnderMasks',    'all', ...
                        'BlockType',         'SubSystem', ...
                        'PreSaveFcn',        'sigbuilder_block(''preSave'');');
    if isempty(sigbH) || length(sigbH)~=1
        sigbH = [];
        errStr = sprintf(['There must be exactly 1 Signal Builder block '...
            'on the top level of model ''%s'''],get_param(modelH,'Name'));
    end
end

% LocalWords:  sigbuilder
