function SavedData = save(Constr)
%SAVE  Saves constraint data

%   Author(s): A. Stothert
%   Copyright 1986-2006 The MathWorks, Inc. 
%   $Revision: 1.1.8.1 $  $Date: 2009/10/16 06:32:52 $

SavedData = struct(...
   'uID', Constr.uID, ...
   'xCoord', Constr.xCoords, ...
   'xUnits', Constr.xUnits, ...
   'yCoord', Constr.yCoords, ...
   'yUnits', Constr.yUnits, ...
   'Linked', Constr.Linked, ...
   'Weight', Constr.Weight, ...
   'SelectedEdge', Constr.SelectedEdge, ...
   'Type', Constr.Type, ...
   'OpenEnd', Constr.getData('OpenEnd'));