function ok = compiler_supports_eml_openmp(compilerName)

%   Copyright 2008-2010 The MathWorks, Inc.

supported_compiler = true;
if strcmp(compilerName, 'intelc91msvs2005') || ...
   strcmp(compilerName, 'intelc11msvs2008') || ...	
   strcmp(compilerName, 'openwatc') || ...
   strcmp(compilerName, 'borland') || ...
   strcmp(compilerName, 'lcc') || ...
   strcmp(compilerName, 'msvc60') || ...
   strcmp(compilerName, 'msvc90')
   supported_compiler = false;
end
% supported:
%  'gcc'
%  'msvc80'
ok = supported_compiler;