function c2dtool(sisodb)
%C2DTOOL Opens and operates the Conversion window

%   Authors: Karen D. Gondoly and P. Gahinet
%   Copyright 1986-2008 The MathWorks, Inc.
%   $Revision: 1.33.4.9 $  $Date: 2009/11/09 16:22:29 $

LoopData = sisodb.LoopData;

DesignData = LoopData.exportdesign; % @sisodata.design object

% Conversion methods
Methods = {...
        'zoh' , 'Zero-Order Hold';...
        'foh' , 'First-Order Hold';...
        'imp', 'Impulse Invariant';...
        'tustin' , 'Tustin';...
        'prewarp' , 'Tustin w/Prewarping';...
        'matched' , 'Matched Pole-Zero'};

% Open window
ConvertFig = LocalOpenFig(sisodb,Methods,DesignData);

% Install listeners
lsnr(1) = handle.listener(LoopData,...
    'ObjectBeingDestroyed',{@LocalClose ConvertFig});
lsnr(2) = handle.listener(LoopData,...
    'LoopDataChanged',{@LocalClose ConvertFig});

% Store model data
UIData = struct(...
      'DesignData', DesignData, ...
      'Listener',lsnr);
set(ConvertFig,'UserData',UIData,'Visible','on')


%------------------------ Callback Functions --------------------

%%%%%%%%%%%%%%
% LocalHelp %
%%%%%%%%%%%%%%
function LocalHelp(hSrc,event)
mapfile = ctrlguihelp;
helpview(mapfile,'sisoconversion','CSHelpWindow');

%%%%%%%%%%%%%%
% LocalClose %
%%%%%%%%%%%%%%
function LocalClose(hSrc,event,ConvertFig)
% Close constraint dialog when GUI is closed
delete(ConvertFig)


%%%%%%%%%%%%%%%%
% LocalConvert %
%%%%%%%%%%%%%%%%
function LocalConvert(hSrc,event,Methods,sisodb,Handles,CloseFlag)
% Converts initial model data to selected domain using specified parameters

FigUd = get(Handles.Figure,'UserData');  % contains initial model data
DesignData = FigUd.DesignData;
InitialTs = DesignData.getTs; % initial sample time
Components = [DesignData.Fixed; DesignData.Tuned];
numComponents = length(Components);

% Determine target domain
if InitialTs == 0
    ToContinuous = false;
else
    ToContinuous = (get(Handles.DiscreteButton,'Value')==0);
end

% Get conversion method and related data
Selections = get(Handles.Method(:,2),{'Value'});
Methods = Methods(cat(1,Selections{:}));

% Critical frequencies (for prewarp method only)
CritFreq = cell(numComponents,1);
ipw = find(strcmp(Methods,'prewarp'));
CritFreq(ipw) = get(Handles.Method(ipw,4),{'UserData'});


% Perform conversion
try
    if ToContinuous
        % D2C conversion
        ConvertFcn = 'd2c';
        Args = [Methods,CritFreq];
        ActionDetails = 'Converted the loop components to continuous time.';
    else
        % C2D or D2D conversion
        TargetTs = abs(get(Handles.SampleTimeEdit,'UserData'));
        Args = cell(numComponents,1);
        Args(:,1) = {TargetTs};
        if InitialTs,
            % D2D conversion
            ConvertFcn = 'd2d';
            ActionDetails = sprintf('Resampled the loop components to new sample time of %0.3g seconds.',...
                TargetTs);
        else
            ConvertFcn = 'c2d';
            Args = [Args,Methods,CritFreq];
            ActionDetails = sprintf('Discretized the loop components using a sample time of %0.3g seconds.',...
                TargetTs);
        end
    end
    
    newDesignData = copy(DesignData);
    % Perform conversion
    for cnt = 1:numComponents
       newDesignData.(Components{cnt}).Value = feval(ConvertFcn, ...
                   DesignData.(Components{cnt}).Value,Args{cnt,:});
    end
    
    % Convert Loops TunedLFT.IC for configuration 0
    % For standard configurations this is done through computeLoop
    if isequal(DesignData.Configuration,0)
        Loops = newDesignData.Loops;
        for ct = 1:length(Loops)
            newDesignData.(Loops{ct}).TunedLFTSSData = feval(ConvertFcn, ...
                   DesignData.(Loops{ct}).TunedLFTSSData,Args{1,:});
        end
    end
    
    
catch ME      
    errordlg(ltipack.utStripErrorHeader(ME.message),'Conversion Error','modal');
    return
    
end

% Unlock all axes limits
idxVis = find(strcmp(get(sisodb.PlotEditors,'Visible'),'on'));
for ct=idxVis',
    zoomout(sisodb.PlotEditors(ct));
end

% Import converted models 
LoopData = sisodb.LoopData;
EventMgr = sisodb.EventManager;

% Start transaction
T = ctrluis.transaction(LoopData,'Name','Conversion',...
    'OperationStore','on','InverseOperationStore','on');

% Perform conversion and register transaction (error-free here)
LoopData.importdata(newDesignData);


% Commit and store transaction
EventMgr.record(T);



% Disable listener for closing the Conversion dialog when a DataChanged event is fired,
% notify peers of data change, and reenable listener
DataListener = FigUd.Listener(2); 
set(DataListener,'Enabled','off'); 
dataevent(LoopData,'all');
set(DataListener,'Enabled','on'); 


% Update status and command history
EventMgr.newstatus(ActionDetails);
EventMgr.recordtxt('history',ActionDetails);


% Exit
if CloseFlag
    % Close window if requested
    delete(Handles.Figure)
end


%%%%%%%%%%%%%%%%%%
% LocalSetDomain %
%%%%%%%%%%%%%%%%%%
function LocalSetDomain(hSrc,event,ConversionType,Handles)
% Sets the target domain (continuous or discrete)

if strcmp(ConversionType,'continuous')
    % Target domain = continuous
    set(Handles.ContinuousButton,'Value',1)
    set(Handles.DiscreteButton,'Value',0)
    set([Handles.SampleTimeEdit,Handles.SampleTimeText],'Enable','off')
    set(Handles.Method,'Enable','on')
else
    % Target domain = discrete
    set(Handles.ContinuousButton,'Value',0)
    set(Handles.DiscreteButton,'Value',1)
    set([Handles.SampleTimeEdit,Handles.SampleTimeText],'Enable','on')
    set(Handles.Method,'Enable','off')
end


%%%%%%%%%%%%%%%%%%
% LocalSetMethod %
%%%%%%%%%%%%%%%%%%
function LocalSetMethod(hPopUp,event,Handles,Methods)
% Sets the conversion method

SelectedMethod = Methods{get(hPopUp,'Value')};
iPop = find(Handles.Method(:,2)==hPopUp);
if strcmp(SelectedMethod,'prewarp')
    set(Handles.Method(iPop,[3 4]),'Visible','on')
else
    set(Handles.Method(iPop,[3 4]),'Visible','off')
end



%%%%%%%%%%%%%
% LocalEdit %
%%%%%%%%%%%%%
function LocalEdit(hEdit,event,Item)
% Edit the sample time or critical frequency
InputStr = get(hEdit,'String');
InputValue = eval(InputStr,'[]');

if ~isequal(size(InputValue),[1 1]) | ~isreal(InputValue) | ...
        ~isfinite(InputValue) | InputValue<=0,
    % Revert to previous value in edit box
    switch Item
    case 'Ts'
        warndlg(xlate('You must enter a valid nonnegative sample time.'), ...
            xlate('Conversion Warning'));
    case 'CF'
        warndlg(xlate('You must enter a valid critical frequency greater then zero.'), ...
            xlate('Conversion Warning'));
    end
    set(hEdit,'String',num2str(get(hEdit,'UserData')));
else
    % Log new value in
    InputStr = num2str(InputValue);
    set(hEdit,'UserData',InputValue,'String',InputStr)
end 


%%%%%%%%%%%%%%%%%%%%
%%% LocalOpenFig %%% 
%%%%%%%%%%%%%%%%%%%%
function ConvertFig = LocalOpenFig(sisodb,Methods,DesignData)

Ts = DesignData.getTs;
if Ts
    % FOH and IMP not offered for DT
    Methods = Methods([1,4:6],:);
end

% Names for fixed and tuned systems
FixedData = DesignData.Fixed;
TunedData = DesignData.Tuned;
Components = [FixedData; TunedData];
numComponents = length(Components);
LabelLength = size(char(Components),2);
MethodLabelLength = size(char(Methods(:,2)),2);

% Parameters
StdColor = get(0,'DefaultUIControlBackground');
StdUnit = 'character';
hBorder = 1.5;
vBorder = 0.5;
EditH = 1.5;
TextH = 1.1;
Toffset = 2;
FigW = max(53,3*hBorder+LabelLength+27+MethodLabelLength);




% Create figure
ConvertFig = figure('Color',StdColor, ...
   'IntegerHandle','off', ...
   'Units',StdUnit,...
   'Resize','off',...
   'MenuBar','none', ...
   'Name',xlate('Sample Time Conversion'), ...
   'NumberTitle','off', ...
   'HandleVisibility','callback',...
   'Visible','off');
Handles.Figure = ConvertFig;

% Button group
BW = (FigW-5*hBorder)/4;  BH = 1.5;
X0 = hBorder; Y0 = vBorder;
Handles.OK = uicontrol('Parent',ConvertFig, ...
   'Units',StdUnit, ...
   'Position',[X0 Y0 BW BH], ...
   'String','OK');
X0 = X0+hBorder+BW;
uicontrol('Parent',ConvertFig, ...
   'Units',StdUnit, ...
   'Callback',{@LocalClose ConvertFig}, ...
   'Position',[X0 Y0 BW BH], ...
   'String','Cancel');
X0 = X0+hBorder+BW;
uicontrol('Parent',ConvertFig, ...
   'Units',StdUnit, ...
   'Callback',{@LocalHelp}, ...
   'Position',[X0 Y0 BW BH], ...
   'String','Help');
X0 = X0+hBorder+BW;
Handles.Apply = uicontrol('Parent',ConvertFig, ...
   'Units',StdUnit, ...
   'Position',[X0 Y0 BW BH], ...
   'String','Apply');




% Method frame
Y0 = Y0+BH+vBorder; FW = FigW-2*hBorder; FH = numComponents*EditH+(numComponents*1.45+3)*vBorder;
HTKey = 'sisoconversionmethod';
uicontrol('Parent',ConvertFig, ...
    'BackgroundColor',StdColor, ...
    'Units',StdUnit, ...
    'Position',[hBorder Y0 FW FH], ...
    'HelpTopicKey',HTKey,...
    'Style','frame');
uicontrol('Parent',ConvertFig, ...
    'Units',StdUnit, ...
    'BackgroundColor',StdColor, ...
    'Position',[hBorder+Toffset Y0+FH-TextH/2 20 TextH], ...
    'String','Conversion Method', ...
    'HelpTopicKey',HTKey,...
    'Style','text');
X0 = 3*hBorder; Y1 = Y0+2*vBorder; 



PW = MethodLabelLength + 7;  X1 = X0+LabelLength+2;  X2 = X1+PW+1;  X3 = X2+3;  EditW = FW-X3-hBorder;
Handles.Method = zeros(numComponents,4);
for ct=numComponents:-1:1,
    Handles.Method(ct,1) = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',StdColor, ...
        'HorizontalAlignment','left', ...
        'Position',[X0 Y1+(EditH-TextH)/2 LabelLength+2 TextH], ...
        'String',[Components{ct},':'], ...
        'HelpTopicKey',HTKey,...
        'Style','text');
    Handles.Method(ct,2) = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',[1 1 1], ...
        'Position',[X1 Y1 PW EditH], ...
        'Style','popupmenu', ...
        'String',Methods(:,2),...
        'HelpTopicKey',HTKey,...
        'Value',1);
    Handles.Method(ct,3) = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',StdColor, ...
        'HorizontalAlignment','left', ...
        'Position',[X2 Y1+(EditH-TextH)/2 3 TextH], ...
        'String','at', ...
        'Visible','off',...
        'HelpTopicKey',HTKey,...
        'Style','text');    
    Handles.Method(ct,4) = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'Position',[X3 Y1 EditW EditH], ...
        'Style','edit', ...
        'Visible','off',...
        'String','1',...
        'HelpTopicKey',HTKey,...
        'UserData',1);
    Y1 = Y1 + EditH + 1.45 * vBorder;
end

% Domain Frame
% Initialize based on current domain
if Ts ~= 0
    % Domain frame for initial domain = discrete
    Y0 = Y0+FH+2*vBorder; FH = 3*EditH+6*vBorder;
    HTKey = 'sisoconversiondomain';
    uicontrol('Parent',ConvertFig, ...
        'BackgroundColor',StdColor, ...
        'Units',StdUnit, ...
        'Position',[hBorder Y0 FW FH], ...
        'HelpTopicKey',HTKey,...
        'Style','frame');
    uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',StdColor, ...
        'Position',[hBorder+Toffset Y0+FH-TextH/2 11 TextH], ...
        'String','Convert to', ...
        'HelpTopicKey',HTKey,...
        'Style','text');
    X0 = hBorder + 9;  Y0 = Y0 + 2*vBorder;
    Handles.SampleTimeText = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',StdColor, ...
        'HorizontalAlignment','left', ...
        'Position',[X0 Y0+(EditH-TextH)/2 19 TextH], ...
        'String','Sample time (sec):', ...
        'HelpTopicKey',HTKey,...
        'Style','text');
    Handles.SampleTimeEdit = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'Position',[X0+20 Y0 0.3*FW EditH], ...
        'String', num2str(Ts), ...
        'UserData', Ts, ...
        'HelpTopicKey',HTKey, ...
        'Style','edit');
    X0 = 3*hBorder; Y0 = Y0+EditH+0.9*vBorder;
    Handles.DiscreteButton = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',StdColor, ...
        'Horizontal','left', ...
        'Position',[X0 Y0 0.8*FW EditH], ...
        'String','Discrete time with new sample time',...
        'HelpTopicKey',HTKey,...
        'Style','radiobutton');
    Y0 = Y0+EditH+0.8*vBorder;
    Handles.ContinuousButton = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',StdColor, ...
        'Position',[X0 Y0 0.5*FW EditH], ...
        'Horizontal','left', ...
        'String','Continuous time', ...
        'HelpTopicKey',HTKey,...
        'Style','radiobutton');
    
    % Set callbacks for radio buttons
    set(Handles.ContinuousButton, 'Callback',{@LocalSetDomain 'continuous' Handles});
    set(Handles.DiscreteButton, 'Callback',{@LocalSetDomain 'discrete' Handles});
    % Initialize radio buttons
    LocalSetDomain([],[],'continuous',Handles)
    
else
    % Domain frame for initial domain = continuous
    Y0 = Y0+FH+2*vBorder; FH = EditH+4*vBorder;
    HTKey = 'sisoconversiondomain';
    uicontrol('Parent',ConvertFig, ...
        'BackgroundColor',StdColor, ...
        'Units',StdUnit, ...
        'Position',[hBorder Y0 FW FH], ...
        'HelpTopicKey',HTKey,...
        'Style','frame');
    uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',StdColor, ...
        'Position',[hBorder+Toffset Y0+FH-TextH/2 16 TextH], ...
        'String','Discretize with', ...
        'HelpTopicKey',HTKey,...
        'Style','text');
    X0 = 3*hBorder;  Y0 = Y0 + 2*vBorder;
    Handles.SampleTimeText = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',StdColor, ...
        'HorizontalAlignment','left', ...
        'Position',[X0 Y0+(EditH-TextH)/2 19 TextH], ...
        'String','Sample time (sec):', ...
        'HelpTopicKey',HTKey,...
        'Style','text');
    Handles.SampleTimeEdit = uicontrol('Parent',ConvertFig, ...
        'Units',StdUnit, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'Position',[X0+20 Y0 0.3*FW EditH], ...
        'String','1', ...
        'UserData', 1 , ...
        'HelpTopicKey',HTKey,...
        'Style','edit');
end


% Set Figure height and position
FigH = Y0 + EditH + 0.9*vBorder + 3*vBorder;
set(Handles.Figure,'Position',[10 10 FigW FigH]);
centerfig(ConvertFig,sisodb.Figure);



% Callbacks
set(Handles.Method(:,2),'Callback',{@LocalSetMethod Handles Methods(:,1)})
set(Handles.Method(:,4),'Callback',{@LocalEdit 'CF'})
set(Handles.SampleTimeEdit,'Callback',{@LocalEdit 'Ts'})
set(Handles.OK,'Callback',{@LocalConvert Methods(:,1) sisodb Handles 1})
set(Handles.Apply,'Callback',{@LocalConvert Methods(:,1) sisodb Handles 0})

% Install CS help
% RE: Do this last for proper initialization when opened while CS help is on
ctrlcshelp(ConvertFig,sisodb.Figure);


