function nativeTypes = getNativeTypes
%GETNATIVETYPES Returns the native supported types.
%   slmgr.getNativeTypes Returns the native supported types.  These are the
%   datatypes which can be queried directly using Data.  If a data type is
%   not found in this list it should usually be read using DataAsDouble.

%   Copyright 2009 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2009/11/16 22:33:36 $

nativeTypes = { ...
    'double', ...
    'single', ...
    'uint8', ...
    'uint16', ...
    'uint32', ...
    'int8', ...
    'int16', ...
    'int32', ...
    'boolean'};

% [EOF]
