%DRAWNOW Flush pending graphics events.
%   DRAWNOW "flushes the event queue" and updates the figure window.
%
%   DRAWNOW causes figure windows and their children to update and
%   flushes the system event queue. Any callbacks generated by incoming
%   events - e.g. mouse or key events - will be dispatched before
%   DRAWNOW returns.
%
%   DRAWNOW('EXPOSE') causes only graphics objects to refresh, if
%   needed. It does not allow callbacks to execute and does not
%   process other events in the queue.
%
%   DRAWNOW('UPDATE') causes only non-graphics objects to refresh, if
%   needed. It does not allow callbacks to execute and does not
%   process other events in the queue.
%
%   DRAWNOW is called implicitly upon returning to the MATLAB prompt and
%   when executing the following functions:
%
%     figure
%     getframe
%     ginput
%     input
%     keyboard
%     pause
%     waitfor
%     waitforbuttonpress
%
% See also PAUSE, GETFRAME, FIGURE, WAITFOR, WAITFORBUTTONPRESS, GINPUT

%   DRAWNOW('DISCARD') causes the information to be updated as if
%   the queued events were flushed, but doesn't actually flush
%   them.  This is needed for printing hardcopy when the figure
%   property InvertHardcopy is on.

%   Copyright 1984-2007 The MathWorks, Inc.
%   $Revision: 5.9.4.7 $  $Date: 2007/06/14 05:09:23 $
%   Built-in function.
