function attr = dicom_create_attr
%DICOM_CREATE_ATTR  Create a structure to contain an attribute.
%   ATTR = DICOM_CREATE_ATTR create a structure ATTR to contain an
%   attribute's metadata.  The fields are filled with empty values.

%   Copyright 1993-2005 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2008/05/12 21:30:53 $

attr = struct('Name', '', ...
              'Group', [], ...
              'Element', [], ...
              'VR', '', ...
              'VM', [], ...
              'Length', []);
