function exprofile_check_enabled(model)
%EXPROFILE_CHECK_ENABLED throws an error if execution profiling is not enabled
%   EXPROFILE_CHECK_ENABLED(MODEL) Checks the status of
%   ExecutionProfilingEnabled parameter in a MODEL. If the status of
%   ExecutionProfilingEnabled is 'off' this function will throw an error.

%   Copyright 1990-2006 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2006/06/16 20:13:38 $

try

    exprofile_enabled = get_param(model, 'ExecutionProfilingEnabled');

catch

    error_STF = ['The operation of the execution profiling block requires' ...
    ' that the current System Target File has support for execution' ...
    ' profiling. If you wish to use the execution profiling block in your' ...
    ' model you should select an appropriate System Target File,' ...
    ' for example mpc555rt.tlc or c166.tlc. You can select the System Target File from' ...
    ' the Real-Time Workshop panel of the configuration parameters. If you' ...
    ' do not wish to use the execution profiling in you should remove' ...
    ' the execution profiling block from your model to prevent this' ...
    ' error.'];
  error(error_STF);    

end

if (strcmp(exprofile_enabled, 'off'))

    error_not_enabled = [ ...
        'The operation of the execution profiling block requires' ...
        ' that execution profiling is enabled. You can enable execution' ...
        ' profiling by checking the box in the target specific panel of the' ...
        ' configuration parameters in your model. If you do not want to enable' ...
        ' execution profiling, you should remove the execution profiling' ...
        ' block from your model to prevent this error.'];
    error(error_not_enabled);
    
end

