function diagnostics = getDiagnosticsList()
    % This function returns the list of all SF diagnostics in the config
    % set.

%   Copyright 2009 The MathWorks, Inc.
    
    diagnostics = {'SFUnusedDataAndEventsDiag', ...
        'SFUnexpectedBacktrackingDiag', ...
        'SFInvalidInputDataAccessInChartInitDiag', ...
        'SFNoUnconditionalDefaultTransitionDiag', ...
        'SFMismatchInSimAndRtwBecauseOfMissingDataTypeDiag', ...
        'SFTransitionOutsideNaturalParentDiag'};  
end
