function createUIControls_tableContextMenuCompRuns(this)

%   Copyright 2010 The MathWorks, Inc.

    % Cache string dictionary class
    SD = Simulink.sdi.StringDict;       
        

    this.tableContextMenuCompRuns = uicontextmenu('parent',this.HDialog);
    
    this.tableContextMenuColumnsCompRuns = uimenu(this.tableContextMenuCompRuns,...
                                                  'label', this.sd.mgColumns);
    
    this.tableContextMenuBlkSrc  = uimenu(this.tableContextMenuColumnsCompRuns,...
                                          'label', this.sd.IGBlockSourceColName);
 
    this.tableContextMenuBlkSrc1  = uimenu(this.tableContextMenuBlkSrc,...
                                           'label', this.sd.mgRun1BlkSrc);
    this.tableContextMenuBlkSrc2  = uimenu(this.tableContextMenuBlkSrc,...
                                           'label', this.sd.mgRun2BlkSrc);                                          
                                          
    this.tableContextMenuDataSrc  = uimenu(this.tableContextMenuColumnsCompRuns,...
                                           'label', this.sd.IGDataSourceColName); 
    this.tableContextMenuDataSrc1  = uimenu(this.tableContextMenuDataSrc,...
                                            'label', this.sd.mgRun1DataSrc);
    this.tableContextMenuDataSrc2  = uimenu(this.tableContextMenuDataSrc,...
                                            'label', this.sd.mgRun2DataSrc);
        
    this.tableContextMenuSID  = uimenu(this.tableContextMenuColumnsCompRuns,...
                                              'label', this.sd.mgSID);
 
    this.tableContextMenuSID1  = uimenu(this.tableContextMenuSID,...
                                              'label', this.sd.mgRun1SID);
    this.tableContextMenuSID2  = uimenu(this.tableContextMenuSID,...
                                              'label', this.sd.mgRun2SID); 
    
    this.tableContextMenuCompRunAbsTol  = uimenu(this.tableContextMenuColumnsCompRuns,...
                                                 'label', this.sd.MGAbsTolLbl);
    this.tableContextMenuCompRunRelTol  = uimenu(this.tableContextMenuColumnsCompRuns,...
                                                'label', this.sd.MGRelTolLbl);
    this.tableContextMenuCompRunSync  = uimenu(this.tableContextMenuColumnsCompRuns,...
                                              'label', this.sd.MGSynchMethodLbl);
    this.tableContextMenuCompRunInterp  = uimenu(this.tableContextMenuColumnsCompRuns,...
                                                 'label', this.sd.MGInterpMethodLbl); 
    this.tableContextMenuCompRunChannel  = uimenu(this.tableContextMenuColumnsCompRuns,...
                                                 'label', this.sd.mgChannel1);     
  
    set(this.tableContextMenuBlkSrc1, 'callback',...
        @this.tableContextMenu_CompRuns);
    set(this.tableContextMenuBlkSrc2, 'callback',...
        @this.tableContextMenu_CompRuns);
    set(this.tableContextMenuDataSrc1, 'callback',...
        @this.tableContextMenu_CompRuns);
    set(this.tableContextMenuDataSrc2, 'callback',...
        @this.tableContextMenu_CompRuns);
    set(this.tableContextMenuSID1, 'callback',...
        @this.tableContextMenu_CompRuns);
    set(this.tableContextMenuSID2, 'callback',...
        @this.tableContextMenu_CompRuns);
    set(this.tableContextMenuCompRunAbsTol, 'callback',...
        @this.tableContextMenu_CompRuns);
    set(this.tableContextMenuCompRunRelTol, 'callback',...
        @this.tableContextMenu_CompRuns);
    set(this.tableContextMenuCompRunSync, 'callback',...
        @this.tableContextMenu_CompRuns);
    set(this.tableContextMenuCompRunInterp, 'callback',...
        @this.tableContextMenu_CompRuns);   
    set(this.tableContextMenuCompRunChannel, 'callback',...
        @this.tableContextMenu_CompRuns);     
                                      
    
    this.tableContextMenuSigSourceCompRuns                                     ...
                                      = uimenu                                 ...
                                     (this.tableContextMenuCompRuns,           ...
                                     'label',                                  ...
                                     SD.mgHighlightSource,                     ...
                                     'Separator', 'on');
                                
                                 
    this.tableContextMenuSigSourceCompRuns1                                    ...
                                      = uimenu                                 ...
                                     (this.tableContextMenuSigSourceCompRuns,  ...
                                     'label',                                  ...
                                     this.sd.mgRun1,                           ...
                                     'callback',                               ...
                                     @this.tableContextMenuCallback_SigSource1);
                                 
    this.tableContextMenuSigSourceCompRuns2                                    ...
                                      = uimenu                                 ...
                                     (this.tableContextMenuSigSourceCompRuns,  ...
                                     'label',                                  ...
                                     this.sd.mgRun2,                           ...
                                     'callback',                               ...
                                     @this.tableContextMenuCallback_SigSource2);
    
    this.tableContextMenuViewDataCompRuns =                         ...
                                    uimenu                          ...
                                    (this.tableContextMenuCompRuns, ...
                                    'label',                        ...
                                    SD.mgExportVarEditor);
    this.tableContextMenuViewDataCompRuns1 =                                ...
                                    uimenu                                  ...
                                    (this.tableContextMenuViewDataCompRuns, ...
                                    'label',                                ...
                                    this.sd.mgRun1,                         ...
                                    'callback',                             ...
                                    @this.tableContextMenuCallback_VarEditor1);
    this.tableContextMenuViewDataCompRuns2 =                                ...
                                    uimenu                                  ...
                                    (this.tableContextMenuViewDataCompRuns, ...
                                    'label',                                ...
                                    this.sd.mgRun2,                         ...
                                    'callback',                             ...
                                    @this.tableContextMenuCallback_VarEditor2);
                                
    this.tableContextMenuPropertiesCompRuns                                            ...
                                       = uimenu                                        ...
                                      (this.tableContextMenuCompRuns,                  ...
                                      'label', 'Properties',                           ...
                                      'Separator', 'on');    
                                  
    this.tableContextMenuPropertiesCompRuns1                                           ...
                                       = uimenu                                        ...
                                      (this.tableContextMenuPropertiesCompRuns,        ...
                                      'label', this.sd.mgRun1,                         ...
                                      'callback',                                      ...
                                      @this.tableContextMenuCallback_SignalProperties1); 
                                  
    this.tableContextMenuPropertiesCompRuns2                                           ...
                                       = uimenu                                        ...
                                      (this.tableContextMenuPropertiesCompRuns,        ...
                                      'label', this.sd.mgRun2,                         ...
                                      'callback',                                      ...
                                      @this.tableContextMenuCallback_SignalProperties2); 
        
