function createUIControls_CompareRunsTab(this)
    % Copyright 2010 The MathWorks, Inc.
    % Creates the compare runs tab uicontrols
    
    % cache geometric constants
    GC = Simulink.sdi.GeoConst;
    
    % add vertical splitter
    this.compareRunsVertSplitter = Simulink.sdi.splitPane(this.TabCompareRuns, ...
                                                          'hori',              ...
                                                           6,                  ...
                                                          [0.5 0.5 0.5],       ...
                                                           0.4,                ...
                                                           GC.mCompareRunsLeft,...
                                                           GC.mOptionWidth+ GC.mOptionHeight);
    % add horizontal splitter                                                       
    this.compareRunsHorSplitter = Simulink.sdi.splitPane                      ...
                                  (this.compareRunsVertSplitter.rightDownPane,...
                                   'vert',                                    ...
                                   6,                                         ...
                                   [0.5 0.5 0.5],                             ...
                                   0.5,                                       ...
                                   GC.mOptionHeight,                          ...
                                   GC.mOptionHeight);
    
    % run 1, run 2 captions
    this.lhsRunCaption = uicontrol('Parent',this.compareRunsVertSplitter.leftUpPane,...
                                   'Style',               'text',                   ...
                                   'Units',               'pixels',                 ...
                                   'HorizontalAlignment', 'left',                   ...
                                   'String',              this.sd.mgRun1);
    this.rhsRunCaption = uicontrol('Parent',this.compareRunsVertSplitter.leftUpPane,...
                                   'Style',               'text',                   ...
                                   'Units',               'pixels',                 ...
                                   'HorizontalAlignment', 'left',                   ...
                                   'String',              this.sd.mgRun2);
    
    % run 1 combobox
   
    this.lhsRunCombo = uicontrol('Parent',this.compareRunsVertSplitter.leftUpPane,...
                                 'Style',               'popupmenu',              ...
                                 'BackGroundColor',     'white',                  ...
                                 'HorizontalAlignment', 'left',                   ...
                                 'Units',               'pixels',                 ...
                                 'String',              {'<empty>'}               ...
                                );
    % run 2 combobox
   
    this.rhsRunCombo = uicontrol('Parent',this.compareRunsVertSplitter.leftUpPane,...
                                 'Style',               'popupmenu',              ...
                                 'BackGroundColor',     'white',                  ...
                                 'HorizontalAlignment', 'left',                   ...
                                 'Units',               'pixels',                 ...
                                 'String',              {'<empty>'}               ...
                                );


    this.compareRuns = uicontrol('Parent', this.compareRunsVertSplitter.leftUpPane, ...
                                 'TooltipString', this.sd.MGCompareRuns,            ...
                                 'String', this.sd.mgCompare, 'style',              ...
                                 'pushbutton');
    
    this.compareRunAdvancePlus = uicontrol('Parent', this.compareRunsVertSplitter.leftUpPane, ...
                                      'TooltipString', this.sd.mgAdvancedOptions,             ...
                                      'String', '+', 'style', 'pushbutton',                   ...
                                      'SelectionHighlight', 'off',                            ...
                                      'Selected', 'off');
                                  
    this.advanceOptions = uicontrol('Parent',this.compareRunsVertSplitter.leftUpPane,...
                                    'Style',               'text',                   ...
                                    'Units',               'pixels',                 ...
                                    'String',              this.sd.mgAdvancedOptions,...
                                    'HorizontalAlignment', 'left',                   ...
                                    'Enable', 'Inactive');
                                 
   
    this.AxesCompareRunsData = axes('Parent',                                    ...
                                    this.compareRunsHorSplitter.rightDownPane);
    this.AxesCompareRunsDiff = axes('Parent',                                  ...
                                    this.compareRunsHorSplitter.leftUpPane);
                                
    % Axes titles and labels
    title(this.AxesCompareRunsData, this.sd.mgSignals);
    title(this.AxesCompareRunsDiff, this.sd.mgDifference);
                                   
    % link axes
    linkaxes([this.AxesCompareRunsData this.AxesCompareRunsDiff], 'x');
                                   
    this.advanceOptionsPanel = uipanel('Parent', this.compareRunsVertSplitter.leftUpPane,...
                                       'BorderWidth', 0, 'Units',  'Pixels',             ...
                                       'vis', 'off');    
                                   
    this.alignByCaption = uicontrol('Parent',this.advanceOptionsPanel,    ...
                                    'Style',               'text',        ...
                                    'Units',               'pixels',      ...
                                    'String',             this.sd.mgAlign);
                            
    this.firstThenByCaption = uicontrol('Parent',this.advanceOptionsPanel,      ...
                                        'Style',               'text',          ...
                                        'Units',               'pixels',        ...
                                        'String',              this.sd.mgThenBy);
                            
    this.secondThenByCaption = uicontrol('Parent',this.advanceOptionsPanel,      ...
                                         'Style',               'text',          ...
                                         'Units',               'pixels',        ...
                                         'String',              this.sd.mgThenBy);
                                     
    alignStrings = {this.sd.mgNone, this.sd.mgPath,...
                    this.sd.IGDataSourceColName, this.sd.mgSID, this.sd.mgSigLabel};
    szAlign = max(size(alignStrings));
                                     
    this.alignByPopUp = javaObjectEDT('com.jidesoft.combobox.ListComboBox');
    this.alignByPopUp.setEditable(false);
    [this.alignByPopUp,...
     this.alignByContainer] = javacomponent(this.alignByPopUp,...
                                           [0 0 1 1],         ... 
                                           this.compareRunsVertSplitter.leftUpPane);
    
    this.firstThenByPopUp = javaObjectEDT('com.jidesoft.combobox.ListComboBox');
    this.firstThenByPopUp.setEditable(false);
    [this.firstThenByPopUp,...
    this.firstThenByContainer] = javacomponent(this.firstThenByPopUp,...
                                           [0 0 1 1],                ...
                                           this.compareRunsVertSplitter.leftUpPane);
   
    this.secondThenByPopUp = javaObjectEDT('com.jidesoft.combobox.ListComboBox');
    this.secondThenByPopUp.setEditable(false);
    [this.secondThenByPopUp,...
    this.secondThenByContainer] = javacomponent(this.secondThenByPopUp,...
                                           [0 0 1 1],                  ...
                                           this.compareRunsVertSplitter.leftUpPane);
                                       
    for i = 1:szAlign
        this.firstThenByPopUp.insertItemAt(alignStrings{i}, i-1);
        this.secondThenByPopUp.insertItemAt(alignStrings{i}, i-1);
        if (i < 5)
            this.alignByPopUp.insertItemAt(alignStrings{i+1}, i-1);
        end
    end
    
    this.alignByPopUp.setSelectedIndex(0);
    this.firstThenByPopUp.setSelectedIndex(0);
    this.secondThenByPopUp.setSelectedIndex(0);
                                       
    set(this.alignByContainer, 'vis', 'off');
    set(this.firstThenByContainer, 'vis', 'off');
    set(this.secondThenByContainer, 'vis', 'off');    

                                  
    %% Create TreeTable
    % Create TreeTableModel
    this.createUIControls_compareRunsTTModel();
    this.compareRunsTT = this.createTreeTable(this.compareRunsVertSplitter.leftUpPane,...
                                              this.compareRunsTTModel);
    % Do not show any tree lines and align test results icon
    this.compareRunsTT.TT.setIndent(0);
    
    this.blkSrcVis1 = true;
    this.blkSrcVis2 = false;
    this.dataSrcVis1 = false;
    this.dataSrcVis2 = false;
    this.sidVis1 = false;
    this.sidVis2 = false;
    this.absTolVis = false;
    this.relTolVis = true;
    this.syncVis = false;
    this.interpVis = false;
    this.channelVis = false;
    
    this.setCallbacks_CompareRuns();
    this.transferStateToScreen_CompareRuns();        
    this.createUIControls_ContextMenuTableHeaderCompareRuns();
    this.createUIControls_tableContextMenuCompRuns();
    this.transferStateToScreen_ContextMenuCompareRuns();       
    this.transferStateToScreen_ColumnVisibleCompareRuns();
    this.setRenderers_CompareRuns();      
    
    %% ResizeFcn
    set(this.compareRunsVertSplitter.leftUpPane,'resizefcn',...
        @this.positionControl_CompareRunLeftPane);
    set(this.compareRunsVertSplitter.rightDownPane,'resizefcn',...
        @this.positionControl_CompareRunRightPane);  
    set(this.compareRunsHorSplitter.rightDownPane,'resizefcn',...
        @this.positionControl_CompareRunRightPane); 
    set(this.compareRunsHorSplitter.leftUpPane,'resizefcn',...
        @this.positionControl_CompareRunRightPane); 
	% order in which the controls are added is important for visual ordering
    this.compareRunsVertSplitter.addDivider();    
    this.compareRunsVertSplitter.addCallbackLeft(@this.positionControls_OptionsButton);
    this.compareRunsVertSplitter.addCallbackRight(@this.positionControls_OptionsButton);
    this.compareRunsHorSplitter.addCallbackLeft(@this.positionControls_OptionsButton);
    this.compareRunsHorSplitter.addCallbackRight(@this.positionControls_OptionsButton);
end

