function this = HistogramInfo(hScopeApp)
% HISTOGRAMINFO Constructor for the HistogramInfo class.

% Copyright 2009 The MathWorks, Inc.
% $Revision: 1.1.6.4 $      $Date: 2010/03/31 18:41:21 $
    
this = scopeextensions.HistogramInfo;

% Initialize DialogBase properties
this.initExt('Data Information', hScopeApp);

this.DataReleasedListener = handle.listener(hScopeApp, 'DataReleased', ...
    @(h, ev) dataReleased(this));

this.SourceNameChangedListener = handle.listener(hScopeApp, 'SourceNameChanged', ...
                                                 @(h, ev) sourceNameChanged(this));
                                             
this.UpdateTitleBarListener = handle.listener(hScopeApp, ...
    'UpdateTitleBarEvent', @(hSrc, ev) sourceNameChanged(this, true));

%------------------------------------------
function dataReleased(this)

set(this, ...
    'SourceType', '', ...
    'SourceLocation', '', ...
    'DataType', '',...
    'AbsMin','',...
    'Min','',...
    'Max','',...
    'Range','',...
    'MinBin',0,...
    'MaxBin',0,...
    'NumZeros','',...
    'Mean','',...
    'StdDev','',...
    'PercentOverflw','',...
    'PercentUnderflw','',...
    'NumSamples',''...
    );

if isa(this.Dialog, 'DAStudio.Dialog')
    this.Dialog.refresh;
end
