function setup_figure(this)
%SETUP_FIGURE   Set up the figure for the SOSVIEWDLG

%   Author(s): J. Schickler
%   Copyright 1988-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.5 $  $Date: 2004/12/26 22:22:18 $

sz = gui_sizes(this);
cbs = dialog_cbs(this);

this.FigureHandle = figure('menubar', 'none', ...
    'Position', [200 200 280 215]*sz.pixf, ...
    'HandleVisibility', 'Off', ...
    'Visible', 'Off', ...
    'Resize', 'Off', ...
    'NumberTitle', 'Off', ...
    'Name', 'SOS View Settings', ...
    'Color', get(0, 'DefaultUIControlBackgroundColor'), ...
    'CloseRequestFcn', cbs.cancel);

% [EOF]
