function hedit = render_spteditmenu(hFig)
%RENDER_SPTEDITMENU Render a Signal Processing Toolbox "Edit" menu.
%   HEDIT = RENDER_SPTEDITMENU(HFIG) creates a "Edit" menu in the second position
%   on a figure whose handle is HFIG and return the handles to all the menu items.

%   Author(s): V.Pellissier
%   Copyright 1988-2005 The MathWorks, Inc.
%   $Revision: 1.2.4.3 $  $Date: 2008/05/31 23:27:41 $ 

strs = {'&Edit', ...
    'F&igure Properties...', ...
    '&Axes Properties...', ...
    'C&urrent Object Properties...'};

cbs = {'', ...
    'domymenu menubar figureprop', ...
    'domymenu menubar axesprop', ...
    'domymenu menubar currentprop'};

tags = {'edit', ...
    'figMenuEditGCF', ...
    'figMenuEditGCA', ...
    'figMenuEditGCO'};

sep = {'off', ...
    'on', ...
    'off', ...
    'off'};

accel = {'', ...
    '', ...
    '', ...
    ''};

% See g268023
if ispc,
    strs = {strs{1},...
        'Copy &Figure', ...
        'Copy &Options...', ...
        strs{2:end}};

    cbs = {cbs{1},...
        'editmenufcn(gcbf,''EditCopyFigure'')', ...
        'preferences(''Figure Copy Template.Copy Options'')', ...
        cbs{2:end}};

    tags = {tags{1},...
        'figMenuEditCopyFigure', ...
        '                           ', ...
        tags{2:end}};

    sep = {sep{1},...
        'off', ...
        'off', ...
        sep{2:end}};

    accel = {accel{1},...
        '', ...
        '', ...
        accel{2:end}};
end


hedit = addmenu(hFig,2,strs,cbs,tags,sep,accel);

% [EOF]
