function initializeTimePanel(h)
% INITIALIZETIMEPANEL initializes the 'Define Time Vector' panel

% Author: Rong Chen 
%  Copyright 1986-2008 The MathWorks, Inc.
%  $Revision: 1.1.6.7 $ $Date: 2008/12/29 02:11:11 $

% -------------------------------------------------------------------------
%% Build time panel
% -------------------------------------------------------------------------
h.DefaultPos.TimePanelDefaultColor=h.DefaultPos.FigureDefaultColor;
if isfield(h.Handles,'PNLtime') && ishghandle(h.Handles.PNLtime)
    delete(h.Handles.PNLtime);
end
h.Handles.PNLtime = uipanel('Parent',h.Figure,...
    'Units','Pixels',...
    'FontSize',9,...
    'FontWeight','bold', ...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'Title',xlate(' Specify time vector '),...
    'Position',[h.DefaultPos.leftoffsetpnl ...
                h.DefaultPos.bottomoffsetTimepnl ...
                h.DefaultPos.widthpnl ...
                h.DefaultPos.heightTimepnl], ...
    'Visible','off'...
);

% create sheet combobox controls whose values are based on the rawdata
huicTXTtimeSheet = uicontextmenu('Parent',h.Figure);
h.Handles.TXTtimeSheet = uicontrol('Parent',h.Handles.PNLtime,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String',xlate('Time-vector source : '),...
    'HorizontalAlignment','Left', ...
    'UIContextMenu',huicTXTtimeSheet,...
    'Position',[h.DefaultPos.TXTtimeSheetleftoffset ...
                h.DefaultPos.TXTtimeSheetbottomoffset ...
                h.DefaultPos.TXTtimeSheetwidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTtimeSheet,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_time_src_for_xls'',''modal'')')

h.Handles.COMBtimeSource = uicontrol('Parent',h.Handles.PNLtime,...
    'style','popupmenu',...
    'Units', 'Pixels',...
    'BackgroundColor',[1 1 1], ...
    'String',[{xlate('current spreadsheet')},{xlate('define it now')},{xlate('MATLAB workspace')}], ...
    'Value',1,...
    'TooltipString','The time vector can be obtained from different sources.  Use this drop-down list the select the type of source and configure the source below.',...
    'Position',[h.DefaultPos.COMBtimeSheetleftoffset ...
                h.DefaultPos.TXTtimeSheetbottomoffset+4 ...
                h.DefaultPos.COMBtimeSheetwidth ...
                h.DefaultPos.heightcomb], ...
    'Callback',{@localSwitchSource h} ...
    );
% create dynamic panels
h.dynamicPanel_CurrentSheet;
h.dynamicPanel_ManualInput;
h.dynamicPanel_Workspace;
if  ~isempty(h.Handles.tsTable)
    % no time or number detected in either the first row or column
    % set column as default and bring up the manual input
    set(h.Handles.COMBdataSample,'Value',1);
    h.TimePanelUpdate('column');
end


% -------------------------------------------------------------------------
%% time vector source selection callbacks
% -------------------------------------------------------------------------
function localSwitchSource(eventSrc, eventData, h)
% callback for the sheet combobox in the time panel
ind = get(eventSrc,'Value');
if ind==3
    % from workspace
    set(h.Handles.PNLtimeCurrentSheet,'Visible','off');
    set(h.Handles.PNLtimeManual,'Visible','off');
    set(h.Handles.PNLtimeWorkspace,'Visible','on');
elseif ind==2
    % manual input
    set(h.Handles.PNLtimeCurrentSheet,'Visible','off');
    set(h.Handles.PNLtimeManual,'Visible','on');
    set(h.Handles.PNLtimeWorkspace,'Visible','off');
elseif ind==1
    % currentsheet
    set(h.Handles.PNLtimeCurrentSheet,'Visible','on');
    set(h.Handles.PNLtimeManual,'Visible','off');
    set(h.Handles.PNLtimeWorkspace,'Visible','off');
end


