function status = isinitialized(nlobj)
%ISINITIALIZED True for initialized TREEPARTITION estimator.
%

% Copyright 2005-2008 The MathWorks, Inc.
% $Revision: 1.1.6.4 $ $Date: 2009/11/09 16:24:12 $

% Author(s): Qinghua Zhang

if isscalar(nlobj)
    param = nlobj.Parameters;
    status = isstruct(param) && ...
        ~(isempty(param.RegressorMean) && ...
        isempty(param.RegressorMinMax) && ...
        isempty(param.OutputOffset) && ...
        isempty(param.SampleLength) && ...
        isempty(param.NoiseVariance)) || ...
        (isstruct(param) && isstruct(param.Tree) && ...
        ~(isempty(param.Tree.TreeLevelPntr) && ...
        isempty(param.Tree.AncestorDescendantPntr) && ...
        isempty(param.Tree.LocalizingVectors) && ...
        isempty(param.Tree.LocalCovMatrix) && ...
        isempty(param.Tree.LocalCovMatrix)));
else
    ctrlMsgUtils.error('Ident:idnlfun:scalarNLRequired','isinitialized')
end

% Oct 2009: removed isempty(param.LinearCoef) && ...

% Oct2009
% FILE END