function SavedData = save(Editor)
% Creates backup of Root Locus Editor settings.

%   Author(s): P. Gahinet
%   Copyright 1986-2006 The MathWorks, Inc.
%   $Revision: 1.9.4.4 $  $Date: 2006/06/20 20:03:19 $

Axes = Editor.Axes;
PlotAxes = getaxes(Axes);
if ~isempty(Editor.GainTargetBlock)
    GainTargetBlock = find(Editor.GainTargetBlock==Editor.LoopData.C);
else
    GainTargetBlock = [];
end
    
SavedData = struct(...
    'Class',class(Editor),...
    'EditedBlock',find(Editor.EditedBlock==Editor.LoopData.C),...
    'GainTargetBlock', GainTargetBlock,...
    'EditedLoop', Editor.EditedLoop,...
    'Constraints',saveconstr(Editor),...
    'Grid',Axes.Grid,...
    'Title',Axes.Title,...
    'TitleStyle',struct(Axes.TitleStyle),...
    'Visible',Editor.Visible,...
    'Xlabel',{Axes.Xlabel},...
    'XlabelStyle',struct(Axes.XlabelStyle),...
    'Xlim',{get(PlotAxes,'Xlim')},...
    'XlimMode',{Axes.XlimMode},...
    'Ylabel',{Axes.Ylabel},...
    'YlabelStyle',struct(Axes.YlabelStyle),...
    'Ylim',{get(PlotAxes,'Ylim')},...
    'YlimMode',{Axes.YlimMode},...
    'LimitStack',Editor.Axes.LimitStack,...
    'AxisEqual',Editor.AxisEqual,...
    'GridOptions',Editor.GridOptions);
