function SavedData = save(Editor)
%SAVE   Creates backup of Nichols Editor settings.

%   Author(s): Bora Eryilmaz
%   Revised:
%   Copyright 1986-2006 The MathWorks, Inc.
%   $Revision: 1.8.4.4 $  $Date: 2006/06/20 20:02:49 $

Axes = Editor.Axes;
PlotAxes = getaxes(Editor.Axes);

if ~isempty(Editor.GainTargetBlock)
    GainTargetBlock = find(Editor.GainTargetBlock==Editor.LoopData.C);
else
    GainTargetBlock = [];
end

SavedData = struct(...
    'Class',class(Editor),...
    'EditedBlock',find(Editor.EditedBlock==Editor.LoopData.C),...
    'GainTargetBlock', GainTargetBlock,...
    'EditedLoop', Editor.EditedLoop,...
    'Constraints',Editor.saveconstr,...
    'Grid',Axes.Grid,...
    'Title',Axes.Title,...
    'TitleStyle',struct(Axes.TitleStyle),...
    'Visible',Editor.Visible,...
    'XlabelStyle',struct(Axes.XlabelStyle),...
    'Xlabel',{Axes.Xlabel},...
    'Xlim',{get(PlotAxes,'Xlim')},...
    'XlimMode',{Axes.XlimMode},...
    'Ylabel',{Axes.Ylabel},...
    'YlabelStyle',struct(Axes.YlabelStyle),...
    'Ylim',{get(PlotAxes,'Ylim')},...
    'YlimMode',{Axes.YlimMode},...
    'MarginVisible',Editor.MarginVisible);
