function examples = getexamples(this)
%GETEXAMPLES   Get the examples.

%   Author(s): J. Schickler
%   Copyright 2005 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2005/06/30 17:38:36 $

examples = {{ ...
    'Design a bandstop FIR Least-squares filter with a weighted stopband.', ...
    'h  = fdesign.bandstop(''N,Fp1,Fst1,Fst2,Fp2'', 30);', ...
    'Hd = design(h, ''firls'');', ...
    '', ...
    '% Weight the stopband more than the passbands.', ...
    'Hd(2) = design(h, ''firls'', ''Wstop'', 20);'....
    '', ...
    '% Compare the two designs.', ...
    'fvtool(Hd)'}};

% [EOF]
