function initialize(this,Axes)
%INITIALIZE  Initialization for @tsCharVarView class

%  Author(s): James G. Owen
%  Copyright 1986-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2005/06/27 23:01:57 $

[s1,s2] = size(Axes(:,:,1)); 
Lines = zeros([s1 s2]);

%% Hittest must be on for characteristic data tip to work
for ct=1:s1*s2
   % Plot dc lines lines
   % RE: Set Z=-10 to make sure dc lines don't obscure response lines
   Lines(ct) = line(NaN,NaN,-10,...
      'Parent',Axes(ct),...
      'Visible','off',...
      'LineStyle',':',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HandleVisibility','off',...
      'Color','k','Marker','diamond');
   VLines(ct) = line(NaN,NaN,-10,...
      'Parent',Axes(ct),...
      'Visible','off',...
      'LineStyle',':',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HandleVisibility','off',...
      'Color','k');
end
this.Lines = handle(Lines);
this.VLines = handle(VLines);
this.LineTips = cell([s1 s2]);