function setup_figure(hObj)
%SETUP_FIGURE Setup the figure for the dfiltwfs dialog

%   Author(s): J. Schickler
%   Copyright 1988-2002 The MathWorks, Inc.
%   $Revision: 1.3 $  $Date: 2002/03/28 19:13:06 $

sz   = dfiltwfsdlg_gui_sizes(hObj);
cbs  = dialog_cbs(hObj);
hFig = figure('Visible', 'Off', ...
    'NumberTitle',      'Off', ...
    'CloseRequestFcn',  cbs.cancel, ...
    'IntegerHandle',    'Off', ...
    'Name',             'Sampling Frequency', ...
    'Resize',           'Off', ...
    'Menubar',          'None', ...
    'HandleVisibility', 'Off', ...
    'Color', get(0, 'DefaultUIControlBackgroundColor'), ...
    'Position', sz.fig);

set(hObj, 'FigureHandle', hFig);

% [EOF]
