function out = covcolordata_struct
% Produce a blank data structure for saving information about 
% coverage highlighting

% Copyright 2004-2005 The MathWorks, Inc.

    out = struct(   'mappedBlks',       [], ...
                    'FGColor',          [], ...
                    'BGColor',          [], ...
                    'systems',          [], ...
                    'screenColors',     [], ...
                    'sfLinkInfo',       []);

