function Extent = extent(Constr,iConstr)
%EXTENT  Returns bounding rectangle [Xmin Xmax Ymin Ymax]

%   Copyright 1986-2004 The MathWorks, Inc.
%   $Revision: 1.1.8.1 $  $Date: 2009/10/16 06:31:21 $

if nargin < 2, iConstr = Constr.SelectedEdge; end
Extent = [...
   min(min(unitconv(Constr.Frequency(iConstr,:),Constr.FrequencyUnits,Constr.getDisplayUnits('XUnits')))), ...
   max(max(unitconv(Constr.Frequency(iConstr,:),Constr.FrequencyUnits,Constr.getDisplayUnits('XUnits')))), ...
   min(min(unitconv(Constr.Magnitude(iConstr,:),Constr.MagnitudeUnits,Constr.getDisplayUnits('YUnits')))), ...
   max(max(unitconv(Constr.Magnitude(iConstr,:),Constr.MagnitudeUnits,Constr.getDisplayUnits('YUnits'))))];