function disp(chan)
%DISP  Object display.

%   Copyright 2008 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2008/10/31 05:54:36 $

% Properties to display (in order)
props = {...
    'ChannelType', ...
    'NumTxAntennas', ...
    'NumRxAntennas', ...
    'InputSamplePeriod', ...
    'DopplerSpectrum', ...
    'MaxDopplerShift', ...
    'PathDelays', ...
    'AvgPathGaindB', ...
    'TxCorrelationMatrix', ...
    'RxCorrelationMatrix', ...
    'KFactor', ...
    'DirectPathDopplerShift', ...
    'DirectPathInitPhase', ...
    'ResetBeforeFiltering', ...
    'NormalizePathGains', ...
    'StorePathGains', ...
    'PathGains', ...
    'ChannelFilterDelay', ...
    'NumSamplesProcessed'};

disp@mimo.BaseClass(chan, props);
