function [DataRunID,    ...
          DataRunIndex] = createRunFromBaseWorkspace(this, RunName, VarNames, varargin)

    % Copyright 2009-2010 The MathWorks, Inc.

    % Get values of variable names
    VarValues = Simulink.sdi.Util.BaseWorkspaceValuesForNames(VarNames);
    
    if isempty(varargin)
        % Create data run
        [DataRunID,    ...
         DataRunIndex] = this.createRunFromNamesAndValues(RunName,  ...
                                                          VarNames, ...
                                                          VarValues);
    else
        % Create data run
        [DataRunID,    ...
         DataRunIndex] = this.createRunFromNamesAndValues(RunName,  ...
                                                          VarNames, ...
                                                          VarValues,...
                                                          varargin{1});        
    end
end