function initializeOptionPanel(h)
% INITIALIZEOPTIONPANEL initializes the Step 3 panel

% Author: Rong Chen 
%  Copyright 1986-2006 The MathWorks, Inc.
%  $Revision: 1.1.6.12 $ $Date: 2009/10/29 15:23:17 $


% -------------------------------------------------------------------------
%% Build timeseries naming option control and its contents
% -------------------------------------------------------------------------
h.DefaultPos.OptionPanelDefaultColor=h.DefaultPos.FigureDefaultColor;
h.Handles.PNLoption = uibuttongroup('Parent',h.Figure, ...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'SelectionChangeFcn',{@localRadio,h}, ...
    'Position',[h.DefaultPos.leftoffsetDynamicPnl ...
                h.DefaultPos.buttomoffsetDynamicPnl ...
                h.DefaultPos.widthDynamicPnl ...
                h.DefaultPos.heightDynamicPnl], ...
    'Visible','off' ...
    );

huicRADIOsingleNEW = uicontextmenu('Parent',h.Figure);
h.Handles.RADIOsingleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','radiobutton',...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'String',xlate(' Create a new time series with the name : '), ...
    'UIContextMenu',huicRADIOsingleNEW,...
    'Position',[h.DefaultPos.RADIOoptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleNew ...
                h.DefaultPos.RADIOoptionwidth ...
                h.DefaultPos.heightradio] ...
    );
uimenu(huicRADIOsingleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_create_one_ts'',''modal'')')

h.Handles.EDTsingleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','edit', ...
    'Units','Pixels', ...
    'BackgroundColor',[1 1 1], ...
    'String','', ...
    'TooltipString',xlate('Key in the name of the time series object to be imported.'), ...
    'HorizontalAlignment','Left', ...
    'Position',[h.DefaultPos.EDToptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleNew-2 ...
                h.DefaultPos.EDToptionwidth ...
                h.DefaultPos.heightedt] ...
    );

huicRADIOmultipleNEW = uicontextmenu('Parent',h.Figure);
h.Handles.RADIOmultipleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','radiobutton',...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'String',xlate(' Create several time series using : '), ...
    'UIContextMenu',huicRADIOmultipleNEW,...
    'Position',[h.DefaultPos.RADIOoptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_multipleNew ...
                h.DefaultPos.RADIOoptionwidth ...
                h.DefaultPos.heightradio] ...
    );
uimenu(huicRADIOmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_create_several_ts'',''modal'')')

h.Handles.COMBmultipleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','popupmenu', ...
    'Units','Pixels', ...
    'String', {xlate('names in data source') xlate('common name + number')}, ...
    'Value',1, ...
    'TooltipString',xlate('If a row/column contains variable names and you want to use them for the time series objects, select the first drop-down menu item, otherwise, select the second menu item.'), ...
    'Position',[h.DefaultPos.EDToptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_multipleNew ...
                h.DefaultPos.EDToptionwidth ...
                h.DefaultPos.heighttxt], ...
    'Callback',{@localSwitchMultiple h} ...
    );
if ~ismac
   set(h.Handles.COMBmultipleNEW,'BackgroundColor',[1 1 1]);
end

huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
h.Handles.TXTmultipleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','text',...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'String',xlate(' Specify row : '), ... %jgo
    'HorizontalAlignment','Left', ...
    'UIContextMenu',huicTXTmultipleNEW,...
    'Position',[h.DefaultPos.EDToptionleftoffset+h.DefaultPos.EDToptionwidth+h.DefaultPos.TXToptionmultipleleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_multipleNew-4 ...
                h.DefaultPos.TXToptionmultiplewidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')

h.Handles.EDTmultipleNEW = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','edit', ...
    'Units','Pixels', ...
    'BackgroundColor',[1 1 1], ...
    'String','', ...
    'TooltipString',xlate('Key in the row number/column letter. Or specify the common part of the names for the time series objects.'),...
    'HorizontalAlignment','Left', ...
    'Position',[h.DefaultPos.EDToptionleftoffset+...
                h.DefaultPos.EDToptionwidth+5+h.DefaultPos.TXToptionmultiplewidth+...%40jgo
                h.DefaultPos.separation ...
                h.DefaultPos.RADIOoptionbottomoffset_multipleNew-2 ...
                h.DefaultPos.EDToptionmultiplewidth ...
                h.DefaultPos.heightedt] ...
    );

huicRADIOsingleINSERT = uicontextmenu('Parent',h.Figure);
h.Handles.RADIOsingleINSERT = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','radiobutton',...
    'Units','Pixels', ...
    'BackgroundColor',h.DefaultPos.OptionPanelDefaultColor, ...
    'String',xlate(' Append data to an existing time series : '), ...
    'UIContextMenu',huicRADIOsingleINSERT,...
    'Position',[h.DefaultPos.RADIOoptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleINSERT ...
                h.DefaultPos.RADIOoptionwidth ...
                h.DefaultPos.heightradio] ...
    );
uimenu(huicRADIOsingleINSERT,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_append_data_to_ts'',''modal'')')

h.Handles.COMBsingleINSERT = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','popupmenu', ...
    'Units','Pixels', ...
    'String',{''},...
    'TooltipString',xlate('Select a time series object from the drop-down list and insert selected data samples'),...
    'Position',[h.DefaultPos.EDToptionleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleINSERT ...
                h.DefaultPos.EDToptionwidth ...
                h.DefaultPos.heighttxt] ...
);
if ~ismac
   set(h.Handles.COMBsingleINSERT,'BackgroundColor',[1 1 1]);
end
    
%populate combobox with current timeseries objects in the base workspace
localRefresh([], [], h);
huicBTNRefresh = uicontextmenu('Parent',h.Figure);
h.Handles.BTNRefresh = uicontrol('Parent',h.Handles.PNLoption, ...
    'style','pushbutton', ...
    'Units','Pixels', ...
    'String',xlate('Refresh List'),...
    'UIContextMenu',huicBTNRefresh,...
    'Position',[h.DefaultPos.EDToptionleftoffset+h.DefaultPos.EDToptionwidth+h.DefaultPos.TXToptionmultipleleftoffset ...
                h.DefaultPos.RADIOoptionbottomoffset_singleINSERT-5 ...
                120 ...
                h.DefaultPos.heightbtn], ...
    'Callback',{@localRefresh h}, ...
    'Tag', 'BTNrefresh');
uimenu(huicBTNRefresh,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_refresh_ts_list'',''modal'')')

% initialize radiobuttons
set(h.Handles.PNLoption,'SelectedObject',h.Handles.RADIOsingleNEW);
set(h.Handles.COMBmultipleNEW,'Enable','off');
set(h.Handles.EDTmultipleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
set(h.Handles.COMBsingleINSERT,'Enable','off');
set(h.Handles.BTNRefresh,'Enable','off');


function localRefresh(eventSrc, eventData, h)
tsgui=tsguis.tsviewer;
all_childnodes = tsgui.Tsnode.getChildren;
alltsobjects={};
for i=1:length(all_childnodes)
    if isa(all_childnodes(i),'tsguis.tsnode')
        alltsobjects{end+1} = all_childnodes(i).Timeseries;
    end
end
strCell={};
for i=1:length(alltsobjects)
    strCell=[strCell {alltsobjects{i}.Name}];
end
if isempty(strCell)
    strCell={''};
end
set(h.Handles.COMBsingleINSERT,'String', strCell,'Value',1);


function localRadio(eventSrc, eventData, h)
% callback for the radiobutton group
if get(eventSrc,'SelectedObject')==h.Handles.RADIOsingleNEW
    % single new
    set(h.Handles.EDTsingleNEW,'Enable','on','BackgroundColor',[1 1 1]);
    set(h.Handles.COMBmultipleNEW,'Enable','off');
    set(h.Handles.EDTmultipleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
    set(h.Handles.COMBsingleINSERT,'Enable','off');
    set(h.Handles.BTNRefresh,'Enable','off');
elseif get(eventSrc,'SelectedObject')==h.Handles.RADIOmultipleNEW
    set(h.Handles.EDTsingleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
    set(h.Handles.COMBmultipleNEW,'Enable','on');
    set(h.Handles.EDTmultipleNEW,'Enable','on','BackgroundColor',[1 1 1]);
    set(h.Handles.COMBsingleINSERT,'Enable','off');
    set(h.Handles.BTNRefresh,'Enable','off');
else
    set(h.Handles.EDTsingleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
    set(h.Handles.COMBmultipleNEW,'Enable','off');
    set(h.Handles.EDTmultipleNEW,'Enable','off','BackgroundColor',h.DefaultPos.OptionPanelDefaultColor);
    set(h.Handles.COMBsingleINSERT,'Enable','on');
    set(h.Handles.BTNRefresh,'Enable','on');
end


function localSwitchMultiple(eventSrc, eventData, h)

source = get(h.Handles.COMBsource,'Value');
if get(h.Handles.COMBmultipleNEW,'Value')==1
    % use a row or column as name
    if source==1
        % excel
        if get(h.Handles.exceldlg.Handles.COMBdataSample,'Value')==1
            % a sample is a row
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',xlate('Specify row : '),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        else
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_name_ts_from_column_xls'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',xlate('Specify column : '),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','A');
        end
    elseif source==2
        % text
        if get(h.Handles.csvdlg.Handles.COMBdataSample,'Value')==1
            % a sample is a row
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',xlate('Specify row : '),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        else
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_name_ts_from_column_xls'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',xlate('Specify column : '),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','A');
        end
    elseif source==3
        % mat
        if get(h.Handles.matdlg.Handles.COMBdataSample,'Value')==1
            % a sample is a row
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',xlate('Specify row : '),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        else
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_name_ts_from_column_mat'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',xlate('Specify column : '),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        end
    elseif source==4
        % workspace
        if get(h.Handles.workspacedlg.Handles.COMBdataSample,'Value')==1
            % a sample is a row
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_name_ts_from_row'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',xlate('Specify row : '),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        else
            huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
            uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_name_ts_from_column_mat'',''modal'')')
            set(h.Handles.TXTmultipleNEW,'String',xlate('Specify column : '),'UIContextMenu',huicTXTmultipleNEW);
            set(h.Handles.EDTmultipleNEW,'String','1');
        end
    end
else
    huicTXTmultipleNEW = uicontextmenu('Parent',h.Figure);
    uimenu(huicTXTmultipleNEW,'Label','What''s This','Callback','tsDispatchHelp(''its_wiz_common_name'',''modal'')')
    set(h.Handles.TXTmultipleNEW,'String',xlate('Common name : '),'UIContextMenu',huicTXTmultipleNEW);
    if source==1
        % excel
        if ~isempty(h.Handles.exceldlg.Handles.ActiveX)
            set(h.Handles.EDTmultipleNEW,'String',h.Handles.exceldlg.Handles.ActiveX.ActiveSheet.Name);
        else
            strCell=get(h.Handles.COMBdataSheet,'String');
            set(h.Handles.EDTmultipleNEW,'String',strCell{get(h.Handles.COMBdataSheet,'Value')});
        end
    elseif source==3
        % mat
        set(h.Handles.EDTmultipleNEW,'String',h.Handles.matdlg.IOData.SelectedVariableInfo.varname);
    elseif source==4
        % workspace
        set(h.Handles.EDTmultipleNEW,'String',h.Handles.workspacedlg.IOData.SelectedVariableInfo.varname);
    end
end