function issueAnalyzeError(~, errorID, failedMeas)
%issueAnalyzeError Issue a standard error when analyze fails

%   @commscope/@eyemeasurements
%
%   Copyright 2009 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2009/11/13 04:14:20 $

error(errorID, ['The ANALYZE '...
    'method cannot determine %s. Check ' ...
    'measurement setup values in the MeasurementsSetup ' ...
    'property. Also, the collected data may ' ...
    'not be valid. See documentation for description of valid eye ' ...
    'diagrams.'], failedMeas);
