function setdefaults(Editor,Prefs,AxesTemplate)
%SETDEFAULTS  Initializes graphics with SISO Tool global defaults.

%   Author(s): P. Gahinet
%   Copyright 1986-2003 The MathWorks, Inc.
%   $Revision: 1.8.4.2 $ $Date: 2005/12/22 17:43:06 $

% Label and line style defaults
Editor.LabelColor = Prefs.AxesForegroundColor;
Editor.LineStyle = Prefs.LineStyle;

% Axes style
set(AxesTemplate,...
   'XColor',Editor.LabelColor,...
   'YColor',Editor.LabelColor)

% Title style
% RE: Interpreter=none so that foo_C displays correctly
set(get(AxesTemplate,'Title'),...
   'Interpreter','none',...
   'Color',Editor.LabelColor,...
   'FontAngle',Prefs.TitleFontAngle,...
   'FontSize',Prefs.TitleFontSize,...
   'FontWeight',Prefs.TitleFontWeight)

% Label style
set([get(AxesTemplate,'Xlabel');get(AxesTemplate,'Ylabel')],...
   'Color',Editor.LabelColor,...
   'FontAngle',Prefs.XYLabelsFontAngle,...
   'FontSize',Prefs.XYLabelsFontSize,...
   'FontWeight',Prefs.XYLabelsFontWeight)



