function GetSystemTargetFile(h)
%   GETSTSTEMTARGETFILE  Get the system target file
%   Note: It's not recommended to be overloaded in subclass.

%   Copyright 2002-2010 The MathWorks, Inc.
%   $Revision: 1.1.6.14 $  $Date: 2010/05/20 02:54:03 $
  
  [nu, gSet] = rtwprivate('getSTFInfo',h.ModelName,...
                          'forceread',...
                          true,...
                          'noTLCSettings',...
                          true,...
                          'ModelReferenceTargetType',...
                          h.MdlRefBuildArgs.ModelReferenceTargetType);

  h.SystemTargetFilename = gSet.SystemTargetFile;
  
  % Load rtw hook MATLAB program if it exists
  h.MakeRTWHookMFile = rtwprivate('rtw_hook_name',...
                                  h.SystemTargetFilename,...
                                  'make_rtw');
