function examples = getexamples(this)
%GETEXAMPLES   Get the examples.

%   Author(s): J. Schickler
%   Copyright 2005 The MathWorks, Inc.
%   $Revision: 1.1.6.4 $  $Date: 2007/10/23 18:53:49 $

examples = {{ ...
    'Compare passband and stopband MatchExactly.', ...
    'h     = fdesign.bandstop(''Fp1,Fst1,Fst2,Fp2,Ap1,Ast,Ap2'');', ...
    'Hd    = design(h, ''cheby2'', ''MatchExactly'', ''passband'');', ...
    'Hd(2) = design(h, ''cheby2'', ''MatchExactly'', ''stopband'');', ...
    '', ...
    '% Compare the passband edges in FVTool.', ...
    'fvtool(Hd);', ...
    'axis([.44 .56 -61 -59]);'}};

% [EOF]
