function setup_figure(hEH)
%SETUP_FIGURE Set up the figure for the exportheader object

%   Author(s): J. Schickler
%   Copyright 1988-2004 The MathWorks, Inc.
%   $Revision: 1.6.4.2 $  $Date: 2004/12/26 22:21:19 $

sz  = exportheader_gui_sizes(hEH);
cbs = dialog_cbs(hEH);

hFig = figure(...
    'CloseRequestFcn',  cbs.cancel, ...
    'Color',            get(0,'defaultuicontrolbackgroundcolor'), ...
    'HandleVisibility', 'Callback', ...
    'IntegerHandle',    'Off', ...
    'Menubar',          'None', ...
    'Name',             gettitle(hEH), ...
    'NumberTitle',      'Off', ...
    'Position',         sz.fig, ...
    'Resize',           'Off', ...
    'Visible',          hEH.Visible);

set(hEH, 'Parent', hFig);

% [EOF]
