function h=scribeuaxes(varargin)
%SCRIBEUAXES creates the scribe underlay axes object
%  H=scribe.SCRIBEUAXES creates a scribeuaxes instance
%
%  See also PLOTEDIT

%   Copyright 1984-2005 The MathWorks, Inc.

if nargin>0 && ischar(varargin{1})
    pvpairs = varargin;
elseif nargin>0 && isscalar(varargin{1}) && ...
        ishandle(varargin{1}) && isa(handle(varargin{1}),'hg.figure')
    pvpairs = {'Parent', varargin{1}};
else
    pvpairs = {'Parent', gcf};
end
h = scribe.scribeuaxes('Tag','scribeUnderlay',pvpairs{:});

set(h,'Position',[0,0,1,1], ...
    'Visible','off', ...
    'HandleVisibility','off', ...
    'XLimMode','manual', ...
    'YLimMode','manual', ...
    'ZLimMode','manual', ...
    'NextPlot','add', ...
    'Xlimmode','manual',...
    'Ylimmode','manual',...
    'Zlimmode','manual',...
    'Climmode','manual',...
    'Alimmode','manual');
hasbehavior(double(h),'zoom',false);
hasbehavior(double(h),'rotate',false);
setappdata(double(h),'ScribeGroup',h);
setappdata(double(h),'scribeobject','on');
setappdata(ancestor(h,'figure'),'Scribe_ScribeUnderlay',double(h));