function renderPre(h,hPropParent)
%renderPre Rendering tasks performed prior to rendering children.
%  Base implementation for uigroup class.

% Copyright 2004-2009 The MathWorks, Inc.
% $Revision: 1.1.6.2 $ $Date: 2009/03/09 19:34:08 $
if isempty(h.GraphicalParent) || ~ishghandle(h.GraphicalParent)
    % See if hPropParent type is useful for the buttongroup:
    %    empty/invalid: create a new or use existing figure,
    %           then see below
    %    figure, others: create new toolbar under figure
    %
    % An error can be generated by the widget function if an invalid
    % parent is used. A uitoolbar is the most common parent here.
    %
    if isempty(hPropParent)
        hPropParent = gcf;
    end
    h.GraphicalParent = hPropParent;
end

% [EOF]
