/* Copyright 2008-2009 The MathWorks, Inc. */
/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Mon Nov 10 11:31:14 2008
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif
#include "sfbuilder_bus_bus.h"

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void sfbuilder_bus_Outputs_wrapper(const SFB_COUNTERBUS *u0,
                          const int32_T *u1,
                          SFB_COUNTERBUS *y0,
                          int32_T *y1)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
int32_T limit;
  boolean_T inputGElower;
  
  /* limit is sum of SFB_SIGNALBUS.input and the second input(u1) */
  limit = u0->inputsignal.input + *u1;
  
  /* check if SFB_SIGNALBUS.limit is >= LIMITBUS.lower_saturation_limit */
  inputGElower = (limit >= u0->limits.lower_saturation_limit);

  if((u0->limits.upper_saturation_limit >= limit) && inputGElower) {
      *y1 = limit;
  } 
  else {
      if(inputGElower) {
          limit = u0->limits.upper_saturation_limit;
      } else {
          limit = u0->limits.lower_saturation_limit;
      }
      *y1 = limit;
  }

  y0->inputsignal.input = *y1;
  y0->limits = u0->limits;
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
