function clean_code_gen_dir(dirName,objectsOnly)

   if(nargin<2)
      objectsOnly = 0;
   end
         
   [prevWarnMsg, prevWarnId] = lastwarn;
   warnFlag = warning;
   warning('off');  %#ok<WNOFF>
   currDir = pwd;
   try
       cd(dirName);
       if(~isempty(strfind(pwd,'sfprj')))
          % simple sanity check that this is a project directory.
          if ~objectsOnly
             sf('Private', 'sf_delete_file', '*.*');
             infoMatDir = fullfile(pwd,'..','info');
             iReportDir = fullfile(pwd,'..','html');
             if exist(infoMatDir,'dir') 
                 cd(infoMatDir);
                 sf('Private', 'sf_delete_file', '*.*');
             end
             if sf('Feature', 'EML InferenceReport')
                 if exist(iReportDir,'dir')
                     cd(iReportDir);
                     dirs = dir(iReportDir);
                     for i=1:numel(dirs)
                         dirname = dirs(i).name;
                         if dirs(i).isdir && dirname(1) == 'c'
                             rmdir(dirname, 's');
                         end
                     end
                 end
             end
          else
            if(ispc)
               sf('Private', 'sf_delete_file', '*.obj');
            else
               sf('Private', 'sf_delete_file', '*.o');
            end               
          end
       else
         disp('Skipping clean target directory as it does not appear to be an autogenerated project dir');
       end
   catch ME %#ok<NASGU>
   end
   cd(currDir);
   lastwarn(prevWarnMsg, prevWarnId);
   warning(warnFlag);
  
   
