function [hb,hl] = dynamicBar(hax,width,offset,xrange,rgb)
% Create default dynamic bargraph plot.
% hb = dynamicBar(...) creates a patch for a bar plot.
% [hb,hl] = dynamicBar(...) also creates a line for each bar.
% Creates all-zero data to initialize bar and line.

%   Copyright 2010 The MathWorks, Inc.
%   $Revision: 1.1.6.1.2.1 $     $Date: 2010/07/06 14:39:08 $

[xp,zp,xl,zl,cp] = embedded.ntxui.NTX.createXBarData(xrange,width,offset,rgb);

% Create histogram bars as a single patch
%
% xxx Bug: When erasemode is specified, cdata is NOT interpreted correctly
%    'erasemode','background', ...
yp = ones(size(xp));
hb = patch('parent',hax, ...
           'facecolor','flat', ...
           'edgecolor','k', ...
           'xdata', xp, ...
           'ydata', yp, ...
           'zdata', zp, ...
           'cdata', cp);

if nargout>1
    % Create sign line
    yl = zeros(size(xl))+0.5;
    hl = line('parent',hax, ...
              'tag','SignLine',...
              'color','w', ...
              'xdata',xl, ...
              'ydata',yl, ...
              'zdata',zl);
end
