function enableMouse(ntx)
% Requires a figure handle, not a uipanel

%   Copyright 2010 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $     $Date: 2010/03/31 18:21:08 $

set(ntx.hFig, ...
    'WindowButtonUpFcn','', ...
    'WindowScrollWheelFcn',@(h,e)wheelMove(ntx,e), ...
    'WindowButtonMotionFcn',@(h,e)mouseMove(ntx), ...
    'WindowButtonDownFcn',@(h,e)mouseDown(ntx));
