function h = event(name,time,varargin)
%TSDATA.EVENT  Construct event object for timeseries object.
%
%    E = TSDATA.EVENT(Name,Time) creates an event object with the specified 
%    name that occurs at the time Time. Time can either be a real value or
%    a date string.
%
%    E = TSDATA.EVENT(Name,Time,'Datenum') uses 'Datenum' to indicate that
%    the Time value is a serial date number generated by the datenum function.
%    The Time value is converted to a date string after the event is
%    created.

% Copyright 2005-2007 The MathWorks, Inc.

h = tsdata.event;
if nargin==0
  return
end

if nargin>=1
  % Set the name
  if ischar(name)
      h.Name = name;
  else
    error('event:event:misname',...
        'The first argument of the event constructor must be the name of the event.')
  end
end

if nargin>=2
     % Numeric value
      if isnumeric(time) && length(time)==1
          % If there is a third input argument called 'datenum', treat the
          % numeric value as a datenum value supported by MATLAB
          if nargin == 3
              if strcmpi(varargin{1},'datenum')
                  h.Time = 0;
                  h.Units = 'days';
                  try
                      h.StartDate = datestr(time,0);
                  catch
                      error('event:event:datenum',...
                            'The second argument of the event constructor must be a valid datenum value.')
                  end
              else
                    h.Time = time;
              end
          % Otherwise, treat the numeirc value as a relative time point
          else
              h.Time = time;
              h.Units = 'seconds';
          end
      % string which represent an absolute date
      elseif ischar(time)
         try 
              Time = datenum(time);
         catch
             error('event:event:abstime',...
                 'The second argument of the event constructor must be a valid date string.')
         end
         h.Time = 0;
         h.Units = 'days';
         h.StartDate = datestr(Time,0);
     else
         error('event:event:abstime',...
             'The second argument of the event constructor must be entered as a valid datenum value, an absolute date string, or a real number.')
     end
end

