function cstructname(~,~,~)
%EML.CSTRUCTNAME Assign a C-friendly name to a structure type in the generated code. 
% 
%  Usage:
% 
%  EML.CSTRUCTNAME(VAR, 'NAME') 
%    Declares structure type variable VAR to use name NAME. Helps maintain 
%    consistency between C code generated by Embedded MATLAB and custom C code.
%
%  EML.CSTRUCTNAME(VAR, 'NAME', 'extern')
%    Declares externally-defined structure type variable VAR to use name NAME. 
%    Embedded MATLAB does not generate the definition of the structure type, 
%    so it must be provided in a custom include file.
% 
%  Example:
% 
%    C code:
% 
%      typedef struct { double x; double y; } MyPointType;
%      void foo(const MyPointType* ptr);
% 
%    MATLAB code:
% 
%      % Declare a MATLAB structure.
%      var.x = 1;
%      var.y = 2;
%
%      % Instruct Embedded MATLAB to assign the name MyPointType to the type of var.         
%      eml.cstructname(var, 'MyPointType', 'extern');
% 
%      % The type of var matches foo's signature.
%      eml.ceval('foo', eml.rref(var));
% 
%  eml.cstructname cannot be applied to global variables. 
%
%  This function has no effect in MATLAB; it applies to Embedded MATLAB only.

%   Copyright 2006-2010 The MathWorks, Inc.
