function initAxisSettings(ax,opts)
%

% INITAXISSETTINGS initializes the options for the axis AX with options
% OPTS. This utility is used by plotting commands such as simView and
% simCompare.

%  Author(s): Erman Korkut 24-Mar-2009
%  Revised: 
%   Copyright 1986-2009 The MathWorks, Inc.
% $Revision: 1.1.8.1 $ $Date: 2009/08/08 01:18:41 $

% The following code originated from toolbox\control\ctrlguis\ltiplot.m
set(ax,...
    'XGrid',      opts.Grid,...
    'YGrid',      opts.Grid,...
    'XColor',     opts.TickLabel.Color,...
    'YColor',     opts.TickLabel.Color,...
    'FontSize',   opts.TickLabel.FontSize,...
    'FontWeight', opts.TickLabel.FontWeight,...
    'FontAngle',  opts.TickLabel.FontAngle,...
    'Selected',   'off')
set(get(ax,'Title'),...
    'FontSize',  opts.Title.FontSize,...
    'FontWeight',opts.Title.FontWeight,...
    'FontAngle', opts.Title.FontAngle)
set(get(ax,'XLabel'),...
    'Color',     opts.XLabel.Color,...
    'FontSize',  opts.XLabel.FontSize,...
    'FontWeight',opts.XLabel.FontWeight,...
    'FontAngle', opts.XLabel.FontAngle)
set(get(ax,'YLabel'),...
    'Color',     opts.YLabel.Color,...
    'FontSize',  opts.YLabel.FontSize,...
    'FontWeight',opts.YLabel.FontWeight,...
    'FontAngle', opts.YLabel.FontAngle)
end
