%#eml
function hdlfm = hdlfimath
% Return fimath settings suitable for HDL code generation.
% This function can be used in an Embedded MATLAB block for specifying
% fimath of a fixed point operand.

% Use sum and product FullPrecision option for better HDL code generation
eml_transient;
hdlfm = fimath(...
    'RoundMode',            'floor', ...
    'OverflowMode',         'wrap', ...
    'ProductMode',          'FullPrecision', ...
    'MaxProductWordLength', 128, ...
    'SumMode',              'FullPrecision', ...
    'MaxSumWordLength',     128);

%   Copyright 2007-2009 The MathWorks, Inc.
