function dynamicPanel_ManualInput(h)
% DYNAMICPANEL_MANUALINPUT initializes dynamic panel

% Author: Rong Chen 
%  Copyright 1986-2005 The MathWorks, Inc.
%  $Revision: 1.1.6.8 $ $Date: 2006/12/20 07:18:56 $

h.Handles.PNLtimeManual = uipanel('Parent',h.Handles.PNLtime,...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'BorderType','none',...
    'Position',[5 ...
                5 ...
                h.DefaultPos.widthpnl-10 ...
                h.DefaultPos.TXTtimeSheetbottomoffset-h.DefaultPos.separation-5], ...
    'Visible','off' ...                
    );

% create sheet combobox controls whose values are based on the rawdata
huicTXTuseFormat = uicontextmenu('Parent',h.Figure);
h.Handles.TXTuseFormat = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'HorizontalAlignment','Right', ...
    'String',xlate('Use : '), ...
    'UIContextMenu',huicTXTuseFormat,...
    'Position',[h.DefaultPos.TXTtimeIndexleftoffset ...
                h.DefaultPos.TXTtimeIndexbottomoffset ...
                h.DefaultPos.TXTtimeIndexwidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTuseFormat,'Label','What''s This','Callback','tsDispatchHelp(''its_use_time_format'',''modal'')')

h.Handles.COMBuseFormat = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','popupmenu',...
    'Units', 'Pixels',...
    'String',[{xlate('Date String')};{xlate('Numerical Time')}], ...
    'Value',2, ...
    'Position',[h.DefaultPos.COMBtimeIndexleftoffset ...
                h.DefaultPos.TXTtimeIndexbottomoffset+4 ...
                h.DefaultPos.COMBtimeIndexwidth ...
                h.DefaultPos.heightcomb], ...
    'Callback',{@localSwitchUse h} ...
    );

if ~ismac
   set(h.Handles.COMBuseFormat,'BackgroundColor',[1 1 1]);
end

h.Handles.COMBtimeManualFormat = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','popupmenu',...
    'Units', 'Pixels',...
    'String',{'weeks', 'days', 'hours', 'minutes', ...
        'seconds', 'milliseconds', 'microseconds', 'nanoseconds'}, ...
    'Value',5, ...
    'Position',[h.DefaultPos.COMBtimeSheetFormatleftoffset ...
                h.DefaultPos.TXTtimeSheetFormatbottomoffset+4 ...
                h.DefaultPos.COMBtimeSheetFormatwidth ...
                h.DefaultPos.heightcomb], ...
    'Callback',{@localSwitchFormat h} ...
    );

% start, end, interval, format
huicTXTtimeManualStart = uicontextmenu('Parent',h.Figure);
h.Handles.TXTtimeManualStart = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String',xlate('Start Time : '),...
    'HorizontalAlignment','Right', ...
    'UIContextMenu',huicTXTtimeManualStart,...
    'Position',[h.DefaultPos.TXTtimeSheetStartleftoffset ...
                h.DefaultPos.TXTtimeSheetStartbottomoffset ...
                h.DefaultPos.TXTtimeSheetStartwidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTtimeManualStart,'Label','What''s This','Callback','tsDispatchHelp(''start_time_enter'',''modal'')')

h.Handles.EDTtimeManualStart = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','edit', ...
    'Units','Pixels',...
    'BackgroundColor',[1 1 1],...
    'String',' ',...
    'HorizontalAlignment','Left',...
    'Position',[h.DefaultPos.EDTtimeSheetStartleftoffset ...
                h.DefaultPos.TXTtimeSheetStartbottomoffset+2 ...
                h.DefaultPos.EDTtimeSheetStartwidth ...
                h.DefaultPos.heightedt], ...
    'Callback',{@localSetStartTime h} ...
    );

huicTXTtimeManualEnd = uicontextmenu('Parent',h.Figure);
h.Handles.TXTtimeManualEnd = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String',xlate('Samples : '),...
    'HorizontalAlignment','Right', ...
    'UIContextMenu',huicTXTtimeManualEnd,...
    'Position',[h.DefaultPos.TXTtimeSheetEndleftoffset ...
                h.DefaultPos.TXTtimeSheetEndbottomoffset ...
                h.DefaultPos.TXTtimeSheetEndwidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTtimeManualEnd,'Label','What''s This','Callback','tsDispatchHelp(''number_samples_readonly'',''modal'')')

h.Handles.EDTtimeManualEnd = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','edit', ...
    'Units','Pixels',...
    'BackgroundColor',[1 1 1],...
    'String',' ',...
    'HorizontalAlignment','Left',...
    'Position',[h.DefaultPos.EDTtimeSheetEndleftoffset ...
                h.DefaultPos.TXTtimeSheetEndbottomoffset+2 ...
                h.DefaultPos.EDTtimeManualEndwidth ...
                h.DefaultPos.heightedt], ...
    'Enable','off' ...
    );

huicTXTtimeManualInterval = uicontextmenu('Parent',h.Figure);
h.Handles.TXTtimeManualInterval = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String',xlate('Interval : '),...
    'HorizontalAlignment','Right', ...
    'UIContextMenu',huicTXTtimeManualInterval,...
    'Position',[h.DefaultPos.TXTtimeManualIntervalleftoffset ...
                h.DefaultPos.TXTtimeSheetIntervalbottomoffset ...
                h.DefaultPos.TXTtimeManualIntervalwidth ...
                h.DefaultPos.heighttxt] ...
    );
uimenu(huicTXTtimeManualInterval,'Label','What''s This','Callback','tsDispatchHelp(''time_interval'',''modal'')')

h.Handles.EDTtimeManualInterval = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','edit', ...
    'Units','Pixels',...
    'BackgroundColor',[1 1 1],...
    'String',' ',...
    'HorizontalAlignment','Left',...
    'Position',[h.DefaultPos.EDTtimeManualIntervalleftoffset ...
                h.DefaultPos.TXTtimeSheetIntervalbottomoffset+2 ...
                h.DefaultPos.EDTtimeSheetIntervalwidth ...
                h.DefaultPos.heightedt], ...
    'Callback',{@localSetInterval h} ...
    );
h.Handles.TXTtimeManualIntervalUnit = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'String','seconds',...
    'HorizontalAlignment','Left', ...
    'Position',[h.DefaultPos.UNITtimeSheetIntervalleftoffset ...
                h.DefaultPos.TXTtimeSheetIntervalbottomoffset ...
                h.DefaultPos.UNITtimeSheetIntervalwidth ...
                h.DefaultPos.heighttxt], ...
    'Visible','off' ...                
    );
h.Handles.TXTtimeManualFormat = uicontrol('Parent',h.Handles.PNLtimeManual,...
    'style','text', ...
    'Units','Pixels',...
    'BackgroundColor',h.DefaultPos.TimePanelDefaultColor,...
    'HorizontalAlignment','Right', ...
    'String',xlate('Units : '), ...
    'Position',[h.DefaultPos.TXTtimeSheetFormatleftoffset ...
                h.DefaultPos.TXTtimeSheetFormatbottomoffset ...
                h.DefaultPos.TXTtimeSheetFormatwidth ...
                h.DefaultPos.heighttxt] ...
    );

if ~ismac
   set(h.Handles.COMBtimeManualFormat,'BackgroundColor',[1 1 1]);
end

function localSwitchUse(eventSrc, eventData, h)
%% Callback for the absolute/relative time format combo

if get(h.Handles.COMBuseFormat,'Value')==1
    % Set the contents of the format combo to be absolute time formats
    set(h.Handles.TXTtimeManualFormat,'String',xlate('Format : '))
    set(h.Handles.COMBtimeManualFormat,'String',h.IOData.formatcell.matlabFormatString,'Value',1)
    % display the content in relative time formats
    set(h.Handles.EDTtimeManualStart,'String',datestr(now));
    set(h.Handles.EDTtimeManualInterval,'String','1');
    % switch unit text on
    set(h.Handles.TXTtimeManualIntervalUnit,'Visible','on');
else
    % Set the contents of the format combo to be relative time formats
    set(h.Handles.TXTtimeManualFormat,'String',xlate('Units : '))
    set(h.Handles.COMBtimeManualFormat,'String',{'weeks', 'days', 'hours', 'minutes', ...
        'seconds', 'milliseconds', 'microseconds', 'nanoseconds'},'Value',5);
    % display the content in relative time formats
    set(h.Handles.EDTtimeManualStart,'String','0');
    set(h.Handles.EDTtimeManualInterval,'String','1');
    % switch unit text off
    set(h.Handles.TXTtimeManualIntervalUnit,'Visible','off');
end


function localSetStartTime(eventSrc, eventData, h)
%% Callback for the start time edit box


function localSetInterval(eventSrc, eventData, h)
%% Callback for the interval time edit box

function localSwitchFormat(eventSrc, eventData, h)
%% Callback for the format/unit edit box
switch h.IOData.formatcell.matlabFormatIndex(get(h.Handles.COMBtimeManualFormat,'Value'))
    case {0 13 14 21} 
        %'dd-mmm-yyyy HH:MM:SS' 'HH:MM:SS' 'HH:MM:SS PM' 'mmm.dd,yyyy HH:MM:SS'
        set(h.Handles.TXTtimeManualIntervalUnit,'String','seconds');
    case {1 2 6 22 23}
        set(h.Handles.TXTtimeManualIntervalUnit,'String','days');
    case {15 16}
        set(h.Handles.TXTtimeManualIntervalUnit,'String','minutes');        
end


