function b = setGUI(this, Hd)
%SETGUI   Set the GUI.

%   Author(s): J. Schickler
%   Copyright 2006-2010 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2010/05/20 03:03:18 $

b = true;
hfdesign = getfdesign(Hd);
if ~strcmpi(get(hfdesign, 'Response'), 'differentiator')
    b = false;
    return;
end
switch hfdesign.Specification
    case 'Fp,Fst,Ap,Ast'
        set(this, ...
            'Fpass', num2str(hfdesign.Fpass), ...
            'Fstop', num2str(hfdesign.Fstop), ...
            'Apass', num2str(hfdesign.Apass), ...
            'Astop', num2str(hfdesign.Astop));
    case 'N'
        set(this, ...
            'privFrequencyConstraints', 'unconstrained', ...
            'privMagnitudeConstraints', 'unconstrained', ...
            'Order', num2str(hfdesign.FilterOrder));
    case 'Ap'
        % Not yet implemented.
    case 'N,Fp,Fst'
        set(this, ...
            'privFrequencyConstraints', 'Passband edge and stopband edge', ...
            'privMagnitudeConstraints', 'unconstrained', ...
            'Order', num2str(hfdesign.FilterOrder), ...
            'Fpass', num2str(hfdesign.Fpass), ...
            'Fstop', num2str(hfdesign.Fstop));
    otherwise
        error(generatemsgid('IncompleteConstraints'), ...
            'Internal Error: Differentiator ''%s'' incomplete', hfdesign.Specification);
end

abstract_setGUI(this, Hd);

% [EOF]
