function createUIControls_tableContextMenu(this)
    % Copyright 2010 The MathWorks, Inc.
    
    % This function is called to create table context menu. This is common
    % for Inspect Signals and Compare Signals tab.

    % Cache string dictionary class
    SD = Simulink.sdi.StringDict;

    this.tableContextMenu = uicontextmenu('parent',this.HDialog);
    
    this.tableContextMenuColumns = uimenu(this.tableContextMenu,...
                                          'label', this.sd.mgColumns);
                                      
    this.tableContextMenuSortBy =     uimenu                               ...
                                      (this.tableContextMenu,              ...
                                      'label', this.sd.sortBy);                                        
    
    this.tableContextMenuSigSource = uimenu...
                                     (this.tableContextMenu,                   ...
                                     'label',                                  ...
                                     SD.mgHighlightSource,                     ...
                                     'callback',                               ...
                                     @this.tableContextMenuCallback_SigSource, ...
                                     'Separator', 'on');
    
    this.tableContextMenuViewData = uimenu                          ...
                                    (this.tableContextMenu,         ...
                                    'label',                        ...
                                    SD.mgExportVarEditor,           ...
                                    'callback',                     ...
                                    @this.tableContextMenuCallback_VarEditor);
                                  
    this.tableContextMenuDelete = uimenu                                 ...
                                  (this.tableContextMenu,                ...
                                   'label', this.sd.mgDeleteSelection,   ...
                                   'callback',                           ...
                                   @this.tableContextMenuCallback_delete,...
                                   'Separator', 'on'); 
%     this.tableContextMenuDeleteAll = uimenu                       ...
%                                      (this.tableContextMenu,      ...
%                                      'label', this.sd.mgDeleteAll,...
%                                      'callback',                  ...
%                                      @this.tableContextMenuCallback_deleteAll);
                                     
    this.tableContextMenuProperties = uimenu                                           ...
                                      (this.tableContextMenu,                          ...
                                      'label', this.sd.SPProperties,                   ...
                                      'callback',                                      ...
                                      @this.tableContextMenuCallback_SignalProperties, ...
                                      'Separator', 'on');  

    this.tableContextMenuSortByRun = uimenu                               ...
                                     (this.tableContextMenuSortBy,        ...
                                     'label', this.sd.mgRun,              ...
                                     'callback',                          ...
                                     {@this.tableContextMenuCallback_Sort,...
                                     'GRUNNAME'});
    set(this.tableContextMenuSortByRun, 'Checked', 'on');                                 
    this.tableContextMenuSortByBlock = uimenu                                 ...
                                     (this.tableContextMenuSortBy,            ...
                                     'label', this.sd.IGBlockSourceColName,...
                                     'callback',                              ...
                                     {@this.tableContextMenuCallback_Sort,    ...
                                     'GBLOCKPATH'});         
    this.tableContextMenuSortByData =  uimenu                                 ...
                                     (this.tableContextMenuSortBy,            ...
                                     'label', this.sd.IGDataSourceColName, ...
                                     'callback',                              ...
                                     {@this.tableContextMenuCallback_Sort,    ...
                                     'GDATASOURCE'});  
    this.tableContextMenuSortByModel =  uimenu                                ...
                                     (this.tableContextMenuSortBy,            ...
                                     'label', this.sd.IGModelSourceColName,...
                                     'callback',                              ...
                                     {@this.tableContextMenuCallback_Sort,    ...
                                     'GMODEL'});
    this.tableContextMenuSortBySignalName =  uimenu                           ...
                                     (this.tableContextMenuSortBy,            ...
                                     'label', this.sd.mgSigLabel,          ...
                                     'callback',                              ...
                                     {@this.tableContextMenuCallback_Sort,    ...
                                     'GSIGNALNAME'});                                                                   
                                  
    this.tableContextMenuRun  = uimenu                        ...
                                (this.tableContextMenuColumns,...
                                'label', this.sd.mgRun,       ...
                                'callback',                   ...
                                @this.tableContextMenuCallback_Columns);
    this.tableContextMenuColor  = uimenu                        ...
                                  (this.tableContextMenuColumns,...
                                  'label', this.sd.mgLine,      ...
                                  'callback',                   ...
                                  @this.tableContextMenuCallback_Columns);
    this.tableContextMenuAbsTol  = uimenu(this.tableContextMenuColumns,...
                                          'label',                     ...
                                          SD.MGAbsTolLbl,              ...
                                          'callback',                  ...
                                          @this.tableContextMenuCallback_Columns);
                                  
    this.tableContextMenuRelTol  = uimenu(this.tableContextMenuColumns,...
                                          'label',                     ...
                                          SD.MGRelTolLbl,              ...
                                          'callback',                  ...
                                          @this.tableContextMenuCallback_Columns);                              
    
    this.tableContextMenuSync  = uimenu(this.tableContextMenuColumns,...
                                        'label',                     ...
                                        SD.MGSynchMethodLbl,         ...
                                        'callback',                  ...
                                        @this.tableContextMenuCallback_Columns);  
    this.tableContextMenuInterp  = uimenu(this.tableContextMenuColumns,...
                                          'label',                     ...
                                          SD.MGInterpMethodLbl,        ...
                                          'callback',                  ...
                                          @this.tableContextMenuCallback_Columns); 
        
    this.tableContextMenuDataSource  = uimenu                          ...
                                       (this.tableContextMenuColumns,  ...
                                       'label', SD.IGDataSourceColName,...
                                       'callback',                     ...
                                       @this.tableContextMenuCallback_Columns);
    this.tableContextMenuModelSource = uimenu                           ...
                                       (this.tableContextMenuColumns,   ...
                                       'label', SD.IGModelSourceColName,...
                                       'callback',                      ...
                                       @this.tableContextMenuCallback_Columns);
    this.tableContextMenuSignalLabel = uimenu                        ...
                                       (this.tableContextMenuColumns,...
                                       'label', this.sd.mgSigLabel,  ...
                                       'callback',                   ...
                                       @this.tableContextMenuCallback_Columns);
    this.tableContextMenuRoot = uimenu                        ...
                                (this.tableContextMenuColumns,...
                                'label',                      ...
                                this.sd.IGRootSourceColName,  ...
                                'callback',                   ...
                                @this.tableContextMenuCallback_Columns);                                 
    this.tableContextMenuTimeSource = uimenu                        ...
                                      (this.tableContextMenuColumns,...
                                      'label',                      ...
                                      this.sd.IGTimeSourceColName,  ...
                                      'callback',                   ...
                                      @this.tableContextMenuCallback_Columns);                                
    this.tableContextMenuPort = uimenu                        ...
                                (this.tableContextMenuColumns,...
                                'label',                      ...
                                this.sd.IGPortIndexColName,   ...
                                'callback',                   ...
                                @this.tableContextMenuCallback_Columns); 
    this.tableContextMenuDim = uimenu                        ...
                               (this.tableContextMenuColumns,...
                               'label',                      ...
                               this.sd.mgDimensions,         ...
                               'callback',                   ...
                               @this.tableContextMenuCallback_Columns);
    this.tableContextMenuChannel...
                               = uimenu                      ...
                               (this.tableContextMenuColumns,...
                               'label',                      ...
                               this.sd.mgChannel,            ...
                               'callback',                   ...
                               @this.tableContextMenuCallback_Columns);                           