function createUIControls_commonTTModel(this)
    % Copyright 2010 The MathWorks, Inc.
    % this function creates a common table model for Inspect and Compare
    % Signals tables. 

    sd = this.sd;
    this.colNames = {sd.IGBlockSourceColName,  sd.mgRun, sd.mgSigLabel,          ... 
                     sd.mgLine, sd.mgLeft, sd.mgRight, sd.MGInspectColNamePlot,  ...
                     sd.IGDataSourceColName, sd.IGModelSourceColName,            ...
                     sd.mgAbsTol, sd.mgRelTol,                                   ...
                     sd.mgSyncMethod, sd.mgInterpMethod,                         ...
                     sd.IGRootSourceColName, sd.IGTimeSourceColName,             ...
                     sd.IGPortIndexColName, sd.mgDimensions,                     ...
                     sd.mgChannel, sd.mgLeaf};
    % this is the default group criterion
    this.sortCriterion = 'GRUNNAME';
                          
    numCol = length(this.colNames);
    rowList = this.populateTableColumns(this.sortCriterion, this.colNames,...
                                        sd.mgAsc);
    this.colNameArrayList = javaObjectEDT('java.util.ArrayList');
    
    for i = 1 : numCol
        strName = java.lang.String(this.colNames{i});
        this.colNameArrayList.add(strName);
    end
                                    
    this.commonTableModel = javaObjectEDT(...
                            'com.mathworks.toolbox.sdi.sdi.STreeTableModel', ...  
                            rowList, this.colNameArrayList, numCol, 1);
    
end
