function createUIControls_ContextMenuTableHeaderInspect(this)

%   Copyright 2010 The MathWorks, Inc.

    this.tableColumnSelectContextMenu = uicontextmenu('parent', this.HDialog);
    
    this.contextMenuColumns = uimenu(this.tableColumnSelectContextMenu,...
                                     'label', this.sd.mgColumns);
                                      
    this.contextMenuSortBy =    uimenu                             ...
                                (this.tableColumnSelectContextMenu,...
                                'label', this.sd.sortBy);
    
    this.contextMenuSortByRun =       uimenu                              ...
                                     (this.contextMenuSortBy,             ...
                                     'label', this.sd.mgRun,              ...
                                     'callback',                          ...
                                     {@this.tableContextMenuCallback_Sort,...
                                     'GRUNNAME'});
                                 
    set(this.contextMenuSortByRun, 'Checked', 'on');                                 
    this.contextMenuSortByBlock =     uimenu                                  ...
                                     (this.contextMenuSortBy,                 ...
                                     'label', this.sd.IGBlockSourceColName,   ...
                                     'callback',                              ...
                                     {@this.tableContextMenuCallback_Sort,    ...
                                     'GBLOCKPATH'});         
    this.contextMenuSortByData =     uimenu                                   ...
                                     (this.contextMenuSortBy,                 ...
                                     'label', this.sd.IGDataSourceColName,    ...
                                     'callback',                              ...
                                     {@this.tableContextMenuCallback_Sort,    ...
                                     'GDATASOURCE'});  
    this.contextMenuSortByModel =     uimenu                                  ...
                                     (this.contextMenuSortBy,                 ...
                                     'label', this.sd.IGModelSourceColName,   ...
                                     'callback',                              ...
                                     {@this.tableContextMenuCallback_Sort,    ...
                                     'GMODEL'});
    this.contextMenuSortBySignalName =  uimenu                                ...
                                     (this.contextMenuSortBy,                 ...
                                     'label', this.sd.mgSigLabel,             ...
                                     'callback',                              ...
                                     {@this.tableContextMenuCallback_Sort,    ...
                                     'GSIGNALNAME'});                        
    
    
    this.contextMenuRun  = uimenu(this.contextMenuColumns,...
                                  'label', this.sd.mgRun);
    this.contextMenuColor  = uimenu(this.contextMenuColumns,...
                                    'label', this.sd.mgLine);
    this.contextMenuAbsTol  = uimenu(this.contextMenuColumns,...
                                     'label', this.sd.MGAbsTolLbl);
    this.contextMenuRelTol  = uimenu(this.contextMenuColumns,...
                                     'label', this.sd.MGRelTolLbl);                                 
    this.contextMenuSync  = uimenu(this.contextMenuColumns,...
                                   'label', this.sd.MGSynchMethodLbl);                                        
    this.contextMenuInterp  = uimenu(this.contextMenuColumns,...
                                   'label', this.sd.MGInterpMethodLbl);  
                                
    this.contextMenuDataSource  = uimenu(this.contextMenuColumns,...
                                        'label', this.sd.IGDataSourceColName);
    this.contextMenuModelSource = uimenu(this.contextMenuColumns,...
                                        'label', this.sd.IGModelSourceColName);
    this.contextMenuSignalLabel = uimenu(this.contextMenuColumns,...
                                        'label', this.sd.mgSigLabel);
    this.contextMenuRoot = uimenu(this.contextMenuColumns,...
                                 'label', this.sd.IGRootSourceColName);                                 
    this.contextMenuTimeSource = uimenu(this.contextMenuColumns,...
                                       'label', this.sd.IGTimeSourceColName);                                
    this.contextMenuPort = uimenu(this.contextMenuColumns,...
                                 'label', this.sd.IGPortIndexColName); 
    this.contextMenuDim = uimenu(this.contextMenuColumns,...
                                'label', this.sd.mgDimensions);
    this.contextMenuChannel = uimenu(this.contextMenuColumns,...
                                    'label', this.sd.mgChannel);                                     
                                    
  
    set(this.contextMenuRun, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuColor, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuDataSource, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuModelSource, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuSignalLabel, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuRoot, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuTimeSource, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuPort, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuDim, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuChannel, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuAbsTol, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuRelTol, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuSync, 'callback',...
        @this.tableContextMenu_Inspect);
    set(this.contextMenuInterp, 'callback',...
        @this.tableContextMenu_Inspect);    
end

