function createUIControls(this)
    
    % Copyright 2009-2010 The MathWorks, Inc.
    
    % Cache string dictionary class
    SD  = Simulink.sdi.StringDict;
    
    % cache geometric constants
    GC = Simulink.sdi.GeoConst;
    
    % Cache GUI utilities class
    UG = Simulink.sdi.GUIUtil;
    
    % Main Dialog
    this.HDialog = UG.CreateDialog(SD.MGTitle);
    
    % set simulink icon instead of MATLAB icon
    prevState = warning('off','MATLAB:HandleGraphics:ObsoletedProperty:JavaFrame');
    warningCleaner = onCleanup(@() warning(prevState));
    jframe=get(this.HDialog, 'javaframe');
    iconPath = fullfile(matlabroot, ...
                        'toolbox',  ...
                        'simulink', ...
                        'simulink', ...
                        '+Simulink',...
                        '+sdi',     ...
                        'Icons',    ...
                        'simulink.gif');
    jIcon=javax.swing.ImageIcon(iconPath);
    jframe.setFigureIcon(jIcon);
                        
    % Tabs.. axes on MJPanel
    %     this.TabGroup  = javaObjectEDT('com.mathworks.mwswing.MJTabbedPane');
    %     this.TabInspectSignals = javaObjectEDT('com.mathworks.mwswing.MJPanel');
    %     this.TabCompareSignals = javaObjectEDT('com.mathworks.mwswing.MJPanel');
    %     this.TabCompareRuns = javaObjectEDT('com.mathworks.mwswing.MJPanel');
    
    %     this.TabGroup.addTab(SD.MGInspectSignals, this.TabInspectSignals);
    %     this.TabGroup.addTab(SD.MGCompareSignals, this.TabCompareSignals);
    %     this.TabGroup.addTab(SD.MGCompareRuns, this.TabCompareRuns);
    
    % Create UITabs |Inspect Signals | Compare Signals | Compare Runs|
    %**************************************************************************
    % Turning off uitabgroup warnings
    %**************************************************************************
    oldState = warning('off','MATLAB:uitabgroup:OldVersion');
    warnCleaner = onCleanup(@() warning(oldState));
    %**************************************************************************

    this.TabGroup = uitabgroup('Parent', this.HDialog);
    this.TabInspectSignals = uitab(this.TabGroup, ...
        'title', SD.MGInspectSignals);
    this.TabCompareSignals = uitab(this.TabGroup, ...
        'title', SD.MGCompareSignals);
    this.TabCompareRuns    = uitab(this.TabGroup, ...
        'title', SD.MGCompareRuns);
    this.inspectSplitter = Simulink.sdi.splitPane(this.TabInspectSignals,...
                                                  'hori', 6,             ...
                                                  [0.5 0.5 0.5], 0.4, [],...
                                                   GC.mOptionWidth + GC.mOptionHeight);
    set(this.TabGroup,'SelectionChangeCallback',@this.TabClickCallback);    
    
    % Main Menu
    this.MainMenuFileGroup = uimenu('Parent',      this.HDialog,           ...
                                    'Label',       SD.File);
    this.MainMenuNew       = uimenu('Parent',      this.MainMenuFileGroup, ...
                                    'Label',       SD.New);
    this.MainMenuOpen      = uimenu('Parent',      this.MainMenuFileGroup, ...
                                    'Label',       [SD.Open SD.DotDotDot], ...
                                    'Accelerator', 'o');
    this.MainMenuSave      = uimenu('Parent',      this.MainMenuFileGroup, ...
                                    'Label',       SD.Save,                ...
                                    'Accelerator', 's',                    ...
                                    'Separator',   'on');
    this.MainMenuSaveAs    = uimenu('Parent',      this.MainMenuFileGroup, ...
                                    'Label',       [SD.SaveAs SD.DotDotDot]);
    this.dataMenuImport    = uimenu('Parent', this.MainMenuFileGroup, ...
                                    'Label',  SD.mgImportWorkSpace,   ...
                                    'Separator', 'on');
    this.dataMenuRecord    = uimenu('Parent', this.MainMenuFileGroup, ...
                                    'Label',  SD.mgRecordSim);                           
    this.MainMenuExit      = uimenu('Parent',      this.MainMenuFileGroup, ...
                                    'Label',       SD.Exit,                ...
                                    'Separator',   'on');

                                   
    % Plot Tools
    this.plotToolsMenuGroup   = uimenu('Parent', this.HDialog,           ...
                                       'Label',  SD.mgPlotTools);
    this.plotToolsZoomInX     = uimenu('Parent', this.plotToolsMenuGroup,...
                                       'Label',  SD.MGZoomInX);
    this.plotToolsZoomInY     = uimenu('Parent', this.plotToolsMenuGroup,...
                                       'Label',  SD.MGZoomInY);                                   
    this.plotToolsZoomInXY    = uimenu('Parent', this.plotToolsMenuGroup,...
                                       'Label',  SD.MGZoomInXY);                                                                                                          
    this.plotToolsZoomOut     = uimenu('Parent', this.plotToolsMenuGroup,...
                                       'Label',  SD.MGZoomOut);
    this.plotToolsPan         = uimenu('Parent', this.plotToolsMenuGroup,...
                                       'Label',  SD.MGPan);
    this.plotToolsDataCursor  = uimenu('Parent', this.plotToolsMenuGroup,...
                                       'Label',  SD.MGDataCursor);
    
    % Help
    this.MainMenuHelpGroup    = uimenu('Parent', this.HDialog,           ...
                                       'Label',  SD.Help);
    this.MainMenuHelpContents = uimenu('Parent', this.MainMenuHelpGroup, ...
                                       'Label',  [SD.ToolName ' ' SD.Help]);
    this.MainMenuAbout        = uimenu('Parent', this.MainMenuHelpGroup, ...
                                       'Label',  [SD.About ' ' SD.Simulink]);
    
    % Toolbar
    this.Toolbar = uitoolbar('Parent', this.HDialog);
    
    % Toolbar button icons
    iconNew         = UG.ReadMATLABIcon('file_new.png');
    iconOpen        = UG.ReadMATLABIcon('file_open.png');
    iconSave        = UG.ReadMATLABIcon('file_save.png');
    iconImport      = UG.ReadSDIIcon('sdi_import.png');        
    iconPan         = UG.ReadMATLABIcon('tool_hand.png');
    iconDataCursor  = UG.ReadMATLABIcon('tool_data_cursor.png');
    iconRecord      = UG.ReadSDIIcon('red_dot.gif');
    iconHelp        = UG.ReadSDIIcon('icon_help.png');
    iconZoomX       = UG.ReadSDIIcon('zoomX.png');
    iconZoomY       = UG.ReadSDIIcon('zoomY.png');
    iconZoomXY      = UG.ReadSDIIcon('zoomXY.png');
    iconZoomOut     = UG.ReadSDIIcon('zoomOut.png');
    
    % Toolbar buttons
    this.ToolbarButtonNew        = uipushtool('Parent',        this.Toolbar, ...
                                              'TooltipString', SD.New,       ...
                                              'CData',         iconNew);
    
    this.ToolbarButtonLoad       = uipushtool('Parent',        this.Toolbar, ...
                                              'TooltipString', SD.Open,      ...
                                              'CData',         iconOpen);
    
    this.ToolbarButtonSave       = uipushtool('Parent',        this.Toolbar, ...
                                              'TooltipString', SD.Save,      ...
                                              'CData',         iconSave);
    
    this.ToolbarButtonImport     = uipushtool('Parent',        this.Toolbar,    ...
                                             'TooltipString', SD.MGImportData, ...
                                             'CData',         iconImport,      ...
                                             'Separator',     'on');
    
    this.ToolbarButtonRecord     = uitoggletool('Parent',        this.Toolbar,    ...
                                                'TooltipString', SD.mgRecordSim,  ...
                                                'CData',         iconRecord);
    
    this.ToolbarButtonZoomInX    = uitoggletool('Parent',        this.Toolbar,  ...
                                                'TooltipString', SD.MGZoomInX,  ...
                                                'CData',         iconZoomX,     ...
                                                'Separator',     'on');
                                        
    this.ToolbarButtonZoomInY    = uitoggletool('Parent',        this.Toolbar,  ...
                                                'TooltipString', SD.MGZoomInY,  ...
                                                'CData',         iconZoomY);       
                                        
    this.ToolbarButtonZoomInXY   = uitoggletool('Parent',        this.Toolbar,  ...
                                                'TooltipString', SD.MGZoomInXY, ...
                                                'CData',         iconZoomXY);                                         
    
    this.ToolbarButtonZoomOut    = uitoggletool('Parent',        this.Toolbar, ...
                                                'TooltipString', SD.MGZoomOut, ...
                                                'CData',         iconZoomOut);
    
    this.ToolbarButtonPan        = uitoggletool('Parent',        this.Toolbar, ...
                                                'TooltipString', SD.MGPan,     ...
                                                'CData',         iconPan);
                                     
    this.ToolbarButtonDataCursor = uitoggletool('Parent', this.Toolbar,            ...
                                                'TooltipString', SD.MGDataCursor,  ...
                                                'CData',  iconDataCursor);                                 
   
    
    this.toolbarButtonHelp       = uipushtool('Parent',         this.Toolbar,...
                                              'TooltipString', SD.Help,     ...
                                              'Separator',     'on',        ...
                                              'CData',         iconHelp);
  
    % Options menu
    this.OptionsMenu          = uicontextmenu('Parent', this.HDialog);
    this.OptionsMenuOriginal  = uimenu(this.OptionsMenu, ...
                                       'Label', SD.MGOriginalAxis);
    this.OptionsMenuNormalize = uimenu(this.OptionsMenu, ...
                                       'Label', SD.MGNormalizedAxis);
    this.optionsMenuStairPlot = uimenu(this.OptionsMenu,       ...
                                       'Label', SD.mgStairStep,...
                                       'Separator', 'on');
    this.optionsMenuLinePlot  = uimenu(this.OptionsMenu, ...
                                       'Label', SD.mgLinePlot);
    this.OptionsMenuNewFigure = uimenu(this.OptionsMenu,            ...
                                       'Label',     SD.MGNewFigure, ...
                                       'Separator', 'on');
   
 
    % Populate tabs                               
    this.createUIControls_InspectSignalsTab();
    this.createUIControls_CompareSignalsTab();
    this.createUIControls_CompareRunsTab();    
    
    % Options menu buttons - No more than 2 per screen
                                   
    % Options Buttons - Icons
    optionsIcon = Simulink.sdi.GUIUtil.CreateSDIIconPath('arrow_down_black.gif');
    
    % Options Button 1
    [this.OptionsMenuButton1,                                             ...
     this.OptionsMenuButton1Container] =                                  ...
                                    Simulink.sdi.GUIUtil.CreateButton     ...
                                    (this.HDialog, SD.Options,            ...
                                     optionsIcon);
                                 
    % Options Button 2
    [this.OptionsMenuButton2,                                             ...
     this.OptionsMenuButton2Container] =                                  ...
                                    Simulink.sdi.GUIUtil.CreateButton     ...
                                    (this.HDialog, SD.Options,            ...
                                     optionsIcon);                                
                                 
  
    % option button margins etc.
    this.OptionsMenuButton1.setVerticalTextPosition(javax.swing.AbstractButton.CENTER);
    this.OptionsMenuButton1.setHorizontalTextPosition(javax.swing.AbstractButton.LEFT); 
    inset = javaObjectEDT('java.awt.Insets', 2, 1, 2, 1);
    this.OptionsMenuButton1.setMargin(inset);
    this.OptionsMenuButton2.setVerticalTextPosition(javax.swing.AbstractButton.CENTER);
    this.OptionsMenuButton2.setHorizontalTextPosition(javax.swing.AbstractButton.LEFT);
    this.OptionsMenuButton2.setMargin(inset);
    
    % set renderers
    this.setRenderers();
    
    % set callbacks
    this.SetCallbacks();    
end

