function SetCallbacks(this)

    % Copyright 2009-2010 The MathWorks, Inc.

    % Dialog
    set(this.HDialog, 'ResizeFcn', @this.DialogResizeCallback);
    set(this.HDialog, 'CloseRequestFcn', @this.dialogCloseCallback);
    

    % Main menu
    set(this.MainMenuNew,          'Callback', @this.callback_New);
    set(this.MainMenuOpen,         'Callback', @this.callback_Load);
    set(this.MainMenuSave,         'Callback', @this.callback_Save);
    set(this.MainMenuSaveAs,       'Callback', @this.callback_SaveAs);
    set(this.MainMenuExit,         'Callback', @this.callback_Exit);
    set(this.MainMenuHelpContents, 'Callback', @this.MainMenuHelpContentsCallback);
    set(this.MainMenuAbout,        'Callback', @this.MainMenuAboutCallback);
    
    % Plot tools menu
    set(this.plotToolsZoomInX,     'Callback', {@this.menuButtonPlotCallback,...
                                               this.plotToolsZoomInX,        ...
                                               this.ToolbarButtonZoomInX,    ...
                                               {@this.ToolbarButtonZoomInCallback,...
                                               'zoominx'}});  
                                           
    set(this.plotToolsZoomInY,     'Callback', {@this.menuButtonPlotCallback,...
                                               this.plotToolsZoomInY,        ...
                                               this.ToolbarButtonZoomInY,    ...
                                               {@this.ToolbarButtonZoomInCallback,...
                                               'zoominy'}});                                           

    set(this.plotToolsZoomInXY,     'Callback', {@this.menuButtonPlotCallback,...
                                               this.plotToolsZoomInXY,        ...
                                               this.ToolbarButtonZoomInXY,    ...
                                               {@this.ToolbarButtonZoomInCallback,...
                                               'zoominxy'}});                                           
                                           
    set(this.plotToolsZoomOut,     'Callback', {@this.menuButtonPlotCallback,...
                                               this.plotToolsZoomOut,        ...
                                               this.ToolbarButtonZoomOut,    ...
                                               @this.ToolbarButtonZoomOutCallback});  
    set(this.plotToolsPan,         'Callback', {@this.menuButtonPlotCallback,...
                                               this.plotToolsPan,            ...
                                               this.ToolbarButtonPan,        ...
                                               @this.ToolbarButtonPanCallback});     

    set(this.plotToolsDataCursor,  'Callback', {@this.menuButtonPlotCallback,...
                                               this.plotToolsDataCursor,     ...
                                               this.ToolbarButtonDataCursor, ...
                                               @this.toolbarButtonDataCursorCallback});     
                                           
    % Data Menu
    set(this.dataMenuRecord,       'Callback', @this.menuButtonDataCallback);
    set(this.dataMenuImport,       'Callback', @(s,e)this.callback_ImportGUI(s,e));
    
    
    % Toolbar
    set(this.ToolbarButtonNew,     'ClickedCallback',...
        @(s, e)this.callback_New);
    set(this.ToolbarButtonLoad,    'ClickedCallback',...
        @(s, e)this.callback_Load);
    set(this.ToolbarButtonSave,    'ClickedCallback',...
        @(s, e)this.callback_Save);
    set(this.ToolbarButtonImport,  'ClickedCallback',...
        @(s, e)this.callback_ImportGUI(s,e));
    set(this.ToolbarButtonZoomInX,  'ClickedCallback',...
        {@this.ToolbarButtonZoomInCallback, 'zoominx'});    
    set(this.ToolbarButtonZoomInY,  'ClickedCallback',...
        {@this.ToolbarButtonZoomInCallback, 'zoominy'});    
    set(this.ToolbarButtonZoomInXY,  'ClickedCallback',...
        {@this.ToolbarButtonZoomInCallback, 'zoominxy'});            
    set(this.ToolbarButtonZoomOut, 'ClickedCallback',...
        @(s, e)this.ToolbarButtonZoomOutCallback);
    set(this.ToolbarButtonPan,     'ClickedCallback',...
        @(s, e)this.ToolbarButtonPanCallback);
    set(this.ToolbarButtonDataCursor, 'ClickedCallback',...
        @(s, e)this.toolbarButtonDataCursorCallback);
    set(this.ToolbarButtonRecord,  'ClickedCallback',...
        @(s, e)this.ToolbarButtonRecordCallback);
    set(this.toolbarButtonHelp,    'ClickedCallback',...
        @(s,e)this.MainMenuHelpContentsCallback);
   
    % Options menu
    set(this.OptionsMenuButton1, 'ActionPerformedCallback', @this.OptionsMenuButton1Callback);
    set(this.OptionsMenuButton2, 'ActionPerformedCallback', @this.OptionsMenuButton2Callback);
    set(this.OptionsMenuOriginal,  'Callback', @this.optionsMenuOriginalCallback);
    set(this.OptionsMenuNormalize, 'Callback', @this.optionsMenuNormalizeCallback);
    set(this.OptionsMenuNewFigure, 'Callback', @this.OptionsMenuNewFigureCallback);
    set(this.optionsMenuStairPlot, 'Callback', {@this.optionsMenuLineCallback,...
                                                false});
    set(this.optionsMenuLinePlot,  'Callback', {@this.optionsMenuLineCallback,...
                                                 true});
    


