function renderPre(h,hPropParent)
%renderPre Rendering tasks performed prior to rendering children.
%  Overload for uistatusgroup class.

% Copyright 2004-2009 The MathWorks, Inc.
% $Revision: 1.1.6.3 $ $Date: 2009/08/14 04:07:39 $

% Confirm that .GraphicalParent is set
if isempty(h.GraphicalParent) || ~uimgr.isHandle(h.GraphicalParent)
    % See if hPropParent type is useful for the buttongroup:
    %    empty/invalid: create a new or use existing figure,
    %           then see below
    %    figure: create new uistatusbar under figure
    %    others: just take them as is and use them
    %
    % An error can be generated by the widget function if an invalid
    % parent is used. A uistatusbar is the most common parent here.
    %
    if isempty(hPropParent) || ~uimgr.isHandle(hPropParent) %
        hPropParent = gcf;
    end
    if strcmpi(get(hPropParent,'type'),'figure')
        % Use existing or create new uistatusbar
        hPropParent = []; % findobj(hPropParent,'type','uistatusbar');
        if isempty(hPropParent)
            hPropParent = uistatusbar;
        else
            hPropParent = hPropParent(1);
        end
    end
    h.GraphicalParent = hPropParent;
end

% [EOF]
