function out = emptyfixptsimrange;
%EMPTYSIMRANGE is for internal use only by Simulink Fixed Point

%
%    Create empty version of structure used in FixPtSimRanges
%

% Copyright 1994-2005 The MathWorks, Inc.
% $Revision: 1.7.2.1 $  
% $Date: 2005/06/24 11:10:36 $

out = struct(...
            'Name',[],...
            'DataType',[],...
            'ExpBits',[],...
            'MantBits',[],...
            'FixExp',[],...
            'Slope',[],...
            'Bias',[],...
            'MinValue',[],...
            'TimeOfMin',[],...
            'MaxValue',[],...
            'TimeOfMax',[]);
