function setup_figure(hPD)
%SETUP_FIGURE Create the figure for the parameter dialog

%   Author(s): J. Schickler
%   Copyright 1988-2002 The MathWorks, Inc.
%   $Revision: 1.4 $  $Date: 2002/11/21 15:30:25 $

sz  = parameter_gui_sizes(hPD);
cbs = dialog_cbs(hPD);

hFig = figure('Position', sz.fig, ...
    'Integerhandle',    'Off', ...
    'NumberTitle',      'Off', ...
    'Name',             hPD.Name, ...
    'Menubar',          'None', ...
    'HandleVisibility', 'Off', ...
    'Resize',           'Off', ...
    'Color',            get(0,'defaultuicontrolbackgroundcolor'), ...
    'Visible',          hPD.Visible);

set(hPD, 'FigureHandle', hFig);

% [EOF]
