function multiratespectypes = getmultiratespectypes(this)
%GETMULTIRATESPECTYPES   Get the multiratespectypes.

%   Author(s): J. Schickler
%   Copyright 2005 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2008/04/21 16:30:25 $

multiratespectypes = {'Fst,Fp,Ast,Ap', ...
    'N,Fc', ...
    'N,F3dB',...
    'N,Fc,Ast,Ap', ...
    'N,Fp,Ast,Ap', ...
    'N,Fst,Fp,Ap', ...
    'N,Fst,Fp,Ast', ...
    'N,Fst,Ast,Ap', ...
    'N,Fst,Fp'};

% [EOF]
