function [props, asgnvals, top, bottom] = pnames(nlsys)
%PNAMES  Return all public properties and their assignable values.
%
%   [PROPS, ASGNVALS] = PNAMES(NLSYS) returns the list PROPS of
%   public properties of the object SYS (a cell vector), as well as
%   the assignable values ASGNVALS for these properties (a cell vector
%   of strings). PROPS contains the true case-sensitive property names.
%
%   [PROPS, ASGNVALS, TOP, BOTTOM] = PNAMES(NLSYS) returns also the indices
%   of the properties to be listed at the top and bottom of GET(M), with M
%   being an o bject of child class of IDNLMODEL.
%
%   See also IDNLMODEL/GET, IDNLMODEL/SET.

% Copyright 2005-2008 The MathWorks, Inc.
% $Revision: 1.1.10.4 $ $Date: 2008/06/13 15:24:37 $

% Author(s): Qinghua Zhang

% Check that the function is called with one argument.
error(nargchk(1, 1, nargin, 'struct'));
no = nargout;

% IDNLMODEL properties.
props = {'Name';             ...
    'Ts';               ...
    'TimeUnit';         ...
    'TimeVariable';     ...
    'InputName';        ...
    'InputUnit';        ...
    'OutputName';       ...
    'OutputUnit';       ...
    'NoiseVariance';    ...
    'Notes';            ...
    'UserData'          ...
    };

% If requested, return assignable values.
if (no > 1)
    asgnvals = {'Chars (model name)';                            ...
        'Scalar positive double (sample time)';          ...
        'Chars';                                         ...
        'Chars (valid MATLAB variable name)';            ...
        'Nu-by-1 cell array of chars';                   ...
        'Nu-by-1 cell array of chars';                   ...
        'Ny-by-1 cell array of chars';                   ...
        'Ny-by-1 cell array of chars';                   ...
        'Ny-by-Ny matrix (partly read-only property)';   ...
        'Chars or cell array of chars';                  ...
        'Arbitrary'                                      ...
        };
end
if (no > 2)
    top = 1:8;
    bottom = 9:length(props);
end

% FILE END