function xdata_adjusted = c166_fixpt_evenspace_cleanup(xdata_original,xdt,xscale)
%C166_FIXPT_EVENSPACE_CLEANUP adjust fixed point data for even spacing
%XDATA_ADJUSTED = C166_FIXPT_EVENSPACE_CLEANUP(XDATA_ORIGINAL,XDT,XSCALE)
%   This function modifies lookup table input data to be be evenly spaced if is
%   not quite evenly spaced after quantization.  For example, 0:0.005:1 appears
%   to be evenly spaced, but if it is quantized with scaling 2^-12, it will not
%   be evenly spaced.  Loss of even spacing can make a very significant impact
%   on the efficiency of the implementation.  Code generated by Real Time
%   Workshop to implement an uneven lookup table will be more complicated, and
%   equally important, the the input data will be stored in ROM.  Modifying the
%   input data to remain evenly spaced after quantization allows Real Time
%   Workshop to generate simpler code and to exclude the input data from memory
%   thereby saving significant amounts of ROM.  The modifications to the lookup
%   table input data are likely to change the numerical behavior of the table.
%   The numerical changes may or may not be trivial, so the model should be
%   tested using simulation, rapid prototyping, or other appropriate methods.
%
%   xdata_original is the input lookup data, ex. 0:0.005:1
%   xdt            is the input data type,   ex. sfix(16)
%   xscale         is the input scaling,     ex. 2^-12
%

% Copyright 1994-2006 The MathWorks, Inc.
% $Revision: 1.1.4.3 $  
% $Date: 2006/06/20 20:20:38 $

warning(['The function c166_fixpt_evenspace_cleanup is deprecated and will be '...
         'removed in future versions. You should replace references to this '...
         'function with fixpt_evenspace_cleanup.']);

xdata_adjusted = fixpt_evenspace_cleanup(xdata_original,xdt,xscale);

