% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 17-Mar-2010 10:58:06
%  MATLAB version: 7.9.0.198 (R2009b)
% -------------------------------------------------------------------

%   Copyright 2010 The MathWorks, Inc.
                                                   

nvmImplicitRExplicitW = AUTOSAR.Signal;
nvmImplicitRExplicitW.RTWInfo.StorageClass = 'Custom';
nvmImplicitRExplicitW.RTWInfo.Alias = '';
nvmImplicitRExplicitW.RTWInfo.CustomStorageClass = 'PerInstanceMemory';
nvmImplicitRExplicitW.RTWInfo.CustomAttributes.needsNVRAMAccess = true;
nvmImplicitRExplicitW.Description = '';
nvmImplicitRExplicitW.DataType = 'uint8';
nvmImplicitRExplicitW.Min = -Inf;
nvmImplicitRExplicitW.Max = Inf;
nvmImplicitRExplicitW.DocUnits = '';
nvmImplicitRExplicitW.Dimensions = -1;
nvmImplicitRExplicitW.Complexity = 'auto';
nvmImplicitRExplicitW.SampleTime = -1;
nvmImplicitRExplicitW.SamplingMode = 'auto';
nvmImplicitRExplicitW.InitialValue = '';

nvmImplicitRW = AUTOSAR.Signal;
nvmImplicitRW.RTWInfo.StorageClass = 'Custom';
nvmImplicitRW.RTWInfo.Alias = '';
nvmImplicitRW.RTWInfo.CustomStorageClass = 'PerInstanceMemory';
nvmImplicitRW.RTWInfo.CustomAttributes.needsNVRAMAccess = true;
nvmImplicitRW.Description = '';
nvmImplicitRW.DataType = 'uint8';
nvmImplicitRW.Min = -Inf;
nvmImplicitRW.Max = Inf;
nvmImplicitRW.DocUnits = '';
nvmImplicitRW.Dimensions = -1;
nvmImplicitRW.Complexity = 'auto';
nvmImplicitRW.SampleTime = -1;
nvmImplicitRW.SamplingMode = 'auto';
nvmImplicitRW.InitialValue = '';

