function simParamMap = simprmtagmap
%SIMPARAMTAGMAP  Define the mapping from a model's
%   simulation parameters to Simulation Parameter Dialog's ui item.

%   Copyright 2002-2006 The MathWorks, Inc.
%   $Revision: 1.1.6.7 $  $Date: 2007/11/17 23:24:30 $

simParamMap = {
    'StartTime',                    'Solver'
    'StopTime',                     'Solver'
    'Solver',                       'Solver'
    'SolverMode',                   'Solver'
    'RelTol',                       'Solver'
    'AbsTol',                       'Solver'
    'FixedStep',                    'Solver'
    'MaxStep',                      'Solver'
    'InitialStep',                  'Solver'
    'MinStep',                      'Solver'
    'MaxConsecutiveMinStep'         'Solver'
    'MaxNumMinSteps',               'Solver'
    'MaxOrder',                     'Solver'
    'ZcThreshold'                'Solver'
    'ConsecutiveZCsStepRelTol'      'Solver'
    'MaxConsecutiveZCs'             'Solver'
    'OutputOption',                 'Solver'
    'OutputTimes',                  'Solver'
    'Refine',                       'Solver'
    'ZeroCrossAlgorithm'            'Solver'
    ... Workspace IO
    'LoadExternalInput',   'WorkspaceIO'
    'ExternalInput',       'WorkspaceIO'
    'LoadInitialState',    'WorkspaceIO'
    'InitialState',        'WorkspaceIO'
    'SaveTime',            'WorkspaceIO'
    'TimeSaveName',        'WorkspaceIO'
    'SaveState',           'WorkspaceIO'
    'StateSaveName',       'WorkspaceIO'
    'SaveOutput',          'WorkspaceIO'
    'OutputSaveName',      'WorkspaceIO'
    'SaveFinalState',      'WorkspaceIO'
    'FinalStateName',      'WorkspaceIO'
    'SaveFormat',          'WorkspaceIO'
    'LimitDataPoints',     'WorkspaceIO'
    'MaxDataPoints',       'WorkspaceIO'
    'Decimation',          'WorkspaceIO'
    ... Diagnostics
    'ConsistencyChecking',            'Diagnostics'
    'ArrayBoundsChecking',            'Diagnostics'
    'AlgebraicLoopMsg',               'Diagnostics'
    'BlockPriorityViolationMsg',      'Diagnostics'
    'MinStepSizeMsg',                 'Diagnostics'
    'MaxConsecutiveZCsMsg'            'Diagnostics'
    'InheritedTsInSrcMsg',            'Diagnostics'
    'DiscreteInheritContinuousMsg',   'Diagnostics'
    'MultiTaskRateTransMsg',          'Diagnostics'
    'SingleTaskRateTransMsg',         'Diagnostics'
    'CheckForMatrixSingularity',      'Diagnostics'
    'IntegerOverflowMsg',             'Diagnostics'
    'Int32ToFloatConvMsg',            'Diagnostics'
    'ParameterDowncastMsg',           'Diagnostics'
    'ParameterOverflowMsg',           'Diagnostics'
    'ParameterUnderflowMsg',          'Diagnostics'
    'ParameterPrecisionLossMsg',      'Diagnostics'
    'UnderSpecifiedDataTypeMsg',      'Diagnostics'
    'UnnecessaryDatatypeConvMsg',     'Diagnostics'
    'VectorMatrixConversionMsg',      'Diagnostics'
    'InvalidFcnCallConnMsg',          'Diagnostics'
    'SignalLabelMismatchMsg',         'Diagnostics'
    'UnconnectedInputMsg',            'Diagnostics'
    'UnconnectedOutputMsg',           'Diagnostics'
    'UnconnectedLineMsg',             'Diagnostics'
    'SfunCompatibilityCheckMsg',      'Diagnostics'
    ... Advanced                       
    'RTWInlineParameters',            'Advanced'
    'BlockReductionOpt',              'Advanced'
    'BooleanDataType',                'Advanced'
    'ConditionallyExecuteInputs',     'Advanced'
    'OptimizeBlockIOStorage',         'Advanced'
    'ZeroCross',                      'Advanced'
    'AssertionControl',               'Advanced'
    'ProdHWDeviceType',               'Advanced'
    'ProdHWWordLengths',              'Advanced'
    ... RTWBuildProcess
    'RTWSystemTargetFile',           'RTW' 
    'RTWTemplateMakefile',           'RTW'
    'RTWMakeCommand',                'RTW'
    'RTWGenerateCodeOnly',           'RTW' 
    'RTWRetainRTWFile',              'RTW'
    'RTWSystemCodeInlineAuto',       'RTW'
    'BufferReuse',                   'RTW'
    'RTWOptions',                    'RTW'
    ... TLC Debugging
    'TLCProfiler',                   'ProfileTLCCheckbox'
    'TLCDebug',                      'TLCDebugCheckbox'
    'TLCCoverage',                   'TLCCoverageCheckbox'
    'TLCAssertion',                  'TLCAssertionCheckbox'
  };

