function multiratespectypes = getmultiratespectypes(this)
%GETMULTIRATESPECTYPES   Get the multiratespectypes.

%   Author(s): J. Schickler
%   Copyright 2005 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2008/04/21 16:30:32 $

multiratespectypes = {'Fp,Fst,Ap,Ast', ...
        'N,Fc', ...
        'N,F3dB',...
        'N,Fc,Ap,Ast', ...
        'N,Fp,Ap,Ast', ...
        'N,Fp,Fst', ...
        'N,Fp,Fst,Ap', ...
        'N,Fp,Fst,Ast', ...
        'N,Fst,Ap,Ast'};

% [EOF]
