function list = defaultlutblklist
% Abstract:
%   Find all opened Simulink systems.
%   The result is a Java Hashtable object. The key is the string concatination
%   of BlockType and MaskType from a block.
%

% Copyright 2003-2009 The MathWorks, Inc.
% $Revision: 1.1.6.9 $

list = java.util.Hashtable;

% Create cell-array of Lookup_nD's 30 breakpoint parameter names.
breakpoints = cell(1,30);
for bpIdx = 1:length(breakpoints)
    breakpoints{bpIdx} = ['BreakpointsForDimension' num2str(bpIdx)];
end
% setup the list structure in the following format:
% { [BlockTypeName///MaskTypeName], {BreakPointNames, TableNames};
%   ...}
blkInfo = { ...
% 1
    ['Lookup',    '///', ''],{{'InputValues'},{''},{''},{'OutputValues'}}; ...
% 11
    ['Lookup2D',  '///', ''],{{'x','y'},{''},{''},{'Table'}}; ...
% 12
    ['Interpolation_n-D',  '///', ''],{{''},{'NumberOfTableDimensions'},{'NumberOfTableDimensions'},{'Table'}}; ...
% 13
    ['PreLookup',  '///', ''],{{'BreakpointsData'},{''},{''},{''}}; ...
% 14
    ['Lookup_n-D', '///', ''], ...
    {breakpoints, {'NumberOfTableDimensions'},{'NumberOfTableDimensions'}, {'Table'}}; ...
% 2
    ['SubSystem',  '///', 'Lookup Table (2-D)'],{{'x','y'},{''},{''},{'Table'}}; ...
% xxx(jkomissa) Should this be removed? 3
    ['S-Function', '///', 'LookupNDInterp'], ...
    {{'bp1','bp2','bp3','bp4','bpcell'}, ...
     {'numDimsPopupSelect'},{'explicitNumDims'}, {'tableData'}}; ...
% 4
    ['LookupNDDirect', '///', ''], ...
    {{''},{'NumberOfTableDimensions'},{'NumberOfTableDimensions'}, {'Table'}}; ...
% 5
    ['S-Function', '///', 'LookupIdxSearch'], {{'bpData'},{''},{''}, {''}}; ...
% 6 
    ['S-Function', '///', 'LookupNDInterpIdx'], ...
    {{''},{'numDimsPopupSelect'},{'explicitNumDims'}, {'table'}}; ...
% 7
    ['S-Function', '///', 'S-function: sfun_directlook'], ...
    {{'XVECT'},{''},{''},{'YVECT'}}; ...
% 8
    ['S-Function', '///', 'S-function: sftable2'], ...
    {{'xindex_idx', 'yindex_idx'},{''},{''}, {'table_idx'}}; ...
% 9 
    ['SubSystem',  '///', 'Repeating table'], ...
    {{'rep_seq_t'},{''},{''}, {'rep_seq_y'}}; ...
% 15 
    ['SubSystem',  '///', 'Repeating Sequence Interpolated'], ...
    {{'TimeValues'},{''},{''}, {'OutValues'}}; ...
% 10
    ['S-Function', '///', 'Fixed-Point Look-Up Table Dynamic'], ...
    {{''},{''},{''},{''}}; ...
	  };

for i = 1:length(blkInfo)
  list.put(blkInfo{i,1}, blkInfo{i,2});
end

% end
            

