function props = getPossibleProperties(h)
%GETPOSSIBLEPROPERTIES   Get the possible properties.

%   Author(s): G. Taillefer
%   Copyright 2006-2008 The MathWorks, Inc.
%   $Revision: 1.1.6.6 $  $Date: 2008/09/13 06:52:38 $

props = {...
    'LogSignal', ...
    'Run',...
    'SimDT',...
    'SpecifiedDT'...
    'ProposedDT', ...
    'Accept',...
    'DesignMin', ...
    'SimMin',...
    'ProposedMin',...
    'DesignMax', ...
    'SimMax',...
    'ProposedMax',...
    'OvfWrap',...
    'OvfSat',...
    'DivByZero',...
    'DTGroup', ...
    'InitValueMin',...
    'InitValueMax',...
    'ModelRequiredMin',...
    'ModelRequiredMax',...
        };

% [EOF]
