% Neural network name property.
% 
% NET.<a href="matlab:doc nnproperty.net_name">name</a>
%
% This property consists of a string defining the network name. Network
% creation functions such as feedforwardnet, define this appropriately.
% But it can be set to any string as desired.
%
% The network name is displayed in diagrams generated by <a href="matlab:doc view">view</a>.
%
%   net = feedforwardnet;
%   view(net)
%
% See also NETWORK/VIEW

% Copyright 2010 The MathWorks, Inc.
