function examples = getexamples(this)
%GETEXAMPLES   Get the examples.

%   Author(s): J. Schickler
%   Copyright 2005-2009 The MathWorks, Inc.
%   $Revision: 1.1.6.5 $  $Date: 2009/06/11 16:08:31 $

examples = {{ ...
    'Compare passband and stopband MatchExactly.', ...
    'h     = fdesign.lowpass(''Fp,Fst,Ap,Ast'', .1, .3, 1, 60);', ...
    'Hd    = design(h, ''cheby2'', ''MatchExactly'', ''passband'');', ...
    'Hd(2) = design(h, ''cheby2'', ''MatchExactly'', ''stopband'');', ...
    '', ...
    '% Compare the passband edges in FVTool.', ...
    'fvtool(Hd);', ...
    'axis([.09 .11 -2 0]);'}};

% [EOF]
